import {spawn} from 'node:child_process';
import {mkdtempSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
const root=process.argv[2], profile=mkdtempSync(join(root,'chrome-profile-'));
const child=spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--no-first-run','--no-default-browser-check','--disable-background-networking','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','pipe']});
let ws,seq=0,session;const pending=new Map(),exceptions=[],cells=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
writeFileSync(join(root,'browser-process.json'),JSON.stringify({pid:child.pid,profile,operation:'design-system-r11-lens-probe-20260927'}));
function send(method,params={},sid=session){return new Promise((resolve,reject)=>{const id=++seq;const timer=setTimeout(()=>{pending.delete(id);reject(new Error('CDP timeout '+method));},10000);pending.set(id,{resolve,reject,timer});ws.send(JSON.stringify({id,method,params,...(sid?{sessionId:sid}:{})}));});}
async function evaluate(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
const settle=()=>evaluate('document.fonts.ready.then(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))))');
async function key(key,code,v){const p={type:'keyDown',key,code,windowsVirtualKeyCode:v};if(key==='Enter')p.text=p.unmodifiedText='\r';else if(key.length===1)p.text=p.unmodifiedText=key;await send('Input.dispatchKeyEvent',p);await send('Input.dispatchKeyEvent',{type:'keyUp',key,code,windowsVirtualKeyCode:v});}
async function until(expr){for(let i=0;i<70;i++){if(await evaluate(expr))return;await sleep(60);}throw new Error('Condition timeout '+expr);}
async function shot(file,target){await evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(target)});scrollTo(0,e.getBoundingClientRect().top+scrollY-document.querySelector('.bar').getBoundingClientRect().height-16)})()`);await settle();await sleep(250);const d=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(join(root,file),Buffer.from(d.data,'base64'));}
try{
 const endpoint=await new Promise((resolve,reject)=>{let text='';const timer=setTimeout(()=>reject(new Error('Chrome launch timeout')),15000);child.stderr.on('data',b=>{text+=b.toString();const m=text.match(/DevTools listening on (ws:\/\/\S+)/);if(m){clearTimeout(timer);resolve(m[1]);}});child.on('exit',c=>{if(!text.includes('DevTools listening'))reject(new Error('Chrome exit '+c));});});
 ws=new WebSocket(endpoint);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});ws.onmessage=e=>{const d=JSON.parse(e.data);if(d.id&&pending.has(d.id)){const p=pending.get(d.id);clearTimeout(p.timer);pending.delete(d.id);d.error?p.reject(new Error(JSON.stringify(d.error))):p.resolve(d.result);}else if(d.method==='Runtime.exceptionThrown')exceptions.push(d.params);};
 const target=await send('Target.createTarget',{url:'about:blank'},null);session=(await send('Target.attachToTarget',{targetId:target.targetId,flatten:true},null)).sessionId;
 for(const method of ['Page.enable','Runtime.enable','Network.enable','Accessibility.enable'])await send(method);
 await send('Page.bringToFront');await send('Network.setBlockedURLs',{urls:['http://*','https://*']});await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});

 async function view(){return evaluate("(()=>{const p=document.querySelector('#lensPop');return {open:!!p&&p.classList.contains('open'),lock:document.documentElement.classList.contains('lens-lock'),focus:document.activeElement.id||document.activeElement.className,text:p?.innerText,aria:document.getElementById('plain').getAttribute('aria-describedby'),nested:document.getElementById('nested').dataset.count||'0',coarse:matchMedia('(hover:none)').matches}})()");}
 async function point(id,type){const p=await evaluate(`(()=>{const r=document.getElementById(${JSON.stringify(id)}).getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);if(type==='touch'){await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...p,radiusX:2,radiusY:2,force:1,id:1}]});await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else{await send('Input.dispatchMouseEvent',{type:'mouseMoved',...p});await send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...p});await send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...p});}await sleep(400);}
 for(const width of [1440,390])for(const input of ['keyboard','touch']){
  await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:input==='touch'});await send('Emulation.setTouchEmulationEnabled',{enabled:input==='touch',maxTouchPoints:1});
  const url=pathToFileURL(join(root,'lens-fixture.html')).href+'?case='+cells.length;await send('Page.navigate',{url});await until("document.readyState==='complete' && document.querySelector('#legacy').classList.contains('help-upgraded')");
  await evaluate("window.events=[];['pointerdown','pointerup','focusin','click','focusout'].forEach(n=>document.addEventListener(n,e=>events.push({type:n,target:e.target.id||e.target.className,open:!!document.querySelector('.lens-pop.open')}),true))");
  const checks=[];
  if(input==='keyboard') {await evaluate("document.getElementById('plain').focus()");await sleep(300);checks.push({name:'focus_shows_help',pass:(await view()).open});await key('Escape','Escape',27);await sleep(250);checks.push({name:'escape_closes',pass:!(await view()).open});await evaluate("document.getElementById('nested').focus()");await key('Enter','Enter',13);await sleep(300);checks.push({name:'nested_control_works',pass:(await view()).nested==='1'});}
  else {await point('plain','touch');let s=await view();checks.push({name:'first_tap_persists',pass:s.open,detail:s});await key('Escape','Escape',27);await sleep(220);await point('dedicated','touch');s=await view();checks.push({name:'dedicated_first_tap_persists',pass:s.open,detail:s});await key('Escape','Escape',27);await sleep(220);await point('nested','touch');s=await view();checks.push({name:'nested_control_works',pass:s.nested==='1'&&!s.open,detail:s});}
  cells.push({width,input,checks,events:await evaluate('window.events')});console.log('CELL',width,input,JSON.stringify(checks));
 }
 writeFileSync(join(root,'lens-baseline.json'),JSON.stringify({scope:'Exact LENS IIFE from pinned theme.js, isolated test fixture; no production changes',cells,exceptions},null,2));
 ws.send(JSON.stringify({id:++seq,method:'Browser.close',params:{}}));await sleep(500);
}catch(e){writeFileSync(join(root,'lens-probe-browser-error.txt'),String(e.stack));console.error(e);process.exitCode=1;}
finally{if(ws)ws.close();for(const p of pending.values())clearTimeout(p.timer);pending.clear();if(child.exitCode===null&&child.signalCode===null)child.kill('SIGTERM');await Promise.race([new Promise(r=>child.once('exit',r)),sleep(1800)]);writeFileSync(join(root,'browser-cleanup.json'),JSON.stringify({pid:child.pid,profile,exitCode:child.exitCode,signalCode:child.signalCode,closed:child.exitCode!==null||child.signalCode!==null}));child.stderr.destroy();child.unref();process.exit(process.exitCode||0);}
