"""tests/test_press_properties.py — D14 W1.5 press property trees.

Three things are pinned here, and only one of them is about HTML.

1. THE CUTOVER PAIRING.  config/press.yml `cutover` and the commented Caddy
   vhost block are two halves of one switch.  Either half alone is a defect:
   `cutover: true` with the block still commented routes articles to a domain
   nothing serves; an uncommented block with `cutover: false` stands up two
   public vhosts over an empty tree.  The guard asserts BOTH directions, so the
   cutover PR trips it if it forgets either half.

2. DETERMINISM.  engine/press/properties.py reads no wall clock, so two builds
   over one ledger are byte-identical.  That is not a nicety — it is the only
   reason `build_press_properties --check` can exist, and a single "generated
   at" stamp would make that check red on every run until somebody deleted it.
   Pinned twice: behaviourally (build twice, compare) and structurally (grep
   the sources for clock reads).

3. THE PRE-CUTOVER INVARIANT.  At `cutover: false` the emit path must write
   NOTHING under properties/ or content/press/ and must target exactly what it
   targeted before this change.  Everything else in W1.5 is dark by definition;
   this is the assertion that says so.

Every test builds under tmp_path.  Nothing here writes the repo's real
properties/ or content/press/ trees — those are generated by the build lane,
and a test that published into them would be exactly the accident the press
engine exists to prevent (see the MM_DATA_GUARD note in tests/conftest.py).

`test_real_templates_render_a_compliant_page` is the LIVE INTEGRATION GATE: the
one test that renders against the real templates/press/ files, which landed in
this same change.  It is deliberately not skip-guarded — a skip-guarded
integration test is an unrun test that reads green, and it exists precisely to
catch the two failures the renderer cannot see in its own fixtures: chrome the
template draws that the body ALSO carries, and a JSON-LD block that an
autoescaping template turned into unparseable text.

NOTHING HERE MAY HARDCODE THE PRE-CUTOVER STATE.  The cutover PR flips
config/press.yml and uncomments the Caddy block, and this suite has to go GREEN
on that PR, not red.  Assertions about the switch are written as a pure
bidirectional helper (`_pairing_violations`) applied to the real files, plus a
four-quadrant test over synthetic inputs that proves both legal states pass and
both half-flipped states fail.
"""
from __future__ import annotations

import json
import re
import shutil
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parent.parent
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from engine.press import desk_planner as P  # noqa: E402
from engine.press import properties as PR  # noqa: E402
from scripts import run_press as R  # noqa: E402
from tests import press_fixtures as F  # noqa: E402
from tests.workflow_staging import staged_paths  # noqa: E402

_CADDYFILE = _REPO / "app" / "deploy" / "Caddyfile"
_UPDATE_SH = _REPO / "app" / "deploy" / "update.sh"
_WORKFLOW = _REPO / ".github" / "workflows" / "press-publish.yml"
_BEGIN = "# PRESS-CUTOVER-BEGIN"
_END = "# PRESS-CUTOVER-END"


# ─────────────────────────────────────────────────────────────────────────────
# Fixture templates.
#
# Deliberately NOT the designer's real files: this suite must pin the RENDERER's
# contract, and a suite that imported the real templates would go red on every
# visual change and green on none of the defects it exists to catch.  The real
# templates get exactly one test, at the bottom of this file.
# ─────────────────────────────────────────────────────────────────────────────

_FRONT_TPL = """<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<title>{{ pub.label }}</title>
<link rel="canonical" href="{{ pub.base_url }}/">
<link rel="stylesheet" href="{{ css_href }}">
<link rel="alternate" type="application/rss+xml" href="{{ feed_href }}">
</head><body>
<header><a href="/">{{ pub.label }}</a> &mdash; {{ pub.tagline }}</header>
<nav><a href="{{ about_href }}">About</a> <a href="{{ feed_href }}">Feed</a></nav>
<main>
{%- for a in articles %}
<article data-native="{{ a.native }}">
  <h2><a href="{{ a.url }}">{{ a.title }}</a></h2>
  <p>{{ a.dek }}</p>
  <p>{{ a.desk_label }} &middot; {{ a.reading_minutes }} min</p>
  <time datetime="{{ a.published_iso }}">{{ a.published_display }}</time>
</article>
{%- endfor %}
</main>
<footer>{{ footer_text }}</footer>
</body></html>
"""

_ARTICLE_TPL = """<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<title>{{ a.title }}</title>
<link rel="canonical" href="{{ a.url }}">
<link rel="stylesheet" href="{{ css_href }}">
<script type="application/ld+json">{{ jsonld }}</script>
</head><body>
<nav><a href="/">{{ pub.label }}</a> <a href="{{ about_href }}">About</a>
<a href="{{ feed_href }}">Feed</a></nav>
<article>
<h1>{{ a.title }}</h1>
<p>{{ a.dek }}</p>
<p>{{ a.byline }} &middot; {{ a.desk_label }} &middot;
<time datetime="{{ a.published_iso }}">{{ a.published_display }}</time>
{%- if a.updated_display %} &middot; updated {{ a.updated_display }}{% endif %}
&middot; {{ a.reading_minutes }} min</p>
{{ a.body_html }}
{%- if a.corrections %}
<ul class="corrections">
{%- for c in a.corrections %}
<li>{{ c.date_display }}: {{ c.text }}</li>
{%- endfor %}
</ul>
{%- endif %}
</article>
<footer>{{ footer_text }}</footer>
</body></html>
"""

_ABOUT_TPL = """<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><title>About {{ pub.label }}</title>
<link rel="canonical" href="{{ pub.base_url }}/about.html">
<link rel="stylesheet" href="{{ css_href }}">
</head><body>
<nav><a href="/">{{ pub.label }}</a></nav>
<p>{{ pub.tagline }}</p>
<p><a href="{{ flagship_url }}">Mastermind</a></p>
<footer>{{ footer_text }}</footer>
</body></html>
"""

_404_TPL = """<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><title>Not found &middot; {{ pub.label }}</title>
<link rel="stylesheet" href="{{ css_href }}">
</head><body>
<nav><a href="/">{{ pub.label }}</a></nav>
<p>That page is not here.</p>
<footer>{{ footer_text }}</footer>
</body></html>
"""

_CSS = "/* fixture stylesheet */\n:root { color-scheme: light dark; }\n"


def _write_fixture_templates(root: Path) -> None:
    tpl = root / "templates" / "press"
    tpl.mkdir(parents=True, exist_ok=True)
    for prefix in ("news", "research"):
        (tpl / f"{prefix}_front.html.j2").write_text(_FRONT_TPL, encoding="utf-8")
        (tpl / f"{prefix}_article.html.j2").write_text(_ARTICLE_TPL, encoding="utf-8")
        (tpl / f"{prefix}_about.html.j2").write_text(_ABOUT_TPL, encoding="utf-8")
        (tpl / f"{prefix}_404.html.j2").write_text(_404_TPL, encoding="utf-8")
        (tpl / f"press_{prefix}.css").write_text(
            _CSS + f"/* {prefix} */\n", encoding="utf-8")


_MD = """---
slug: {slug}
family: article
title: "{title}"
description: "{desc}"
cluster: market-brief
published: {published}
updated: {updated}
---
<p class="press-byline">{byline}</p>
<p>{body}</p>
<p class="press-footer">Educational content — not investment advice. Markets involve risk.</p>
"""


def _write_md(path: Path, slug: str, *, title="A first-party read of the session",
              desc="Our own measurements moved this week, and here is the level "
                   "that would settle the question for the next session.",
              published="2026-07-26", updated="", byline="The Brief — Mastermind News desk",
              body="The composite reads 56 of 100, which is the number the rest of "
                   "this note leans on.") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_MD.format(slug=slug, title=title, desc=desc, published=published,
                               updated=updated or published, byline=byline, body=body),
                    encoding="utf-8")


def _row(slug: str, *, pub="mastermind_news", desk="brief", ts="2026-07-26T13:20:00Z",
         url=None, title=None, rid=None) -> dict:
    row = {"id": rid or f"press-{desk}-{slug}", "ts": ts, "desk": desk,
           "publication": pub, "slug": slug, "sources": [], "seed_refs": [],
           "validator_report": {"ok": True},
           "urls": [url or f"https://www.mastermind-x.com/blog/{slug}.html"]}
    if url is not None:
        row["url"] = url
    if title is not None:
        row["title"] = title
    return row


def _property_root(tmp_path: Path, rows: list[dict] | None = None,
                   *, cutover: bool = False) -> Path:
    """A repo root carrying config, fixture templates and a press ledger."""
    import yaml

    root = tmp_path / "repo"
    (root / "config").mkdir(parents=True, exist_ok=True)
    cfg = yaml.safe_load((_REPO / "config" / "press.yml").read_text(encoding="utf-8"))
    cfg["cutover"] = bool(cutover)
    (root / "config" / "press.yml").write_text(yaml.safe_dump(cfg, sort_keys=False),
                                               encoding="utf-8")
    _write_fixture_templates(root)
    ledger = root / "data" / "press" / "published.jsonl"
    ledger.parent.mkdir(parents=True, exist_ok=True)
    ledger.write_text("".join(json.dumps(r) + "\n" for r in (rows or [])),
                      encoding="utf-8")
    (root / "content" / "seo" / "blog").mkdir(parents=True, exist_ok=True)
    return root


def _tree_bytes(tree: Path) -> dict[str, bytes]:
    return {str(p.relative_to(tree)): p.read_bytes()
            for p in sorted(tree.rglob("*")) if p.is_file()}


# ─────────────────────────────────────────────────────────────────────────────
# (a) THE CUTOVER SYNC GUARD
# ─────────────────────────────────────────────────────────────────────────────


def _caddy_lines(text: str | None = None) -> list[str]:
    return (text if text is not None
            else _CADDYFILE.read_text(encoding="utf-8")).splitlines()


def _marker_bounds(lines: list[str]) -> tuple[int, int]:
    return lines.index(_BEGIN), lines.index(_END)


def _uncommented(lines: list[str]) -> list[str]:
    """The block's interior as Caddy would see it once the cutover has happened.

    State-aware: strips one leading '#' only while the block is still commented.
    Stripping unconditionally would, after the real cutover, eat the '#' off the
    block's own inline comments and turn them into bare directives — a guard
    that reports a syntax error it invented itself.
    """
    b, e = _marker_bounds(lines)
    interior = lines[b + 1:e]
    if all(l.startswith("#") for l in interior):
        return [l[1:] for l in interior]
    return interior


def _pairing_violations(cutover: bool, caddyfile_text: str) -> list[str]:
    """THE PAIRING, as a pure function of (flag, file).

    Pure on purpose.  A guard written directly against the repo's current files
    can only ever encode the state those files are in TODAY — which is how a
    cutover guard ends up asserting that the cutover may never happen.  Written
    this way it is checked twice: once against the real files (whatever state
    they are in), and once over synthetic inputs covering all four quadrants,
    where both failure modes are actually exercised.

    Returns a list of human-readable violations; empty means consistent.
    """
    lines = _caddy_lines(caddyfile_text)
    problems: list[str] = []
    if lines.count(_BEGIN) != 1 or lines.count(_END) != 1:
        return [f"markers must appear exactly once each "
                f"(begin={lines.count(_BEGIN)}, end={lines.count(_END)})"]
    b, e = _marker_bounds(lines)
    if b >= e:
        return ["the END marker must follow the BEGIN marker"]
    interior = lines[b + 1:e]
    if not interior:
        return ["the cutover block has no interior lines"]

    # A LIVE line is a directive Caddy will act on. A '#' line is inert whatever
    # the flag says — the block carries its own prose, written '##' so that one
    # '#' survives the transform. So the state is read from the LIVE lines, not
    # from the absence of comments; a '##' line that is still '##' after a
    # cutover is the tell that the transform skipped it.
    live = [l for l in interior if l.strip() and not l.startswith("#")]
    untransformed = [l for l in interior if l.startswith("##")]
    if cutover is False and live:
        problems.append(
            "config/press.yml has `cutover: false` but these Caddyfile lines are "
            f"live: {live[:5]} — re-comment the block, or flip cutover in the SAME "
            "commit")
    if cutover is True:
        if not live:
            problems.append(
                "config/press.yml has `cutover: true` but the Caddyfile press block "
                "is still fully commented out — uncomment it in the SAME commit "
                "(see app/deploy/README.md § Press properties (W1.5))")
        elif untransformed:
            problems.append(
                "the Caddyfile press block is live but these lines never had their "
                f"leading '#' stripped: {untransformed[:5]} — the uncomment "
                "transform was applied by hand and missed them")
    return problems


# The block's committed (dark) form, in the real file's idiom: config lines get
# one '#', prose gets two so that one survives.
_SYNTHETIC_DARK = ["## the news property",
                   "#mastermindx.ai {",
                   "#\troot * /opt/macro/press_news.served",
                   "#}"]


def _synthetic(commented: bool) -> str:
    """A minimal Caddyfile carrying the marker pair in one of the two states.

    The LIVE form is DERIVED from the dark form by the same one-'#'-strip the
    runbook performs, rather than hand-written. Hand-writing it is how a
    quadrant test ends up proving something about a file shape that the real
    transform never produces — which it did, on the first attempt here: the
    hand-written "live" form left a '##' prose line that the real transform
    would have reduced to '#'.
    """
    if commented:
        return "\n".join(["# unrelated preamble", _BEGIN, *_SYNTHETIC_DARK, _END, ""])
    live = [l[1:] if l.startswith("#") else l for l in _SYNTHETIC_DARK]
    return "\n".join(["# unrelated preamble", _BEGIN, *live, _END, ""])


def test_the_cutover_markers_appear_exactly_once():
    """A duplicated marker makes every index() below silently pick the first
    pair, which is how a guard starts checking a different block than the one
    that ships."""
    text = _CADDYFILE.read_text(encoding="utf-8")
    assert text.count(_BEGIN) == 1, "PRESS-CUTOVER-BEGIN must appear exactly once"
    assert text.count(_END) == 1, "PRESS-CUTOVER-END must appear exactly once"
    lines = _caddy_lines()
    b, e = _marker_bounds(lines)
    assert b < e, "the END marker must follow the BEGIN marker"
    assert e - b > 10, "the cutover block is empty — that is not a shipped block"


def test_the_shipped_files_are_a_consistent_pair():
    """The real config + the real Caddyfile, in whatever state they are in.

    This test is state-AGNOSTIC by construction: it passes before the cutover
    and after it, and fails only on a half-flipped switch.
    """
    cutover = P.load_config(_REPO).get("cutover")
    assert cutover in (True, False), \
        f"config/press.yml cutover must be a bool, got {cutover!r}"
    problems = _pairing_violations(cutover,
                                   _CADDYFILE.read_text(encoding="utf-8"))
    assert not problems, "\n".join(problems)


@pytest.mark.parametrize("cutover,commented,legal", [
    (False, True, True),     # today: dark config, dark vhosts
    (True, False, True),     # cutover day: live config, live vhosts
    (False, False, False),   # vhosts live, nothing routed to them
    (True, True, False),     # routed emit, nothing serving it
])
def test_the_pairing_guard_catches_both_half_flips(cutover, commented, legal):
    """FOUR QUADRANTS, over synthetic inputs.

    The two legal states must PASS and the two half-flipped states must FAIL.
    A one-directional guard passes three of these four and lets exactly one
    disaster through — and which one depends on which direction was written,
    which is not a property anybody remembers a year later.
    """
    problems = _pairing_violations(cutover, _synthetic(commented))
    if legal:
        assert not problems, f"a legal state was rejected: {problems}"
    else:
        assert problems, (
            f"half-flipped state (cutover={cutover}, commented={commented}) "
            "was accepted — the guard is one-directional")


def test_the_pairing_guard_rejects_a_duplicated_marker():
    """A duplicated marker makes every index() pick the first pair, which is how
    a guard starts checking a different block than the one that ships."""
    doubled = _synthetic(True) + _synthetic(True)
    assert _pairing_violations(False, doubled)


def test_the_uncommented_block_is_the_config_we_intend_to_serve():
    """What `sed 's/^#//'` produces has to be the real thing, not approximately
    it: nobody reads a commented block as configuration, so this is the only
    place its shape is ever checked before it goes live."""
    block = "\n".join(_uncommented(_caddy_lines()))
    directives = "\n".join(l for l in block.splitlines() if not l.lstrip().startswith("#"))

    assert directives.count("{") == directives.count("}"), \
        "unbalanced braces in the cutover block"
    assert "\nblog.mastermind-x.com {" in "\n" + directives
    assert "root * /opt/macro/press_news.served" in directives
    assert "root * /opt/macro/press_research.served" in directives

    # ONE CANONICAL HOST: the apex serves, www 301s to it. Serving both names
    # off one block puts every page on two live URLs and leaves rel=canonical —
    # a hint, not an instruction — to sort it out.
    assert "\nmastermindx.ai {" in "\n" + directives, "the apex must be its own site block"
    assert "mastermindx.ai, www.mastermindx.ai {" not in directives, \
        "apex and www must not share one serving block"
    assert "www.mastermindx.ai {\n" in directives
    assert "redir https://mastermindx.ai{uri} permanent" in directives, \
        "www must 301 to the apex — the host config/press.yml base_url names"

    # REAL certificates. These hosts are grey-cloud direct A records with no CDN
    # in front, so `tls internal` would hand a browser a self-signed cert.
    assert "tls internal" not in directives, (
        "the press vhosts are direct/grey-cloud — they take real Let's Encrypt "
        "certs over HTTP-01, never `tls internal`")

    assert directives.count("Content-Security-Policy") == 2, "both vhosts need a CSP"
    assert "frame-ancestors 'none'" in directives
    assert "X-Content-Type-Options" in directives and "X-Frame-Options" in directives

    # HSTS RAMP. A long max-age on a brand-new host is not revocable: a client
    # that cached it refuses plain http until it expires, so a cert or DNS
    # mistake is unreachable-by-design. Ship 300s, raise it after a clean week.
    hsts = re.findall(r'Strict-Transport-Security "max-age=(\d+)"', directives)
    assert hsts, "both vhosts need HSTS"
    assert all(int(v) <= 300 for v in hsts), (
        f"press vhosts ship an un-revocable HSTS max-age {hsts} on day one — "
        "start at 300 and raise it in a follow-up (app/deploy/README.md step 5)")

    # `auto_https disable_redirects` is global, so each host needs its own.
    for host in ("http://mastermindx.ai", "http://www.mastermindx.ai",
                 "http://blog.mastermind-x.com"):
        assert f"{host} {{" in directives, \
            f"missing the plain-HTTP redirect block for {host}"
    assert directives.count("redir https://") == 4, \
        "three http->https redirects plus the www->apex canonical redirect"

    assert "max-age=31536000, immutable" in directives, \
        "versioned assets need the immutable cache"
    assert "handle_errors" in directives and "/404.html" in directives


def test_block_comments_survive_the_uncomment_as_comments():
    """A prose line inside the block must carry a DOUBLE '#'.

    THE DEFECT THIS CLOSES, found by running the real `caddy validate` on the
    transformed file: a single-'#' comment inside the block loses its '#' to the
    uncomment and becomes a bare line, which Caddy reads as a SITE ADDRESS
    ("Site addresses cannot contain a comma"). The cutover would have failed
    validation on the box — where the only symptom is update.sh refusing to
    install the new config, at 3am, silently.

    Checked structurally rather than by guessing which lines look like prose:
    in Caddyfile grammar every line at brace-depth 0 opens a site block and
    therefore ends in '{'. A surviving comment lands at depth 0 and does not.
    """
    depth = 0
    for line in _uncommented(_caddy_lines()):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            depth += line.count("{") - line.count("}")
            continue
        if depth == 0:
            assert stripped.endswith("{"), (
                f"line {stripped!r} sits at brace-depth 0 after the uncomment but does "
                "not open a site block — Caddy reads it as a site address. Prose inside "
                "the block must use '##' so one '#' survives the transform.")
        depth += line.count("{") - line.count("}")
        assert depth >= 0, f"unbalanced closing brace at {stripped!r}"
    assert depth == 0, "the uncommented block does not close every brace it opens"


# ─────────────────────────────────────────────────────────────────────────────
# (b) determinism
# ─────────────────────────────────────────────────────────────────────────────


def test_two_builds_over_one_ledger_are_byte_identical(tmp_path):
    """The property that makes `--check` possible at all."""
    rows = [_row("first-note"), _row("second-note", ts="2026-07-27T13:20:00Z")]
    root = _property_root(tmp_path, rows)
    for slug in ("first-note", "second-note"):
        _write_md(root / "content" / "seo" / "blog" / f"{slug}.md", slug)

    a, b = tmp_path / "a", tmp_path / "b"
    PR.render_property(root, P.load_config(root), "mastermind_news", dest=a)
    PR.render_property(root, P.load_config(root), "mastermind_news", dest=b)
    assert _tree_bytes(a) == _tree_bytes(b)
    assert _tree_bytes(a), "the build produced nothing — the comparison is vacuous"


def test_check_mode_reports_drift_in_both_directions(tmp_path, capsys):
    """--check must catch a MUTATED file and an EXTRA one; an append-only ledger
    means a file with no row behind it is a hand edit, not garbage."""
    from scripts import build_press_properties as B

    rows = [_row("first-note")]
    root = _property_root(tmp_path, rows)
    _write_md(root / "content" / "seo" / "blog" / "first-note.md", "first-note")
    cfg = P.load_config(root)

    assert B.main(["--root", str(root), "--publications", "news"]) == 0
    capsys.readouterr()
    assert B.main(["--root", str(root), "--publications", "news", "--check"]) == 0

    tree = PR.property_tree_path(root, cfg, "mastermind_news")
    (tree / "robots.txt").write_text("User-agent: *\nDisallow: /\n", encoding="utf-8")
    (tree / "stray.html").write_text("<html></html>", encoding="utf-8")
    assert B.main(["--root", str(root), "--publications", "news", "--check"]) == 1
    err = capsys.readouterr().err
    assert "DIFFERS" in err and "robots.txt" in err
    assert "EXTRA" in err and "stray.html" in err


# ─────────────────────────────────────────────────────────────────────────────
# (c) the empty property
# ─────────────────────────────────────────────────────────────────────────────


def test_an_empty_ledger_still_builds_a_valid_property(tmp_path):
    """An empty feed is a real state, not an error state.  Day one of a
    publication looks exactly like this."""
    root = _property_root(tmp_path, [])
    tree = tmp_path / "out"
    PR.render_property(root, P.load_config(root), "mastermind_news", dest=tree)

    for name in ("index.html", "about.html", "404.html", "feed.xml",
                 "sitemap.xml", "robots.txt", "assets/press_news.css"):
        assert (tree / name).exists(), f"missing {name}"
    assert not (tree / "articles").exists(), "no articles means no article directory"

    front = (tree / "index.html").read_text(encoding="utf-8")
    assert "<article" not in front, "an empty front page must list no articles"

    feed = ET.fromstring((tree / "feed.xml").read_text(encoding="utf-8"))
    assert feed.findall("./channel/item") == []
    assert feed.findall("./channel/lastBuildDate") == [], \
        "lastBuildDate on an item-less feed could only come from the clock"

    urls = [u.text for u in ET.fromstring(
        (tree / "sitemap.xml").read_text(encoding="utf-8")).iter(
        "{http://www.sitemaps.org/schemas/sitemap/0.9}loc")]
    assert urls == ["https://mastermindx.ai/", "https://mastermindx.ai/about.html"]

    assert (tree / "robots.txt").read_text(encoding="utf-8") == (
        "User-agent: *\nAllow: /\nSitemap: https://mastermindx.ai/sitemap.xml\n")


# ─────────────────────────────────────────────────────────────────────────────
# (d) a populated property
# ─────────────────────────────────────────────────────────────────────────────

_NATIVE_URL = "https://mastermindx.ai/articles/native-note.html"


def _populated(tmp_path: Path) -> tuple[Path, Path, dict]:
    """A ledger spanning the cutover: a pre-cutover row with no url/title, a
    routed native row, a cross-domain row, and an orphan whose .md is gone."""
    rows = [
        # Pre-cutover shape: no `url`, no `title` — every row written by W1.
        _row("legacy-note", ts="2026-07-20T13:20:00Z"),
        _row("cross-note", ts="2026-07-24T13:20:00Z",
             url="https://www.mastermind-x.com/blog/cross-note.html",
             title="A cross-posted note"),
        _row("native-note", ts="2026-07-26T13:20:00Z", url=_NATIVE_URL,
             title="A native note"),
        _row("gone-note", ts="2026-07-27T13:20:00Z",
             url="https://mastermindx.ai/articles/gone-note.html", title="Vanished"),
        # A different publication's row must not leak onto this property.
        _row("other-desk-note", pub="mastermind_research", desk="research_desk",
             ts="2026-07-25T13:20:00Z"),
    ]
    root = _property_root(tmp_path, rows)
    _write_md(root / "content" / "seo" / "blog" / "legacy-note.md", "legacy-note",
              title="The legacy note", published="2026-07-20")
    _write_md(root / "content" / "seo" / "blog" / "cross-note.md", "cross-note",
              title="A cross-posted note", published="2026-07-24")
    _write_md(root / "content" / "press" / "news" / "native-note.md", "native-note",
              title="A native note", published="2026-07-26")
    _write_md(root / "content" / "seo" / "blog" / "other-desk-note.md",
              "other-desk-note", title="Research desk note", published="2026-07-25")
    # gone-note deliberately has NO .md — the orphan case.
    tree = tmp_path / "out"
    cfg = P.load_config(root)
    return root, tree, cfg


def test_a_populated_front_page_lists_newest_first(tmp_path, capsys):
    root, tree, cfg = _populated(tmp_path)
    PR.render_property(root, cfg, "mastermind_news", dest=tree)
    capsys.readouterr()

    articles = PR.iter_publication_articles(root, cfg, "mastermind_news")
    assert [a["slug"] for a in articles] == ["native-note", "cross-note", "legacy-note"], \
        "newest first, orphan dropped, other publication excluded"
    assert [a["published_display"] for a in articles] == \
        ["Jul 26, 2026", "Jul 24, 2026", "Jul 20, 2026"]

    front = (tree / "index.html").read_text(encoding="utf-8")
    assert front.index(_NATIVE_URL) < front.index(
        "https://www.mastermind-x.com/blog/cross-note.html")
    # A pre-cutover row carries no url; the derived flagship URL is what shows.
    assert "https://www.mastermind-x.com/blog/legacy-note.html" in front


def test_an_orphan_ledger_row_warns_at_line_start_and_is_skipped(tmp_path, capsys):
    """A row whose .md is gone must not render an empty article, and must not
    disappear quietly — the ledger is append-only, so the row is evidence."""
    root, tree, cfg = _populated(tmp_path)
    PR.render_property(root, cfg, "mastermind_news", dest=tree)
    out = capsys.readouterr().out

    lines = [l for l in out.splitlines() if "press_property_orphan_row" in l]
    assert lines, "the orphan row produced no annotation at all"
    # House law: a "::warning" behind a logger prefix is not a line start and
    # GitHub silently drops it.
    for line in lines:
        assert line.startswith("::warning title=press_property_orphan_row::"), line
    assert any("gone-note" in l for l in lines)
    assert not (tree / "articles" / "gone-note.html").exists()


def test_cross_domain_rows_are_listed_but_never_hosted_or_claimed(tmp_path, capsys):
    """The pre-cutover shape, and the whole no-migration argument: a row that
    was published on the flagship appears on the front page and in the feed, has
    no local file, and is NOT in this domain's sitemap."""
    root, tree, cfg = _populated(tmp_path)
    PR.render_property(root, cfg, "mastermind_news", dest=tree)
    capsys.readouterr()

    assert (tree / "articles" / "native-note.html").exists()
    assert not (tree / "articles" / "cross-note.html").exists()
    assert not (tree / "articles" / "legacy-note.html").exists()

    feed_links = [i.findtext("link") for i in ET.fromstring(
        (tree / "feed.xml").read_text(encoding="utf-8")).findall("./channel/item")]
    assert _NATIVE_URL in feed_links
    assert "https://www.mastermind-x.com/blog/cross-note.html" in feed_links

    sitemap = [u.text for u in ET.fromstring(
        (tree / "sitemap.xml").read_text(encoding="utf-8")).iter(
        "{http://www.sitemaps.org/schemas/sitemap/0.9}loc")]
    assert sitemap == ["https://mastermindx.ai/", "https://mastermindx.ai/about.html",
                       _NATIVE_URL]
    assert not any("mastermind-x.com/blog" in u for u in sitemap), \
        "another host's URL in this host's sitemap is a claim we do not get to make"


def test_feed_and_sitemap_parse_and_carry_derived_dates(tmp_path, capsys):
    root, tree, cfg = _populated(tmp_path)
    PR.render_property(root, cfg, "mastermind_news", dest=tree)
    capsys.readouterr()

    feed = ET.fromstring((tree / "feed.xml").read_text(encoding="utf-8"))
    items = feed.findall("./channel/item")
    assert len(items) == 3
    assert feed.findtext("./channel/lastBuildDate") == items[0].findtext("pubDate")
    assert items[0].findtext("pubDate") == "Sun, 26 Jul 2026 13:20:00 GMT"
    for item in items:
        guid = item.find("guid")
        assert guid.get("isPermaLink") == "true"
        assert guid.text == item.findtext("link")
    ET.fromstring((tree / "sitemap.xml").read_text(encoding="utf-8"))


def test_every_internal_href_resolves(tmp_path, capsys):
    """A root-relative href that resolves to nothing is a 404 on a page we
    shipped ourselves."""
    root, tree, cfg = _populated(tmp_path)
    PR.render_property(root, cfg, "mastermind_news", dest=tree)
    capsys.readouterr()

    broken: list[str] = []
    for page in sorted(tree.rglob("*.html")):
        for href in re.findall(r'href="([^"]+)"', page.read_text(encoding="utf-8")):
            if href.startswith("https://"):
                continue
            if not href.startswith("/"):
                broken.append(f"{page.name}: relative href {href!r}")
                continue
            rel = href.split("?", 1)[0].split("#", 1)[0].lstrip("/") or "index.html"
            if not (tree / rel).is_file():
                broken.append(f"{page.name}: {href!r} resolves to nothing")
    assert not broken, broken


def test_jsonld_parses_and_types_itself_by_publication(tmp_path, capsys):
    root, tree, cfg = _populated(tmp_path)
    PR.render_property(root, cfg, "mastermind_news", dest=tree)
    capsys.readouterr()

    page = (tree / "articles" / "native-note.html").read_text(encoding="utf-8")
    raw = re.search(r'<script type="application/ld\+json">(.*?)</script>',
                    page, re.DOTALL).group(1)
    data = json.loads(raw)
    assert data["@type"] == "NewsArticle"
    assert data["url"] == _NATIVE_URL
    assert data["datePublished"] == "2026-07-26T13:20:00Z"
    assert data["author"]["@type"] == "Organization", \
        "desk copy has an organisation author — a person here would be a fabricated person"
    assert data["publisher"]["name"] == "Mastermind"
    assert data["isAccessibleForFree"] is True
    assert "dateModified" not in data, "no update, no dateModified"

    pub = PR.publication_context(cfg, "mastermind_research")
    article = dict(title="t", dek="d", url="u", published_iso="2026-07-26T00:00:00Z",
                   byline="Research Desk")
    assert json.loads(PR.jsonld_for(pub, article))["@type"] == "Article"


def test_jsonld_carries_dateModified_only_when_the_piece_was_updated(tmp_path, capsys):
    root = _property_root(tmp_path, [_row("edited-note", url=
                                          "https://mastermindx.ai/articles/edited-note.html")])
    _write_md(root / "content" / "seo" / "blog" / "edited-note.md", "edited-note",
              published="2026-07-20", updated="2026-07-24")
    cfg = P.load_config(root)
    article = PR.iter_publication_articles(root, cfg, "mastermind_news")[0]
    capsys.readouterr()
    assert article["updated_display"] == "Jul 24, 2026"
    data = json.loads(PR.jsonld_for(PR.publication_context(cfg, "mastermind_news"), article))
    assert data["dateModified"] == "2026-07-24T00:00:00Z"


_BREAKOUT_TITLE = 'Note </script><img src=x onerror=alert(1)><script>'


def test_a_title_cannot_break_out_of_the_jsonld_script_element(tmp_path, capsys):
    """SCRIPT INJECTION THROUGH A HEADLINE.

    HTML parsing beats JSON parsing: `</script>` inside the ld+json block ends
    the element early and everything after it is parsed as MARKUP. The title
    comes from a .md file, and a .md file is written by an LLM — so this is
    reachable by anything that can influence a draft title.
    """
    url = "https://mastermindx.ai/articles/breakout-note.html"
    root = _property_root(tmp_path, [_row("breakout-note", url=url)])
    _write_md(root / "content" / "seo" / "blog" / "breakout-note.md", "breakout-note",
              title=_BREAKOUT_TITLE)
    tree = tmp_path / "out"
    PR.render_property(root, P.load_config(root), "mastermind_news", dest=tree)
    capsys.readouterr()

    page = (tree / "articles" / "breakout-note.html").read_text(encoding="utf-8")
    raw = re.search(r'<script type="application/ld\+json">(.*?)</script>',
                    page, re.DOTALL).group(1)

    assert "</script>" not in raw, "the JSON-LD block can be closed from inside"
    assert "<script>" not in raw and "<img" not in raw
    data = json.loads(raw)
    # The ESCAPE is on the wire only — the parsed object is unchanged.
    assert data["headline"] == _BREAKOUT_TITLE


def test_the_script_escape_leaves_the_parsed_object_identical():
    """`\\u003c` and friends are ordinary JSON escapes, so escaping must be
    invisible to a parser."""
    payload = {"a": "<b>&amp;</b>", "b": "already \\u003c literal",
               "c": "5 > 3 & 2 < 4", "d": "</script>"}
    raw = json.dumps(payload, ensure_ascii=False)
    escaped = PR._script_safe_json(raw)

    assert json.loads(escaped) == payload, "escaping changed the parsed object"
    for ch in "<>":
        assert ch not in escaped, f"{ch!r} survived the escape"
    assert "</script>" not in escaped


def test_the_script_escape_is_order_independent():
    """The obvious worry about three chained .replace() calls is that one pass
    corrupts another's output.  It cannot, and this pins WHY rather than
    freezing an arbitrary order: every replacement emits `\\u00XX`, and none of
    the characters in that output is one of the three triggers `&`, `<`, `>`.
    Disjoint alphabets in and out, so all six orderings agree.

    Written as an equivalence rather than "& must be first" so that a future
    reshuffle of those three lines cannot silently start mattering.
    """
    import itertools

    payload = {"x": "</script> & <b>5 > 3</b> &amp; \\u0026 literal"}
    raw = json.dumps(payload, ensure_ascii=False)
    subs = {"&": "\\u0026", "<": "\\u003c", ">": "\\u003e"}

    results = set()
    for order in itertools.permutations(subs):
        out = raw
        for ch in order:
            out = out.replace(ch, subs[ch])
        results.add(out)
    assert len(results) == 1, (
        f"the three escapes are NOT order-independent ({len(results)} distinct "
        "results) — the disjoint-alphabet argument in _script_safe_json is wrong")
    assert results.pop() == PR._script_safe_json(raw)
    assert json.loads(PR._script_safe_json(raw)) == payload


def test_a_slug_that_is_a_path_escape_writes_nothing_and_warns(tmp_path, capsys):
    """A slug becomes a file path. `../../..` would write outside the property
    entirely, so it is refused before any path is built."""
    good_url = "https://mastermindx.ai/articles/good-note.html"
    rows = [_row("../../../../ESCAPED", url="https://mastermindx.ai/articles/x.html",
                 rid="press-brief-evil"),
            _row("good-note", url=good_url)]
    root = _property_root(tmp_path, rows)
    _write_md(root / "content" / "seo" / "blog" / "good-note.md", "good-note")
    tree = tmp_path / "out"
    tree.mkdir()

    written = PR.render_property(root, P.load_config(root), "mastermind_news", dest=tree)
    out = capsys.readouterr().out

    lines = [l for l in out.splitlines() if "press_property_bad_slug" in l]
    assert lines, "a path-escape slug produced no annotation"
    for line in lines:
        assert line.startswith("::warning title=press_property_bad_slug::"), line

    # The build SUCCEEDS — one poisoned row must not take the property down.
    assert (tree / "articles" / "good-note.html").exists()
    # Nothing escaped the tree, and nothing landed inside it for the bad row.
    assert all((tree / rel).resolve().is_relative_to(tree.resolve()) for rel in written)
    assert not list(tmp_path.glob("ESCAPED*"))
    assert not list(tmp_path.glob("*/ESCAPED*"))
    assert [p.name for p in (tree / "articles").iterdir()] == ["good-note.html"]


def test_a_same_domain_row_at_the_wrong_path_is_demoted_not_mislinked(tmp_path, capsys):
    """A row on our own domain at some OTHER path would make us write
    articles/<slug>.html and then link somewhere else — a sitemap entry for a
    URL we do not serve, and an orphan file we do."""
    odd = "https://mastermindx.ai/2026/07/odd-note.html"
    root = _property_root(tmp_path, [_row("odd-note", url=odd)])
    _write_md(root / "content" / "seo" / "blog" / "odd-note.md", "odd-note")
    tree = tmp_path / "out"
    PR.render_property(root, P.load_config(root), "mastermind_news", dest=tree)
    out = capsys.readouterr().out

    lines = [l for l in out.splitlines() if "press_property_url_mismatch" in l]
    assert lines and all(
        l.startswith("::warning title=press_property_url_mismatch::") for l in lines)

    assert not (tree / "articles").exists(), "a demoted row must not get a local file"
    assert odd in (tree / "index.html").read_text(encoding="utf-8"), \
        "it is still one of this desk's articles — it is listed, just not hosted"
    assert odd in (tree / "feed.xml").read_text(encoding="utf-8")
    assert odd not in (tree / "sitemap.xml").read_text(encoding="utf-8"), \
        "a URL we do not serve must not be claimed in our sitemap"


def test_the_estate_byline_and_footer_are_stripped_for_a_property_page(tmp_path, capsys):
    """DOUBLE CHROME.  The .md contract REQUIRES an in-body byline and an
    in-body disclosure footer (validators enforce it, and the /blog/ estate
    renders the body with them).  A property template draws both itself, so the
    body must arrive without them or every article prints both twice.
    """
    root, tree, cfg = _populated(tmp_path)
    article = next(a for a in PR.iter_publication_articles(root, cfg, "mastermind_news")
                   if a["slug"] == "native-note")
    capsys.readouterr()

    assert "press-byline" not in article["body_html"]
    assert "press-footer" not in article["body_html"]
    assert cfg["validators"]["footer_required_text"] not in article["body_html"]
    assert article["body_html"].startswith("<p>"), \
        "stripping must leave the real body, not an empty string"
    assert "composite reads 56" in article["body_html"]

    # The .md ON DISK is untouched — it is the archive and the estate's source.
    md = (root / "content" / "press" / "news" / "native-note.md").read_text(encoding="utf-8")
    assert 'class="press-byline"' in md and 'class="press-footer"' in md


def test_chrome_stripping_is_a_no_op_when_there_is_no_chrome():
    cfg = F.config()
    body = "<p>Just a body.</p>\n<p>And another.</p>"
    assert PR.strip_estate_chrome(body, cfg) == body


def test_reading_minutes_never_returns_zero():
    assert PR.reading_minutes("<p>one two three</p>") == 1
    assert PR.reading_minutes("") == 1
    assert PR.reading_minutes("<p>" + "word " * 600 + "</p>") == 3


# ─────────────────────────────────────────────────────────────────────────────
# (e) StrictUndefined
# ─────────────────────────────────────────────────────────────────────────────


def test_a_missing_context_key_raises_instead_of_rendering_blank(tmp_path):
    """A silently blank masthead is the failure this environment exists to
    prevent: it ships, it looks almost right, and nothing goes red."""
    import jinja2

    root = _property_root(tmp_path, [])
    (root / "templates" / "press" / "probe.html.j2").write_text(
        "<p>{{ pub.label }}</p><p>{{ nonexistent_key }}</p>", encoding="utf-8")
    env = PR._env(root)
    with pytest.raises(jinja2.UndefinedError):
        env.get_template("probe.html.j2").render(pub={"label": "x"})


def test_a_missing_template_fails_loudly(tmp_path):
    import jinja2

    root = _property_root(tmp_path, [])
    (root / "templates" / "press" / "news_front.html.j2").unlink()
    with pytest.raises(jinja2.TemplateNotFound):
        PR.render_property(root, P.load_config(root), "mastermind_news",
                           dest=tmp_path / "out")


# ─────────────────────────────────────────────────────────────────────────────
# (f) the clock sentinel
# ─────────────────────────────────────────────────────────────────────────────

_CLOCK_READS = ("datetime.now", "utcnow", ".today(", "time.time", "time.gmtime",
                "time.localtime", "time.monotonic", "st_mtime", "getmtime")

# One probe per token. A sentinel with nine tokens and one probe proves one
# token works and the other eight are decoration.
_CLOCK_PROBES = {
    "datetime.now": "x = datetime.now(timezone.utc)",
    "utcnow": "x = datetime.utcnow()",
    ".today(": "x = date.today()",
    "time.time": "x = time.time()",
    "time.gmtime": "x = time.gmtime()",
    "time.localtime": "x = time.localtime()",
    "time.monotonic": "x = time.monotonic()",
    "st_mtime": "x = path.stat().st_mtime",
    "getmtime": "x = os.path.getmtime(path)",
}


@pytest.mark.parametrize("rel", ["engine/press/properties.py",
                                 "scripts/build_press_properties.py"])
def test_the_property_renderer_reads_no_clock(rel):
    """DETERMINISM IS THE CONTRACT.  One wall-clock read — a "generated at"
    stamp, an RSS lastBuildDate taken from the current instant — makes
    `build_press_properties --check` red on every single run, and a check that
    is always red is a check that gets deleted.  Every timestamp on every page
    comes from the ledger or from frontmatter.
    """
    source = (_REPO / rel).read_text(encoding="utf-8")
    hits = [tok for tok in _CLOCK_READS if tok in source]
    assert not hits, f"{rel} reads the wall clock: {hits}"


@pytest.mark.parametrize("token", sorted(_CLOCK_READS))
def test_the_clock_sentinel_is_not_vacuous(token, tmp_path):
    """A text-scanning guard that cannot see a violation is not a guard — and a
    token that no probe exercises is a token nobody has ever seen fire.

    Each probe must trip the scan through THE WHOLE TOKEN LIST, not just its own
    token: that is what catches a token whose spelling is wrong (`date.today()`
    never matched `d.today()`; `time.time(` never matched `from time import
    time`).
    """
    assert token in _CLOCK_PROBES, f"{token!r} has no probe — add one"
    probe = tmp_path / "probe.py"
    probe.write_text(_CLOCK_PROBES[token] + "\n", encoding="utf-8")
    source = probe.read_text(encoding="utf-8")
    assert [t for t in _CLOCK_READS if t in source], \
        f"probe for {token!r} tripped nothing in the sentinel"


# ─────────────────────────────────────────────────────────────────────────────
# (g) the css stamp
# ─────────────────────────────────────────────────────────────────────────────


def test_property_css_is_the_template_css_byte_for_byte_and_stamped(tmp_path, capsys):
    import hashlib

    root, tree, cfg = _populated(tmp_path)
    PR.render_property(root, cfg, "mastermind_news", dest=tree)
    capsys.readouterr()

    src = (root / "templates" / "press" / "press_news.css").read_bytes()
    assert (tree / "assets" / "press_news.css").read_bytes() == src
    stamp = hashlib.sha1(src).hexdigest()[:10]

    seen = 0
    for page in sorted(tree.rglob("*.html")):
        for href in re.findall(r'href="(/assets/[^"]+)"', page.read_text(encoding="utf-8")):
            assert href == f"/assets/press_news.css?v={stamp}", href
            seen += 1
    assert seen >= 4, "every page must reference the stamped stylesheet"


def test_a_changed_stylesheet_changes_the_stamp(tmp_path, capsys):
    """The stamp is a content address — if it does not move with the bytes it is
    decoration, and the immutable cache header turns it into a permanent stale
    stylesheet."""
    root, tree, cfg = _populated(tmp_path)
    PR.render_property(root, cfg, "mastermind_news", dest=tree)
    before = re.search(r'\?v=([0-9a-f]+)',
                       (tree / "index.html").read_text(encoding="utf-8")).group(1)

    css = root / "templates" / "press" / "press_news.css"
    css.write_text(css.read_text(encoding="utf-8") + "\n.x{}\n", encoding="utf-8")
    PR.render_property(root, cfg, "mastermind_news", dest=tree)
    capsys.readouterr()
    after = re.search(r'\?v=([0-9a-f]+)',
                      (tree / "index.html").read_text(encoding="utf-8")).group(1)
    assert before != after


def test_fonts_are_copied_through_when_present(tmp_path, capsys):
    root = _property_root(tmp_path, [])
    fonts = root / "templates" / "press" / "fonts"
    fonts.mkdir(parents=True)
    (fonts / "display.woff2").write_bytes(b"wOF2fixture")
    tree = tmp_path / "out"
    PR.render_property(root, P.load_config(root), "mastermind_news", dest=tree)
    capsys.readouterr()
    assert (tree / "assets" / "fonts" / "display.woff2").read_bytes() == b"wOF2fixture"


# ─────────────────────────────────────────────────────────────────────────────
# (h) update.sh
# ─────────────────────────────────────────────────────────────────────────────


def test_update_sh_publishes_both_property_trees_atomically():
    """Same pattern as site.served, and the flags are the point: --min-size=1
    refuses to publish a 0-byte file over a good one (the 2026-07-03 white-page
    incident), and the [ -d ] guard stops `set -e` aborting the whole update run
    on a box that has not built the trees yet."""
    script = _UPDATE_SH.read_text(encoding="utf-8")
    for src, dst in (("properties/news", "press_news.served"),
                     ("properties/research", "press_research.served")):
        assert f'if [ -d "$APP_DIR/{src}" ]; then' in script, f"missing [ -d ] guard for {src}"
        assert f'mkdir -p "$APP_DIR/{dst}"' in script
        assert (f'rsync -a --delete --min-size=1 "$APP_DIR/{src}/" '
                f'"$APP_DIR/{dst}/"') in script, f"missing/altered rsync for {src}"

    # Inside the REPO_UPDATED block, next to the site.served publish it mirrors.
    site_rsync = script.index('rsync -a --delete --min-size=1 "$APP_DIR/site/"')
    news_rsync = script.index('"$APP_DIR/properties/news/"')
    reconcile = script.index("# Do not exit just because Git is current.")
    assert site_rsync < news_rsync < reconcile


# ─────────────────────────────────────────────────────────────────────────────
# (i) the workflow
# ─────────────────────────────────────────────────────────────────────────────


def _emit_steps() -> list[dict]:
    import yaml

    return yaml.safe_load(_WORKFLOW.read_text(encoding="utf-8"))["jobs"]["emit"]["steps"]


def test_the_workflow_rebuilds_the_properties_after_emitting():
    """Front pages, feeds and sitemaps are functions of the WHOLE ledger, so
    they are rebuilt after the ledger moved — not before it."""
    steps = _emit_steps()
    runs = [str(s.get("run") or "") for s in steps]
    emit_at = next(i for i, r in enumerate(runs) if "run_press --emit" in r)
    build_at = next(i for i, r in enumerate(runs) if "scripts.build_press_properties" in r)
    check_at = next(i for i, r in enumerate(runs) if "build_free_content --check" in r)
    assert emit_at < build_at < check_at
    assert "set -euo pipefail" in runs[build_at], \
        "a crashed rebuild must not sail past into the commit step"


# Tokens that end the ARGUMENT list of a `git add` line in these run: blocks —
# every one of them is written `git add <paths> 2>/dev/null || true`.
_ARGV_END = ("||", "&&", ";", "|")

# Paths this lane stages plainly. A flag on any of these would change what a
# publish commits, so they are pinned bare.
_PROPERTY_PATHS = frozenset({
    "content/seo/blog", "site/blog", "data/press/published.jsonl",
    "content/press", "properties",
})

# ...and the content-hashed assets the normalized pages LINK (#4549,
# aa143e42c80). externalize_css rewrites each article to
# <link> site/assets/css/<hash>.css, so staging a page without its asset ships a
# 404 stylesheet.
_ASSET_PATHS = frozenset({"site/assets/css", "site/assets/js"})


def _git_add_targets(step: str) -> dict[str, tuple[str, ...]]:
    """Every ``git add`` in a run: block, as ``{path: flags}``.

    Parsed rather than regex-sliced because the naive ``git add ([^\\s]+)`` reads
    the FIRST token as the path, so a flag becomes a phantom staged path: when
    #4549 added ``git add --ignore-removal site/assets/css`` this test began
    asserting that the lane stages a directory called ``--ignore-removal``
    (ci-pack-2 red, 2026-08-06). The flags are not noise to skip — ``--ignore-
    removal`` is the difference between staging an asset and staging its
    deletion — so they are returned alongside the path and asserted below.
    """
    targets: dict[str, tuple[str, ...]] = {}
    for tail in re.findall(r"^\s*git add\s+(.+)$", step, re.MULTILINE):
        flags: list[str] = []
        paths: list[str] = []
        for token in tail.split():
            if token in _ARGV_END or re.match(r"^\d*[<>]", token):
                break
            (flags if token.startswith("-") else paths).append(token)
        for path in paths:
            targets[path] = tuple(flags)
    return targets


def test_the_commit_step_stages_the_property_paths():
    """The staged set is EXACT — the lane cannot silently widen what it commits.

    #4549 (aa143e42c80) grew the owned set to seven: `externalize_css` now runs
    before the staging and lifts each article's inline CSS into a content-hashed
    site/assets/css/<hash>.css the page then <link>s, so the asset has to ride
    along in the same commit or the published article points at a stylesheet
    that was never committed.  Those two adds carry `--ignore-removal`, which is
    what broke this guard: the old pattern captured the first token after
    `git add`, read the FLAG as a path, and the comparison failed on
    '--ignore-removal' rather than on any real widening.

    Parsing now goes through tests/workflow_staging.py, shared with the sibling
    guards in test_press_workflow.py and test_marketing_hot_tape_radar.py, so
    the next flagged add cannot fix one copy and leave the others blind — the
    partial sweep IS the bug this file has been on both ends of.
    """
    step = next(str(s.get("run") or "") for s in _emit_steps()
                if "git add" in str(s.get("run") or ""))
    staged = _git_add_targets(step)
    assert set(staged) == _PROPERTY_PATHS | _ASSET_PATHS
    for path in sorted(_PROPERTY_PATHS):
        assert staged[path] == (), \
            f"{path} gained an unreviewed `git add` flag: {staged[path]}"
    for path in sorted(_ASSET_PATHS):
        assert "--ignore-removal" in staged[path], (
            f"{path} must be staged --ignore-removal: the orphan prune reasons only "
            "from pages it can see and this lane has no post-rebase normalize, so a "
            "staged DELETION here 404s a sibling page's stylesheet")
    # ...and the shared parser must agree on the SET.  _git_add_targets is the
    # flag-aware local reader (the flags are load-bearing above, and
    # staged_paths deliberately drops them); staged_paths is the one shared with
    # test_press_workflow.py and test_marketing_hot_tape_radar.py.  Pinning them
    # against each other here is what stops the three guards drifting apart
    # again — the partial sweep (#4549 → #4707 → #4714) IS the recurring bug.
    assert staged_paths(step) == set(staged), (
        "tests/workflow_staging.py::staged_paths and the flag-aware local reader "
        f"disagree on this lane's staged set: {staged_paths(step)} vs {set(staged)}")

    # The nightly still owns site/sitemap.xml; the properties carry their own.
    assert "git add site/sitemap.xml" not in step
    assert "press_sitemap_guard" in step


def test_the_property_suite_can_be_triggered_by_the_changes_it_guards():
    """A guard the guarded change cannot trigger is not a guard."""
    import yaml

    ci = yaml.safe_load((_REPO / ".github" / "workflows" / "ci.yml").read_text(
        encoding="utf-8"))
    triggers = ci.get("on") if "on" in ci else ci[True]
    paths = triggers["pull_request"]["paths"]
    for needed in ("engine/press/**", "scripts/build_press_properties.py",
                   "templates/press/**", "properties/**", "content/press/**",
                   "app/deploy/Caddyfile", "app/deploy/update.sh"):
        assert needed in paths, f"{needed} cannot trigger ci.yml"


# ─────────────────────────────────────────────────────────────────────────────
# (j) emit routing — the pre-cutover invariant, and what cutover changes
# ─────────────────────────────────────────────────────────────────────────────


def _stage_passing(root: Path, slug: str = "routed-note") -> None:
    slot = F.slot()
    draft = dict(F.draft_from_slot(slot), slug=slug)
    (root / "data" / "press" / "staging").mkdir(parents=True, exist_ok=True)
    (root / "data" / "press" / "staging" / "x.json").write_text(json.dumps({
        "id": "press-brief-x", "desk": "brief", "publication": "mastermind_news",
        "as_of": "2026-07-26", "status": "passed", "sources": ["chronicle:x"],
        "seed_refs": [], "slug": slug, "draft": draft, "slot": slot,
        "validator_report": {"ok": True},
    }), encoding="utf-8")


def test_before_cutover_the_emit_path_is_exactly_what_it_was(tmp_path, monkeypatch):
    """THE DARK INVARIANT.  W1.5 ships every property mechanism and moves no
    published byte: nothing under properties/ or content/press/, the .md in
    content/seo/blog, and the flagship /blog/ URL on the ledger row."""
    root = _property_root(tmp_path, [], cutover=False)
    _stage_passing(root)
    monkeypatch.setattr(R, "_render_blog_subtree", lambda r: ([], []))

    out = R.run_emit(root, P.load_config(root))
    assert out["emitted"] == 1
    assert (root / "content" / "seo" / "blog" / "routed-note.md").exists()
    assert not (root / "properties").exists(), "cutover:false wrote a property tree"
    assert not (root / "content" / "press").exists(), "cutover:false wrote a routed .md"

    row = json.loads((root / "data" / "press" / "published.jsonl").read_text(
        encoding="utf-8").splitlines()[-1])
    assert row["url"] == "https://www.mastermind-x.com/blog/routed-note.html"
    assert row["urls"] == ["https://www.mastermind-x.com/blog/routed-note.html"]
    assert row["title"] == "A first-party read of the session"
    assert row["publication"] == "mastermind_news"


def test_before_cutover_the_route_targets_the_estate(tmp_path):
    """The routing decision itself, isolated from the emit's side effects."""
    root = _property_root(tmp_path, [], cutover=False)
    cfg = P.load_config(root)
    paths = R._paths(cfg, root)
    route = R._emit_route(cfg, root, paths, {"desk": "brief"}, "a-slug")
    assert route["routed"] is False
    assert route["md_dir"] == root / "content" / "seo" / "blog"
    assert route["url"] == "https://www.mastermind-x.com/blog/a-slug.html"


def test_after_cutover_a_piece_lands_on_its_own_property(tmp_path, capsys):
    root = _property_root(tmp_path, [], cutover=True)
    _stage_passing(root)

    out = R.run_emit(root, P.load_config(root))
    capsys.readouterr()
    assert out["emitted"] == 1

    assert (root / "content" / "press" / "news" / "routed-note.md").exists()
    assert not (root / "content" / "seo" / "blog" / "routed-note.md").exists()
    tree = root / "properties" / "news"
    assert (tree / "articles" / "routed-note.html").exists()
    assert (tree / "index.html").exists() and (tree / "feed.xml").exists()

    row = json.loads((root / "data" / "press" / "published.jsonl").read_text(
        encoding="utf-8").splitlines()[-1])
    assert row["url"] == "https://mastermindx.ai/articles/routed-note.html"
    assert row["urls"] == [row["url"]]

    # The piece it just published is ON the property it just rendered.
    assert row["url"] in (tree / "index.html").read_text(encoding="utf-8")


def test_the_ledger_records_the_desks_current_publication_not_the_staged_one(
        tmp_path, monkeypatch):
    """DECLARED DELTA VS W1.  The row's `publication` now comes from the DESK's
    config at emit time, not from the staged record written days earlier.

    W1 read the staged copy, so re-pointing a desk between staging and emit
    published the piece under the NEW routing while recording the OLD name — a
    ledger that disagrees with the URL beside it. The staged value stays as the
    fallback for a desk that has since left config entirely.
    """
    root = _property_root(tmp_path, [], cutover=False)
    _stage_passing(root)
    # Staged record says mastermind_news (see _stage_passing); the desk now
    # points at mastermind_research.
    import yaml
    cfg_path = root / "config" / "press.yml"
    raw = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
    raw["desks"]["brief"]["publication"] = "mastermind_research"
    cfg_path.write_text(yaml.safe_dump(raw, sort_keys=False), encoding="utf-8")
    monkeypatch.setattr(R, "_render_blog_subtree", lambda r: ([], []))

    R.run_emit(root, P.load_config(root))
    row = json.loads((root / "data" / "press" / "published.jsonl").read_text(
        encoding="utf-8").splitlines()[-1])
    assert row["publication"] == "mastermind_research", \
        "the ledger must record where the piece actually routed"


def test_a_desk_missing_from_config_falls_back_to_the_staged_publication(tmp_path):
    root = _property_root(tmp_path, [], cutover=False)
    cfg = P.load_config(root)
    route = R._emit_route(cfg, root, R._paths(cfg, root),
                          {"desk": "deleted_desk", "publication": "mastermind_news"},
                          "a-slug")
    assert route["publication"] == "mastermind_news"
    assert route["routed"] is False


def test_after_cutover_the_estate_render_is_skipped(tmp_path, capsys, monkeypatch):
    """A routed piece never enters the free-content estate, so the estate render
    must not run for it at all — running it would rewrite /blog/ pages this lane
    no longer owns."""
    root = _property_root(tmp_path, [], cutover=True)
    _stage_passing(root)
    monkeypatch.setattr(R, "_render_blog_subtree",
                        lambda r: pytest.fail("the estate render ran for a routed emit"))
    assert R.run_emit(root, P.load_config(root))["emitted"] == 1
    capsys.readouterr()


def test_a_mid_emit_failure_rolls_back_the_property_tree_and_the_content_dir(
        tmp_path, capsys, monkeypatch):
    """ATOMICITY, extended to the property trees.  A .md with no rendered page —
    or a rendered page with no ledger row — is the render-clobber class, and the
    property trees are now part of that surface."""
    root = _property_root(tmp_path, [], cutover=True)
    _stage_passing(root)
    tree = root / "properties" / "news"
    tree.mkdir(parents=True)
    (tree / "index.html").write_text("<html>original</html>", encoding="utf-8")

    real_render = PR.render_property

    def _boom(r, cfg, key, **kw):
        real_render(r, cfg, key, **kw)      # get partway: rewrite + add files
        raise RuntimeError("property render exploded")

    monkeypatch.setattr(R.properties, "render_property", _boom)
    with pytest.raises(RuntimeError, match="property render exploded"):
        R.run_emit(root, P.load_config(root))
    capsys.readouterr()

    assert (tree / "index.html").read_text(encoding="utf-8") == "<html>original</html>"
    assert not (tree / "feed.xml").exists(), "a file the failed render added survived"
    assert not (tree / "articles" / "routed-note.html").exists()
    assert list((root / "content" / "press" / "news").glob("*.md")) == [], \
        "a .md with no rendered page is the defect this rollback exists for"
    assert (root / "data" / "press" / "published.jsonl").read_text(encoding="utf-8") == ""


def test_a_failed_ledger_append_after_cutover_rolls_the_property_back(
        tmp_path, capsys, monkeypatch):
    root = _property_root(tmp_path, [], cutover=True)
    _stage_passing(root)
    monkeypatch.setattr(R, "append_ledger",
                        lambda *a, **kw: (_ for _ in ()).throw(OSError("disk full")))
    with pytest.raises(OSError, match="disk full"):
        R.run_emit(root, P.load_config(root))
    capsys.readouterr()
    assert list((root / "content" / "press" / "news").glob("*.md")) == []
    tree = root / "properties" / "news"
    assert [p for p in tree.rglob("*") if p.is_file()] == []


# ─────────────────────────────────────────────────────────────────────────────
# (l) loader validation
# ─────────────────────────────────────────────────────────────────────────────


def test_the_shipped_config_passes_its_own_validator():
    cfg = P.load_config(_REPO)
    assert cfg, "config/press.yml must load"
    P.validate_publications(cfg)
    pubs = cfg["publications"]
    assert pubs["flagship"].get("property_tree") is None
    for key in ("mastermind_news", "mastermind_research"):
        assert pubs[key]["base_url"].startswith("https://")
        assert pubs[key]["property_tree"].startswith("properties/")
        assert pubs[key]["content_dir"].startswith("content/")


def _cfg(**pub_overrides) -> dict:
    base = {
        "cutover": False,
        "desks": {"brief": {"publication": "mastermind_news"}},
        "publications": {
            "mastermind_news": {"label": "News", "domain": "mastermindx.ai",
                                "base_url": "https://mastermindx.ai",
                                "property_tree": "properties/news",
                                "content_dir": "content/press/news"},
            "flagship": {"label": "Flagship", "domain": "mastermind-x.com",
                         "base_url": "https://www.mastermind-x.com"},
        },
    }
    for key, patch in pub_overrides.items():
        if key == "cutover":
            base["cutover"] = patch
        elif key == "desks":
            base["desks"] = patch
        else:
            base["publications"][key] = {**base["publications"].get(key, {}), **patch}
    return base


def test_a_good_config_validates():
    P.validate_publications(_cfg())


@pytest.mark.parametrize("patch,needle", [
    ({"desks": {"brief": {"publication": "nope"}}}, "unknown publication"),
    ({"desks": {"brief": {}}}, "carries no `publication`"),
    ({"mastermind_news": {"base_url": "http://mastermindx.ai"}}, "must be https"),
    ({"mastermind_news": {"base_url": "https://example.com"}}, "is neither"),
    ({"mastermind_news": {"base_url": "https://mastermindx.ai/"}}, "must not end in '/'"),
    ({"mastermind_news": {"property_tree": "/etc/passwd"}}, "must be a RELATIVE path"),
    ({"mastermind_news": {"property_tree": "../../etc"}}, "must not escape"),
    ({"mastermind_news": {"property_tree": "site/news"}}, "must live under properties/"),
    ({"mastermind_news": {"content_dir": "site/press/news"}}, "must live under content/"),
    ({"flagship": {"property_tree": "properties/flagship"}}, "must NOT carry `property_tree`"),
    ({"cutover": True, "mastermind_news": {"content_dir": None}}, "must carry `content_dir`"),
    ({"cutover": True, "mastermind_news": {"base_url": None}}, "must carry `base_url`"),
])
def test_each_violation_raises(patch, needle):
    with pytest.raises(ValueError, match=re.escape(needle)):
        P.validate_publications(_cfg(**patch))


def test_a_missing_config_still_returns_empty_rather_than_raising(tmp_path):
    """Fail LOUD on a broken contract, fail SOFT on an absent file: the CLI
    reports a missing config as its own error, and that path must survive."""
    assert P.load_config(tmp_path) == {}


def test_the_md_parser_agrees_with_the_estate_builder(tmp_path):
    """properties._parse_md mirrors build_free_content._parse_md rather than
    importing it (that module drags the whole estate builder in for fifteen
    lines of string splitting).  A mirror that is never compared is a fork."""
    from scripts.build_free_content import _parse_md as estate_parse

    path = tmp_path / "sample.md"
    _write_md(path, "sample", published="2026-07-20", updated="2026-07-22")
    assert PR._parse_md(path) == estate_parse(path)


# ─────────────────────────────────────────────────────────────────────────────
# (k) THE REAL TEMPLATES — one test, RED BY DESIGN until the design lane lands
# ─────────────────────────────────────────────────────────────────────────────


@pytest.mark.parametrize("pub_key,prefix", [("mastermind_news", "news"),
                                            ("mastermind_research", "research")])
def test_real_templates_render_a_compliant_page(pub_key, prefix, tmp_path, capsys):
    """THE LIVE INTEGRATION GATE — the one test that renders the real templates.

    Deliberately NOT skip-guarded: a skip-guarded integration test is an unrun
    test that reads green, which is how a renderer and a template set ship in
    the same PR having never met.  It asserts the four things the renderer
    cannot check about itself:

      * the standing disclosure reaches the page, verbatim, EXACTLY ONCE (twice
        means the body still carries its estate chrome — see M1);
      * the byline appears exactly once for the same reason;
      * the page declares its canonical URL;
      * the JSON-LD block parses (an autoescaped one parses as nothing at all).
    """
    root, tree, cfg = _populated(tmp_path)
    shutil.rmtree(root / "templates" / "press")
    shutil.copytree(_REPO / "templates" / "press", root / "templates" / "press")

    if pub_key == "mastermind_research":
        # Same fixture archive, re-pointed at the research property. The native
        # piece's .md moves to the research content_dir too — a publication only
        # searches its OWN content_dir plus the flagship estate.
        led = root / "data" / "press" / "published.jsonl"
        rows = [json.loads(l) for l in led.read_text(encoding="utf-8").splitlines()]
        url = "https://blog.mastermind-x.com/articles/native-note.html"
        for r in rows:
            r["publication"] = "mastermind_research"
            if r["slug"] == "native-note":
                r["url"] = url
        led.write_text("".join(json.dumps(r) + "\n" for r in rows), encoding="utf-8")
        dst = root / "content" / "press" / "research" / "native-note.md"
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(root / "content" / "press" / "news" / "native-note.md", dst)

    PR.render_property(root, cfg, pub_key, dest=tree)
    capsys.readouterr()

    article_rel = "articles/native-note.html"
    footer = cfg["validators"]["footer_required_text"]
    for name in ("index.html", "about.html", "404.html", article_rel):
        page = (tree / name).read_text(encoding="utf-8")
        assert page.count(footer) == 1, (
            f"{prefix} {name}: the standing disclosure appears {page.count(footer)} "
            "times — it must appear exactly once (twice means the article body "
            "still carries the estate's in-body footer)")

    article = (tree / article_rel).read_text(encoding="utf-8")
    byline = cfg["desks"]["brief"]["byline"]      # every fixture row is brief's
    # Count VISIBLE occurrences only: the JSON-LD block legitimately names the
    # desk as `author.name`, and that is machine-readable metadata, not chrome.
    visible = re.sub(r'<script type="application/ld\+json">.*?</script>', "",
                     article, flags=re.DOTALL)
    visible = visible[visible.index("<body"):]
    assert visible.count(byline) == 1, (
        f"{prefix}: the byline appears {visible.count(byline)} times in the visible "
        "page — the template draws it, so the body must not carry it too")

    expected_url = PR.iter_publication_articles(root, cfg, pub_key)[0]["url"]
    assert f'rel="canonical" href="{expected_url}"' in article.replace("'", '"'), \
        "the article page must declare its canonical URL"

    raw = re.search(r'<script type="application/ld\+json">(.*?)</script>',
                    article, re.DOTALL).group(1)
    data = json.loads(raw)     # an escaped JSON-LD block dies here
    assert data["@type"] == ("NewsArticle" if pub_key == "mastermind_news"
                             else "Article")


def test_the_front_page_empty_state_says_what_it_means(tmp_path, capsys):
    """Approved copy, pinned.  An empty front page is a real state on day one,
    and it must not claim a cadence or a piece 'being written'."""
    expected = {
        "mastermind_news": ["Nothing on the wire yet.",
                            "When the desk files, it lands here."],
        "mastermind_research": ["No notes published yet.",
                                "Close readings of institutional reports will "
                                "publish here."],
    }
    root = _property_root(tmp_path, [])
    shutil.rmtree(root / "templates" / "press")
    shutil.copytree(_REPO / "templates" / "press", root / "templates" / "press")
    cfg = P.load_config(root)

    for pub_key, lines in expected.items():
        tree = tmp_path / f"out-{pub_key}"
        PR.render_property(root, cfg, pub_key, dest=tree)
        capsys.readouterr()
        front = (tree / "index.html").read_text(encoding="utf-8")
        for line in lines:
            assert line in front, f"{pub_key} front page is missing {line!r}"
        # Scoped to <main>: the masthead legitimately carries the publication's
        # standing tagline, which is not an empty-state claim.
        main = re.search(r"<main\b.*?</main>", front, re.DOTALL).group(0)
        for banned in ("being written", "The Brief writes", "The first note",
                       "The index is empty"):
            assert banned not in main, (
                f"{pub_key} empty state claims {banned!r} — an empty page must not "
                "promise a cadence, name the desk, or describe work in progress")
