"""tests/test_signal_gate_coherence.py — the board/gate pair must be one run's work.

Guards scripts/check_signal_gate_coherence.py and the two readers that demote a stale gate
(scripts/build_discovery._signal_verdicts, scripts/run_watchlist_sentinel._load_per_ticker_states).

Every fixture here is a LITERAL dict, never a call into build_stock_library. That is the
point: the artifacts are what disagreed on 2026-08-12, so a fixture generated by the writer
could never express the failure — it would agree with itself by construction.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts.check_signal_gate_coherence import (  # noqa: E402
    _check, incoherent_tickers, main as cli_main)


# ---------------------------------------------------------------------------
# fixtures — literal artifact shapes
# ---------------------------------------------------------------------------

def _gate_entry(**over) -> dict:
    """One signal_gate.json verdict: the 11 keys the live artifact carries."""
    e = {
        "anchor_era": "2026-07-30", "bars_to_cross": 0, "eligible": True,
        "htf_s1": True, "htf_s2": False, "provisional": False,
        "sq_anchor_era": "2026-07-28", "ticks": 3, "tier_cascade": "T2",
        "tier_sub": "confirmed", "young_history": False,
    }
    e.update(over)
    return e


def _blob(**over) -> dict:
    """A board row's embedded `signal` blob: a strict SUPERSET of the gate entry."""
    b = _gate_entry()
    b.update({
        "asof": "2026-08-12", "state": "FRESH BUY", "tier": "T2", "sub": "confirmed",
        "weight": 1.0, "reason": "confluence", "reasons": [], "above200": True,
        "early_now": False, "fresh_bars": 2, "history_bars": 900, "last": 101.5,
        "weekly_bull": True,
    })
    b.update(over)
    return b


def _standouts(*, buy=(), watch=(), leaders=(), laggards=(), **top) -> dict:
    d = {"as_of": "2026-08-12", "rank_by": "us_prophet_v1",
         "buy": list(buy), "watch": list(watch),
         "leaders": list(leaders), "laggards": list(laggards)}
    d.update(top)
    return d


def _gate(entries: dict, **top) -> dict:
    d = {"as_of": "2026-08-12", "verdicts": entries}
    d.update(top)
    return d


def _row(ticker: str, sig: dict | None) -> dict:
    return {"ticker": ticker, "alpha": 0.4, "state": "FRESH BUY", "signal": sig}


def _write_pair(tmp_path: Path, standouts: dict, gate: dict) -> tuple[str, str]:
    fd = tmp_path / "factordata"
    fd.mkdir(parents=True, exist_ok=True)
    p_s, p_g = fd / "us_standouts.json", fd / "signal_gate.json"
    p_s.write_text(json.dumps(standouts))
    p_g.write_text(json.dumps(gate))
    return str(p_s), str(p_g)


# The 2026-08-12 incident: 8 of 69 buy rows disagreed with the gate on `ticks`.
_SKEWED_5490 = ("CRCL", "GPCR", "GRAB", "LNG", "NTES", "RBRK", "SGML", "TEM")


def _incident_pair() -> tuple[dict, dict]:
    """The #5490 shape: a board re-emitted with fresh blobs against an unadvanced gate."""
    rows = [_row(t, _blob(ticks=0 if t == "NTES" else 1)) for t in _SKEWED_5490]
    rows.append(_row("AAPL", _blob()))          # coherent control
    gate = {t: _gate_entry(ticks=3) for t in _SKEWED_5490}
    gate["AAPL"] = _gate_entry()
    return _standouts(buy=rows), _gate(gate)


# ---------------------------------------------------------------------------
# 1. a coherent pair is clean
# ---------------------------------------------------------------------------

class TestCoherentPair:
    def test_predicate_empty_on_coherent_pair(self):
        s = _standouts(buy=[_row("AAPL", _blob())], watch=[_row("MSFT", _blob(ticks=5))],
                       leaders=[_row("NVDA", _blob(tier_cascade="T1"))],
                       laggards=[_row("INTC", _blob(eligible=False))])
        g = _gate({"AAPL": _gate_entry(), "MSFT": _gate_entry(ticks=5),
                   "NVDA": _gate_entry(tier_cascade="T1"),
                   "INTC": _gate_entry(eligible=False)})
        assert incoherent_tickers(s, g) == {}

    def test_check_returns_no_violations(self, tmp_path):
        s = _standouts(buy=[_row("AAPL", _blob())])
        g = _gate({"AAPL": _gate_entry()})
        assert _check(*_write_pair(tmp_path, s, g)) == []

    def test_blob_superset_keys_are_not_a_violation(self):
        """The gate entry's own key set is the contract — extra blob keys must not red."""
        s = _standouts(buy=[_row("AAPL", _blob(some_new_display_field="x"))])
        assert incoherent_tickers(s, _gate({"AAPL": _gate_entry()})) == {}


# ---------------------------------------------------------------------------
# 2. the #5490 shape
# ---------------------------------------------------------------------------

class TestIncidentShape:
    def test_exactly_the_skewed_tickers_are_flagged(self):
        s, g = _incident_pair()
        assert incoherent_tickers(s, g) == {t: ["ticks"] for t in _SKEWED_5490}

    def test_check_strings_name_every_skewed_ticker_and_both_values(self, tmp_path):
        s, g = _incident_pair()
        viol = _check(*_write_pair(tmp_path, s, g))
        assert len(viol) == len(_SKEWED_5490)
        text = "\n".join(viol)
        for t in _SKEWED_5490:
            assert t in text
        assert "AAPL" not in text
        assert "NTES: 1 gate key(s) disagree — ticks: board=0 gate=3" in text

    def test_cli_exits_1_on_the_incident_pair(self, tmp_path, capsys):
        s, g = _incident_pair()
        p_s, p_g = _write_pair(tmp_path, s, g)
        assert cli_main([p_s, p_g]) == 1
        assert "NTES" in capsys.readouterr().err


# ---------------------------------------------------------------------------
# 3. a board ticker the gate never saw
# ---------------------------------------------------------------------------

class TestAbsentFromGate:
    def test_absent_ticker_is_flagged(self):
        s = _standouts(buy=[_row("AAPL", _blob()), _row("GHOST", _blob())])
        g = _gate({"AAPL": _gate_entry()})
        assert incoherent_tickers(s, g) == {"GHOST": ["absent_from_gate"]}

    def test_check_says_the_gate_never_saw_it(self, tmp_path):
        s = _standouts(buy=[_row("GHOST", _blob())])
        viol = _check(*_write_pair(tmp_path, s, _gate({})))
        assert len(viol) == 1
        assert "GHOST" in viol[0] and "ABSENT" in viol[0]


# ---------------------------------------------------------------------------
# 4. rows with no reading of their own are skipped
# ---------------------------------------------------------------------------

class TestEmptyBlobSkipped:
    @pytest.mark.parametrize("empty", [None, {}])
    def test_row_without_a_signal_blob_is_not_flagged(self, empty):
        """No embedded copy means nothing to disagree WITH — not even absence from the gate."""
        s = _standouts(buy=[_row("QUIET", empty)])
        assert incoherent_tickers(s, _gate({})) == {}


# ---------------------------------------------------------------------------
# 5. lineage: the emit stamp names the stale side, and only skew is a violation
# ---------------------------------------------------------------------------

def _stamp(pair_id: str, at_utc: str) -> dict:
    return {"pair_id": pair_id, "at_utc": at_utc, "writer": "build_stock_library"}


class TestLineageStamp:
    def test_differing_pair_id_with_identical_content_is_benign(self, tmp_path):
        """A re-emit that changed nothing is not a violation — only disagreement is."""
        s = _standouts(buy=[_row("AAPL", _blob())],
                       emit=_stamp("bbbb", "2026-08-12T22:40:00+00:00"))
        g = _gate({"AAPL": _gate_entry()}, emit=_stamp("aaaa", "2026-08-12T02:10:00+00:00"))
        assert _check(*_write_pair(tmp_path, s, g)) == []

    def test_differing_pair_id_with_skew_names_the_older_side_as_stale(self, tmp_path):
        s, g = _incident_pair()
        s["emit"] = _stamp("bbbb", "2026-08-12T22:40:00+00:00")
        g["emit"] = _stamp("aaaa", "2026-08-12T02:10:00+00:00")   # the gate lagged
        viol = _check(*_write_pair(tmp_path, s, g))
        lineage = [v for v in viol if v.startswith("lineage:")]
        assert len(lineage) == 1
        assert "signal_gate.json is the STALE side" in lineage[0]
        assert "us_standouts.json" in lineage[0]

    def test_same_pair_id_emits_no_lineage_line(self, tmp_path):
        """One run wrote both files, so nothing lags — the skew is reported without direction."""
        s, g = _incident_pair()
        s["emit"] = g["emit"] = _stamp("cccc", "2026-08-12T22:40:00+00:00")
        assert [v for v in _check(*_write_pair(tmp_path, s, g)) if v.startswith("lineage:")] == []


# ---------------------------------------------------------------------------
# 6. CLI on absent / unparseable artifacts
# ---------------------------------------------------------------------------

class TestCLIMissingArtifacts:
    def test_missing_files_print_na_and_exit_0(self, tmp_path, capsys):
        """Sparse agent checkouts and fresh clones carry no site/ tree — that is not a red."""
        p_s, p_g = str(tmp_path / "nope_standouts.json"), str(tmp_path / "nope_gate.json")
        assert cli_main([p_s, p_g]) == 0
        out = capsys.readouterr().out
        assert out.startswith("signal-gate coherence: n/a (")
        assert "nope_standouts.json" in out and "nope_gate.json" in out

    def test_one_missing_file_still_exits_0(self, tmp_path, capsys):
        p_s, p_g = _write_pair(tmp_path, _standouts(buy=[_row("AAPL", _blob())]),
                               _gate({"AAPL": _gate_entry()}))
        Path(p_g).unlink()
        assert cli_main([p_s, p_g]) == 0
        assert "n/a" in capsys.readouterr().out

    def test_present_but_unparseable_is_a_violation(self, tmp_path, capsys):
        p_s, p_g = _write_pair(tmp_path, _standouts(buy=[_row("AAPL", _blob())]),
                               _gate({"AAPL": _gate_entry()}))
        Path(p_g).write_text("{not json")
        assert cli_main([p_s, p_g]) == 1
        assert "JSON parse error" in capsys.readouterr().err

    def test_cli_exits_0_on_a_coherent_pair(self, tmp_path, capsys):
        p_s, p_g = _write_pair(tmp_path, _standouts(buy=[_row("AAPL", _blob())]),
                               _gate({"AAPL": _gate_entry()}))
        assert cli_main([p_s, p_g]) == 0
        assert "OK" in capsys.readouterr().out


# ---------------------------------------------------------------------------
# 7. build_discovery demotes a stale gate to the board's copy
# ---------------------------------------------------------------------------

class TestDiscoveryDemotion:
    def test_flagged_verdict_becomes_the_board_blob(self, tmp_path, capsys):
        from scripts import build_discovery as bd

        blob = _blob(ticks=0, tier_cascade="T3")
        s = _standouts(buy=[_row("NTES", blob), _row("AAPL", _blob())])
        g = _gate({"NTES": _gate_entry(ticks=3), "AAPL": _gate_entry()})
        _write_pair(tmp_path, s, g)

        v = bd._signal_verdicts(tmp_path, None)

        assert v["NTES"] == blob, "the board's fresher copy must replace the stale verdict"
        assert v["AAPL"] == _gate_entry(), "a coherent name keeps its gate verdict untouched"
        # house law: the annotation must START the line (never through a logger)
        line = next(ln for ln in capsys.readouterr().out.splitlines() if "coherence" in ln)
        assert line.startswith("::")
        assert line.startswith("::warning title=signal-gate-coherence")
        assert "NTES" in line

    def test_absent_from_gate_ticker_is_added(self, tmp_path):
        from scripts import build_discovery as bd

        blob = _blob(tier_cascade="T1")
        _write_pair(tmp_path, _standouts(buy=[_row("AAPL", _blob()), _row("GHOST", blob)]),
                    _gate({"AAPL": _gate_entry()}))
        v = bd._signal_verdicts(tmp_path, None)
        assert v["GHOST"] == blob

    def test_coherent_pair_leaves_the_verdicts_untouched_and_silent(self, tmp_path, capsys):
        from scripts import build_discovery as bd

        _write_pair(tmp_path, _standouts(buy=[_row("AAPL", _blob())]),
                    _gate({"AAPL": _gate_entry()}))
        v = bd._signal_verdicts(tmp_path, None)
        assert v == {"AAPL": _gate_entry()}
        assert "signal-gate-coherence" not in capsys.readouterr().out


# ---------------------------------------------------------------------------
# 8. run_watchlist_sentinel reads the row, not the stale gate
# ---------------------------------------------------------------------------

class TestSentinelDemotion:
    def _fixture(self, tmp_path, monkeypatch):
        from scripts import run_watchlist_sentinel as rws

        # NTES: board row disagrees with the gate -> flagged, row values win.
        # AAPL: EMPTY blob -> skipped by the predicate, so the gate keeps its preference
        #       (and the row carries no gate fields at all, which makes the source visible).
        s = _standouts(buy=[_row("NTES", _blob(eligible=False, tier_cascade="T3"))],
                       watch=[_row("AAPL", {})])
        g = _gate({"NTES": _gate_entry(eligible=True, tier_cascade="T1"),
                   "AAPL": _gate_entry(eligible=True, tier_cascade="T2")})
        _write_pair(tmp_path / "site", s, g)
        monkeypatch.setattr(rws, "ROOT", tmp_path)
        monkeypatch.setattr(rws._eb, "store_staleness", lambda: {"stale": True})
        return rws

    def test_flagged_ticker_uses_row_values_unflagged_uses_gate(self, tmp_path, monkeypatch):
        rws = self._fixture(tmp_path, monkeypatch)
        states = rws._load_per_ticker_states("2026-08-12")

        assert states["NTES"]["gate_tier"] == "T3", "flagged name must read the board row"
        assert states["NTES"]["gate_eligible"] is False
        assert states["AAPL"]["gate_tier"] == "T2", "coherent name still prefers the gate"
        assert states["AAPL"]["gate_eligible"] is True

    def test_warning_is_a_line_start_annotation(self, tmp_path, monkeypatch, capsys):
        rws = self._fixture(tmp_path, monkeypatch)
        rws._load_per_ticker_states("2026-08-12")
        line = next(ln for ln in capsys.readouterr().out.splitlines() if "coherence" in ln)
        assert line.startswith("::")
        assert line.startswith("::warning title=signal-gate-coherence")
        assert "NTES" in line

    def test_coherent_pair_is_silent(self, tmp_path, monkeypatch, capsys):
        from scripts import run_watchlist_sentinel as rws

        _write_pair(tmp_path / "site", _standouts(buy=[_row("AAPL", _blob())]),
                    _gate({"AAPL": _gate_entry()}))
        monkeypatch.setattr(rws, "ROOT", tmp_path)
        monkeypatch.setattr(rws._eb, "store_staleness", lambda: {"stale": True})
        states = rws._load_per_ticker_states("2026-08-12")
        assert states["AAPL"]["gate_tier"] == "T2"
        assert "signal-gate-coherence" not in capsys.readouterr().out


# ---------------------------------------------------------------------------
# 9. mutation guard: the predicate is the FULL gate-key set, not ticks
# ---------------------------------------------------------------------------

class TestPredicateCoversEveryGateKey:
    @pytest.mark.parametrize("key,board_value,gate_value", [
        ("tier_cascade", "T3", "T1"),
        ("tier_sub", "provisional", "confirmed"),
        ("eligible", False, True),
        ("anchor_era", "2026-08-01", "2026-07-30"),
        ("bars_to_cross", 4, 0),
        ("htf_s1", False, True),
        ("young_history", True, False),
    ])
    def test_skew_on_a_non_ticks_key_is_still_flagged(self, key, board_value, gate_value):
        """A ticks-only predicate would read GREEN here — the whole gate entry is the contract."""
        s = _standouts(buy=[_row("AAPL", _blob(**{key: board_value}))])
        g = _gate({"AAPL": _gate_entry(**{key: gate_value})})
        assert incoherent_tickers(s, g) == {"AAPL": [key]}

    def test_multi_key_skew_reports_every_key(self):
        s = _standouts(buy=[_row("AAPL", _blob(ticks=0, tier_cascade="T3", eligible=False))])
        g = _gate({"AAPL": _gate_entry(ticks=3, tier_cascade="T1", eligible=True)})
        assert incoherent_tickers(s, g) == {"AAPL": ["eligible", "ticks", "tier_cascade"]}

    def test_every_bucket_is_graded(self):
        """A stale gate skews whatever names it reaches — not just the buy lane."""
        for bucket in ("buy", "watch", "leaders", "laggards"):
            s = _standouts(**{bucket: [_row("AAPL", _blob(ticks=0))]})
            assert incoherent_tickers(s, _gate({"AAPL": _gate_entry(ticks=3)})) == \
                {"AAPL": ["ticks"]}, f"{bucket} rows must be graded"
