"""Synthetic archive and local PostgreSQL proof, never production acceptance."""
from __future__ import annotations
import copy
import io
import json
import os
import shutil
import socket
import subprocess
import tarfile
from decimal import Decimal
from pathlib import Path
import pytest
from scripts import backup_user_tables as bak

REF = 'a' * 20
KEY = 'synthetic-backup-test-key'


def capsule():
    return dict(schema=bak.SNAPSHOT_SCHEMA, project_ref=REF,
                as_of='2026-10-09T10:00:00+00:00', snapshot='100:105:101,103', timezone='UTC',
                tables={n: [] for n in bak.IW2_TABLES}, counts={n: 0 for n in bak.IW2_TABLES})


def test_historical_exact_head_archive_remains_readable():
    # Generated by exact 7532 head 21d35c48, synthetic rows and test key only.
    raw = (Path(__file__).parent / 'fixtures/user_table_backup_v1.tar.gz').read_bytes()
    manifest, tables = bak.parse_tar(raw)
    assert manifest['schema'] == bak.SCHEMA
    assert tuple(tables) == bak.PROTECTED_TABLES
    assert tables['profiles'].rows == [{'id': 'synthetic-old-archive', 'n': 1}]
    actual = bak.restore_via_writer(tables, lambda name, rows: len(rows))
    assert bak.verify_tables(manifest['tables'], actual)['ok']
    store = bak.MemoryStore()
    enc, man = bak.object_keys(manifest['backup_id'], bak.DEFAULT_PREFIX)
    store.put(enc, bak.encrypt_payload(raw, KEY))
    store.put(man, json.dumps({**manifest, 'payload_sha256': bak.sha256_bytes(raw)}).encode())
    assert bak.load_artifact(store, manifest['backup_id'], bak.DEFAULT_PREFIX, KEY).tables == tables
    sidecar = json.loads(store.get(man))
    sidecar['source']['project_ref'] = 'mismatched-source'
    store.put(man, json.dumps(sidecar).encode())
    with pytest.raises(bak.BackupError, match='identity mismatch'):
        bak.load_artifact(store, manifest['backup_id'], bak.DEFAULT_PREFIX, KEY)


def test_iw2_archive_preserves_numeric_precision_and_all_tables():
    c = capsule()
    c['tables']['chart_layout_revisions'] = [{'config': {'value': Decimal('1.123456789012345678901')}}]
    c['counts']['chart_layout_revisions'] = 1
    tables, source = bak.parse_snapshot(bak.json_value(c).encode(), REF)
    artifact = bak.make_artifact(tables, mode='snapshot', source=source, key=KEY)
    manifest, loaded = bak.parse_tar(bak.decrypt_payload(artifact.ciphertext, KEY))
    assert manifest['schema'] == bak.IW2_SCHEMA
    assert len(loaded) == 13
    assert loaded['chart_layout_revisions'].rows == c['tables']['chart_layout_revisions']


@pytest.mark.parametrize('mutation', ['missing', 'extra', 'count', 'bool-count', 'row', 'project', 'schema', 'snapshot', 'date'])
def test_incomplete_or_malformed_snapshot_refused(mutation):
    c = capsule()
    if mutation == 'missing': del c['tables']['investigation_revisions']
    elif mutation == 'extra': c['tables']['auth.users'] = []
    elif mutation == 'count': c['counts']['investigations'] = 1
    elif mutation == 'bool-count': c['counts']['investigations'] = False
    elif mutation == 'row':
        c['tables']['investigations'] = [None]
        c['counts']['investigations'] = 1
    elif mutation == 'project': c['project_ref'] = 'b' * 20
    elif mutation == 'schema': c['schema'] = 'unknown'
    elif mutation == 'snapshot': c['snapshot'] = 'not-a-snapshot'
    else: c['as_of'] = 'not-a-date'
    with pytest.raises(bak.BackupError): bak.parse_snapshot(json.dumps(c).encode(), REF)


def test_management_row_shape_and_import_bound(monkeypatch):
    tables, _ = bak.parse_snapshot(json.dumps([{'snapshot': capsule()}]).encode(), REF)
    assert len(tables) == 13
    monkeypatch.setattr(bak, 'MAX_SNAPSHOT_BYTES', 10)
    with pytest.raises(bak.BackupError, match='bounded'):
        bak.parse_snapshot(json.dumps(capsule()).encode(), REF)


@pytest.mark.parametrize('mutation', ['missing', 'extra', 'duplicate', 'foreign-prefix', 'content', 'manifest'])
def test_archive_rejects_wrong_members_or_content(mutation):
    raw = (Path(__file__).parent / 'fixtures/user_table_backup_v1.tar.gz').read_bytes()
    with tarfile.open(fileobj=io.BytesIO(raw), mode='r:gz') as archive:
        members = [(m.name, archive.extractfile(m).read()) for m in archive.getmembers()]
    if mutation == 'missing': members.pop()
    elif mutation == 'extra': members.append(('extra/tables/evil.jsonl', b'{}\n'))
    elif mutation == 'duplicate': members.append(members[-1])
    elif mutation == 'foreign-prefix': members = [('foreign/' + n.split('/', 1)[1], d) for n, d in members]
    elif mutation == 'content': members[-1] = (members[-1][0], b'{"changed":true}\n')
    else: members[0] = (members[0][0], b'not json')
    out = io.BytesIO()
    with tarfile.open(fileobj=out, mode='w:gz') as archive:
        for name, data in members: bak._add_bytes(archive, name, data)
    with pytest.raises(bak.BackupError): bak.parse_tar(out.getvalue())


def test_snapshot_cli_requires_complete_sql_path(monkeypatch, tmp_path, capsys):
    monkeypatch.setenv('BACKUP_ENCRYPTION_KEY', KEY)
    monkeypatch.setattr(bak.sys, 'stdin', io.TextIOWrapper(io.BytesIO(json.dumps(capsule()).encode())))
    args = ['dump', '--table-set', 'iw2', '--source-project-ref', REF, '--local-dir', str(tmp_path)]
    assert bak.main([*args, '--mode', 'rest']) == 2
    assert bak.main([*args, '--mode', 'snapshot', '--allow-missing']) == 2
    assert bak.main([*args, '--mode', 'snapshot']) == 0
    assert set(json.loads(capsys.readouterr().out)['tables']) == set(bak.IW2_TABLES)


def test_receipt_rejects_lookalike_and_failed_verification():
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    kw = dict(backup_id='synthetic', started=now, ended=now, source_as_of=None,
              commands=[], environment='scratch-postgres')
    for dest, ok in [('postgresql://u:p@supabase.internal/db', True), (f'https://{REF}.supabase.co', False)]:
        assert not bak.build_receipt(dest=dest, verification={'ok': ok}, **kw)['gate1_scratch_supabase']


@pytest.fixture
def postgres(tmp_path):
    if not all(shutil.which(c) for c in ('psql', 'initdb', 'pg_ctl')):
        pytest.skip('local PostgreSQL unavailable; not production restore proof')
    if hasattr(os, 'geteuid') and os.geteuid() == 0: pytest.skip('initdb refuses root')
    data = tmp_path / 'db'
    subprocess.run(['initdb', '-D', str(data), '-A', 'trust', '--no-locale'], capture_output=True, check=True)
    with socket.socket() as sock:
        sock.bind(('127.0.0.1', 0))
        port = sock.getsockname()[1]
    subprocess.run(['pg_ctl', '-D', str(data), '-l', str(tmp_path / 'pg.log'),
                    '-o', f"-F -p {port} -h 127.0.0.1 -k ''", '-w', 'start'], capture_output=True, check=True)
    url = f'postgresql://127.0.0.1:{port}/postgres'
    def sql(query):
        return subprocess.run(['psql', '-X', '-qAt', '-v', 'ON_ERROR_STOP=1', '-d', url],
                              input=query, text=True, capture_output=True, check=True).stdout
    try:
        sql('\n'.join(f'CREATE TABLE public.{n}(id text PRIMARY KEY, payload jsonb NOT NULL);' for n in bak.IW2_TABLES))
        yield url, sql
    finally:
        subprocess.run(['pg_ctl', '-D', str(data), '-m', 'fast', '-w', 'stop'], capture_output=True, check=True)


def test_real_postgres_snapshot_restore_and_atomic_failure(postgres):
    url, sql = postgres
    payload = {'layout_revision_id': 'kept-exact', 'revision': 2,
               'value': Decimal('1.123456789012345678901'), 'quoted': "'\\$mmx_restore$"}
    encoded = bak.json_value(payload).replace("'", "''")
    sql('\n'.join(f"INSERT INTO {n} VALUES ('{n}', '{encoded}');" for n in bak.IW2_TABLES))
    tables, _ = bak.parse_snapshot(sql(bak.snapshot_query(REF)).encode(), REF)
    assert all(t.rows[0]['payload'] == payload for t in tables.values())
    sql('TRUNCATE ' + ','.join(bak.IW2_TABLES) + ';')
    assert bak.pg_insert_jsonl(url, tables) == {n: 1 for n in bak.IW2_TABLES}
    again, _ = bak.parse_snapshot(sql(bak.snapshot_query(REF)).encode(), REF)
    assert {n: t.rows for n, t in again.items()} == {n: t.rows for n, t in tables.items()}
    sql('TRUNCATE ' + ','.join(bak.IW2_TABLES) + ';')
    sql("ALTER TABLE investigation_mutation_receipts ADD CONSTRAINT reject_receipt CHECK (id <> 'investigation_mutation_receipts');")
    with pytest.raises(bak.BackupError, match='rolled back'): bak.pg_insert_jsonl(url, tables)
    assert all(not t.rows for t in bak.parse_snapshot(sql(bak.snapshot_query(REF)).encode(), REF)[0].values())
    sql('ALTER TABLE investigation_mutation_receipts DROP CONSTRAINT reject_receipt;')
    changed = copy.deepcopy(tables)
    changed['profiles'].rows[0]['unexpected_column'] = 'cannot round trip'
    with pytest.raises(bak.BackupError, match='rolled back'): bak.pg_insert_jsonl(url, changed)
    assert sql('SELECT count(*) FROM profiles;').strip() == '0'


def test_legacy_rest_restore_preserves_decimal_type(monkeypatch):
    sent = []
    class Response:
        def __enter__(self): return self
        def __exit__(self, *args): pass
        def read(self): return b''
    def transport(request, **kwargs):
        sent.append(request.data)
        return Response()
    monkeypatch.setattr(bak.urllib.request, 'urlopen', transport)
    rows = [{'value': Decimal('1.123456789012345678901')}]
    assert bak.write_via_rest('chart_layouts', rows, base_url='https://scratch.invalid', service_key='synthetic') == 1
    assert json.loads(sent[0], parse_float=Decimal) == rows
    assert b'"1.123456789012345678901"' not in sent[0]


def test_typed_iw2_links_and_source_timezone_survive(postgres):
    url, sql = postgres
    actor = '11111111-1111-4111-8111-111111111111'
    target = '22222222-2222-4222-8222-222222222222'
    retained = '33333333-3333-4333-8333-333333333333'
    layout = '44444444-4444-4444-8444-444444444444'
    op = '55555555-5555-4555-8555-555555555555'
    sql('''DROP TABLE investigations, investigation_revisions, investigation_mutation_receipts, chart_layout_revisions;
    CREATE TABLE investigations(id uuid PRIMARY KEY, user_id uuid NOT NULL, current_revision integer NOT NULL, lifecycle text NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, UNIQUE(id,user_id));
    CREATE TABLE investigation_revisions(investigation_id uuid, user_id uuid, revision integer, action text, lifecycle text, manifest jsonb, committed_at timestamptz, PRIMARY KEY(investigation_id,revision), FOREIGN KEY(investigation_id,user_id) REFERENCES investigations(id,user_id));
    CREATE TABLE investigation_mutation_receipts(user_id uuid, operation_id uuid, request jsonb, result jsonb, PRIMARY KEY(user_id,operation_id));
    CREATE TABLE chart_layout_revisions(id uuid PRIMARY KEY, user_id uuid, layout_id uuid, source_revision integer, name text, config jsonb, digest text, retained_at timestamptz);''')
    manifest = {'layout_refs': [{'layout_id': layout, 'layout_revision_id': retained, 'digest': 'a'*64}], 'evidence_refs': [{'state': 'HISTORICAL_UNAVAILABLE'}]}
    m = json.dumps(manifest).replace("'", "''")
    sql(f"""BEGIN;
    INSERT INTO investigations VALUES ('{target}','{actor}',2,'removed','2026-10-09T01:00Z','2026-10-09T02:00Z');
    INSERT INTO chart_layout_revisions VALUES ('{retained}','{actor}','{layout}',5,'retained','{{}}','{'a'*64}','2026-10-09T01:00Z');
    INSERT INTO investigation_revisions VALUES ('{target}','{actor}',1,'create','active','{m}','2026-10-09T01:00Z'),('{target}','{actor}',2,'remove','removed','{m}','2026-10-09T02:00Z');
    INSERT INTO investigation_mutation_receipts VALUES ('{actor}','{op}','{{"target":"{target}"}}','{{"id":"{target}","revision":2,"manifest":{m}}}'); COMMIT;""")
    raw = sql("SET TIME ZONE 'America/Vancouver';\n" + bak.snapshot_query(REF)).encode()
    tables, source = bak.parse_snapshot(raw, REF)
    sql('TRUNCATE ' + ','.join(bak.IW2_TABLES) + ';')
    bak.pg_insert_jsonl(url, tables, timezone=source['timezone'])
    restored, _ = bak.parse_snapshot(sql("SET TIME ZONE 'America/Vancouver';\n" + bak.snapshot_query(REF)).encode(), REF)
    assert {n: t.rows for n, t in restored.items()} == {n: t.rows for n, t in tables.items()}
    assert sql('SELECT count(*) FROM investigations h JOIN investigation_revisions r ON r.investigation_id=h.id AND r.user_id=h.user_id AND r.revision=h.current_revision;').strip() == '1'
    assert restored['investigation_revisions'].rows[0]['manifest'] == manifest
