"""TP-2 data-only private view contract over ACTUAL TP-B Python synthetic golden.

The golden fixture is generated by TP-B's existing source and calibration
functions at the pinned review commit, not by an invented standalone emitter.
No real vendor data, credentials, auth route, browser or public delivery.
"""
import copy
import hashlib
import json
from pathlib import Path

import pytest

from engine.tp2_private_ruler_view import (
    SCHEMA, TP2PrivateViewRefusal, build_private_tp2_view,
)

FIXTURE = Path(__file__).parent / "fixtures/tp2_tpb_source.synthetic.v0.json"
SOURCE_REV = "23787b0518b6bd9ab807194698014b32976d1f48"


def originals():
    raw = FIXTURE.read_bytes()
    assert hashlib.sha256(raw).hexdigest() == (
        "a499fb167aab3498943663598593408b008b2e98c79565e07177c310cba4a196")
    item = json.loads(raw)
    assert item["schema"] == "tp2.synthetic_tpb_private_input/v0"
    assert item["source_published_head"] == SOURCE_REV
    assert item["note"] == "SYNTHETIC_SOURCE_NO_VENDOR_AUTHENTICITY_OR_FINALITY"
    return item["observation"], item["calibration"]


def context(*, observation=None, calibration=None, now=None):
    original, golden = originals()
    return build_private_tp2_view(
        observation=original if observation is None else observation,
        calibration=golden if calibration is None else calibration,
        view_asof_ns=golden["evaluation_ns"]+1 if now is None else now,
    )


def test_golden_private_tp2_separates_print_cluster_day_from_ats_and_liveness():
    result = context()
    assert result["schema"] == SCHEMA
    assert result["state"] == "PRIVATE_TPB_RESEARCH_CONTEXT_ONLY"
    assert result["ticker"] == "SPY"
    assert result["session"] == "2026-10-08:RTH"
    obs = result["observed_source"]
    assert obs["largest_individual_print_usd"] == "200000"
    assert obs["largest_same_level_cluster_usd"] == "300000"
    assert obs["measured_rth_trf_notional_usd"] == "500000"
    assert obs["n_trf_observed"] == 3
    assert result["historical_ruler"]["SINGLE_PRINT"]["rank_desc_in_observed_sample"] == 1
    assert result["historical_ruler"]["SAME_LEVEL_CLUSTER"]["rank_desc_in_observed_sample"] is None
    assert result["historical_ruler"]["DAILY_TOTAL"]["rank_desc_in_observed_sample"] == 1
    assert result["intraday_minute_baseline"]["conditioning"] == (
        "EXACT_MINUTE_INDEX_RTH_CUMULATIVE_ONLY")
    assert result["intraday_minute_baseline"]["cumulative_offexchange_share"] == "0.4"
    assert result["intraday_minute_baseline"]["median"] == "0.22"
    assert result["live_block_tape"] is None
    assert result["repeat_print_price_shelves"] is None
    assert result["live_signed_offexchange_flow"] is None
    assert result["named_ats_attribution"] is None
    assert result["finra_ats_delayed_context"] is None
    assert result["eod_weekly_context"] == "UNCHANGED_SEPARATE_EXISTING_CONSUMER"
    assert result["public_delivery_allowed"] is False
    assert result["source_authenticated"] is False
    assert result["ranking_trading_alert_authority"] is False
    assert result["signal"] is None


def test_lossless_private_clock_uses_unsigned_decimal_text_not_json_number():
    result = context()
    assert type(result["observation_asof_ns_decimal"]) is str
    assert int(result["observation_asof_ns_decimal"]) > 2**53
    assert result["view_asof_ns_decimal"].isdigit()
    encoded = json.dumps(result, sort_keys=True, separators=(",", ":"))
    assert '"view_asof_ns_decimal":"' in encoded
    assert '"observation_asof_ns_decimal":"' in encoded
    assert str(int(result["view_asof_ns_decimal"])) in encoded


def test_explicit_no_source_and_no_new_auth_plane():
    result = build_private_tp2_view(observation=None, view_asof_ns=100)
    assert result["state"] == "NO_TPB_OBSERVATION_SOURCE"
    assert result["observed_source"] is None
    assert result["historical_ruler"] is None
    assert result["live_block_tape"] is None
    assert result["public_delivery_allowed"] is False
    assert result["eod_weekly_context"] == "UNCHANGED_SEPARATE_EXISTING_CONSUMER"
    _, golden = originals()
    with pytest.raises(TP2PrivateViewRefusal, match="without an original source"):
        build_private_tp2_view(observation=None, calibration=golden, view_asof_ns=100)


def test_source_not_yet_knowable_does_not_emit_future_observation():
    observation, golden = originals()
    out = build_private_tp2_view(
        observation=observation, calibration=golden,
        view_asof_ns=observation["asof_ns"]-1)
    assert out["state"] == "SOURCE_NOT_YET_KNOWABLE"
    assert out["observed_source"] is None
    assert out["historical_ruler"] is None


def test_historical_calibration_not_yet_knowable_stays_pending():
    observation, golden = originals()
    result = build_private_tp2_view(
        observation=observation, calibration=golden,
        view_asof_ns=golden["evaluation_ns"]-1)
    assert result["state"] == "CALIBRATION_NOT_YET_KNOWABLE"
    assert result["observed_source"] is not None
    assert result["historical_ruler"] is None


def test_missing_calibration_is_not_zero_baseline_or_hidden_rank():
    observation, _ = originals()
    result = build_private_tp2_view(
        observation=observation, calibration=None,
        view_asof_ns=observation["asof_ns"]+1)
    assert result["state"] == "HISTORICAL_CALIBRATION_PENDING"
    assert result["observed_source"]["measured_rth_trf_notional_usd"] == "500000"
    assert result["historical_ruler"] is None
    assert result["intraday_minute_baseline"] is None


def test_source_correction_changed_generation_invalidates_old_ranks():
    observation, cal = originals()
    later = copy.deepcopy(observation)
    later["snapshot_sha256"] = "e"*64
    later["source_generation_sha256"] = "f"*64
    later["supersedes_generation_sha256"] = observation["source_generation_sha256"]
    result = build_private_tp2_view(
        observation=later, calibration=cal, view_asof_ns=cal["evaluation_ns"]+1)
    assert result["state"] == "CALIBRATION_STALE_SOURCE_GENERATION"
    assert result["source_generation_sha256"] == "f"*64
    assert result["historical_ruler"] is None
    assert result["intraday_minute_baseline"] is None


def test_no_qualified_sample_is_unknown_not_zero_market_volume():
    observation, _ = originals()
    empty = copy.deepcopy(observation)
    empty["state"] = "NO_QUALIFIED_OFF_EXCHANGE_OBSERVED"
    empty["n_trf_observed"] = 0
    empty["oe_source_notional_usd"] = None
    empty["oe_source_shares"] = None
    empty["largest_individual_print_usd"] = None
    empty["largest_cluster_usd"] = None
    empty["snapshot_sha256"] = "f"*64
    result = build_private_tp2_view(
        observation=empty, view_asof_ns=observation["asof_ns"]+1)
    assert result["state"] == "NO_QUALIFIED_TRF_OBSERVATIONS"
    assert result["reason"] == "NO_QUALIFIED_OFF_EXCHANGE_OBSERVED"
    assert result["observed_source"] is None
    assert result["live_signed_offexchange_flow"] is None


@pytest.mark.parametrize("changed", [
    {"public_delivery_allowed": True},
    {"ranking_trading_alert_authority": True},
    {"source_receipts_authenticated": True},
    {"market_capture_completeness_proven": True},
    {"actor_identity": "UNKNOWN_INSTITUTION"},
    {"signal": {"buy": True}},
    {"authority": "TRADING_SIGNAL"},
])
def test_source_unauthorized_authority_is_never_read_as_admitted(changed):
    observation, _ = originals()
    bad = dict(observation, **changed)
    with pytest.raises(TP2PrivateViewRefusal, match="unauthorized source promotion"):
        build_private_tp2_view(observation=bad, view_asof_ns=observation["asof_ns"]+100)


@pytest.mark.parametrize("changed", [
    {"public_delivery_allowed": True},
    {"ranking_trading_alert_authority": True},
    {"source_authenticated": True},
    {"named_ats_attribution": {"broker": "fabricated"}},
    {"signal": {"sell": True}},
])
def test_calibration_unauthorized_authority_is_never_rendered(changed):
    observation, golden = originals()
    bad = dict(golden, **changed)
    with pytest.raises(TP2PrivateViewRefusal, match="unauthorized data promotion"):
        build_private_tp2_view(
            observation=observation, calibration=bad,
            view_asof_ns=golden["evaluation_ns"]+1)


@pytest.mark.parametrize("changed", [
    {"ticker": "QQQ"},
    {"target_session": "2026-10-09:RTH"},
    {"basis_id": "WRONG_BASIS"},
    {"basis_vintage_sha256": "f"*64},
    {"split_segment": "WRONG_SEGMENT"},
])
def test_wrong_historical_identity_or_split_basis_refused(changed):
    observation, golden = originals()
    bad = dict(golden, **changed)
    with pytest.raises(TP2PrivateViewRefusal):
        build_private_tp2_view(observation=observation, calibration=bad,
                               view_asof_ns=golden["evaluation_ns"]+1)


def test_partial_day_cannot_gain_daily_rank_from_old_calibration():
    observation, golden = originals()
    partial = dict(observation, full_rth_covered=False)
    with pytest.raises(TP2PrivateViewRefusal, match="full-session rank on partial day"):
        build_private_tp2_view(observation=partial, calibration=golden,
                               view_asof_ns=golden["evaluation_ns"]+1)


def test_future_calibration_before_source_refused():
    observation, golden = originals()
    bad = dict(golden, evaluation_ns=observation["asof_ns"]-1)
    with pytest.raises(TP2PrivateViewRefusal, match="evaluated before source"):
        build_private_tp2_view(observation=observation, calibration=bad,
                               view_asof_ns=golden["evaluation_ns"]+1)


def test_private_reader_rejects_relabelled_rth_dates_and_wrong_source_clock():
    observation, golden = originals()
    mislabeled = dict(observation, session="2026-10-09:RTH")
    with pytest.raises(TP2PrivateViewRefusal, match="RTH.*clock"):
        build_private_tp2_view(observation=mislabeled, view_asof_ns=golden["evaluation_ns"]+1)
    wrong_open = dict(observation, start_ns=observation["start_ns"]+60_000_000_000)
    with pytest.raises(TP2PrivateViewRefusal, match="RTH.*clock"):
        build_private_tp2_view(observation=wrong_open, view_asof_ns=golden["evaluation_ns"]+1)


def test_private_reader_rejects_print_or_cluster_greater_than_source_total():
    observation, golden = originals()
    for key, amount in (
        ("largest_individual_print_usd", "999999"),
        ("largest_cluster_usd", "999999"),
    ):
        bad = dict(observation, **{key: amount})
        with pytest.raises(TP2PrivateViewRefusal, match="source total"):
            build_private_tp2_view(observation=bad, view_asof_ns=golden["evaluation_ns"]+1)


def test_unsafe_source_exponent_and_oversized_ranks_are_not_promoted():
    observation, golden = originals()
    forged = dict(observation, largest_individual_print_usd="1e99999999")
    with pytest.raises(TP2PrivateViewRefusal, match="bounded"):
        build_private_tp2_view(observation=forged, calibration=golden,
                               view_asof_ns=golden["evaluation_ns"]+1)
    bad_rank = copy.deepcopy(golden)
    bad_rank["daily_object_ranks"]["DAILY_TOTAL"]["rank_desc"] = 1000
    with pytest.raises(TP2PrivateViewRefusal, match="invalid rank"):
        build_private_tp2_view(observation=observation, calibration=bad_rank,
                               view_asof_ns=golden["evaluation_ns"]+1)


def test_tampered_minute_after_rth_end_or_out_of_range_fraction_refused():
    observation, golden = originals()
    future_minute = copy.deepcopy(golden)
    future_minute["minute_conditioned_baseline"]["minute_index"] = 389
    with pytest.raises(TP2PrivateViewRefusal, match="minute-matched baseline"):
        build_private_tp2_view(observation=observation, calibration=future_minute,
                               view_asof_ns=golden["evaluation_ns"]+1)
    forged_share = copy.deepcopy(golden)
    forged_share["minute_conditioned_baseline"]["share"] = "2.0"
    with pytest.raises(TP2PrivateViewRefusal, match="minute.*share"):
        build_private_tp2_view(observation=observation, calibration=forged_share,
                               view_asof_ns=golden["evaluation_ns"]+1)


def test_unknown_daily_rank_state_or_invalid_minute_conditioning_refused():
    observation, golden = originals()
    invalid = copy.deepcopy(golden)
    invalid["daily_object_ranks"]["DAILY_TOTAL"]["state"] = "VALIDATED_SIGNAL"
    with pytest.raises(TP2PrivateViewRefusal, match="invalid daily rank"):
        build_private_tp2_view(observation=observation, calibration=invalid,
                               view_asof_ns=golden["evaluation_ns"]+1)
    invalid = copy.deepcopy(golden)
    invalid["minute_conditioned_baseline"]["conditioning"] = "FULL_DAY_BASELINE"
    with pytest.raises(TP2PrivateViewRefusal, match="minute-matched baseline"):
        build_private_tp2_view(observation=observation, calibration=invalid,
                               view_asof_ns=golden["evaluation_ns"]+1)
