"""Live Entry Radar PR-4 (W4) — the frozen substrate pack + inversion proof.

WHAT THIS SUITE IS FOR
----------------------
The pack is the only thing standing between a mid-session store move and a
fabricated crossing (contract §5 stale-pack row, §7.1).  Everything the RTH lane
will compare against is decided here, once, at a session boundary — so every
property below is a property of an artifact nobody will re-derive:

  PACK-1   the frozen substrate is byte-stable and its fingerprint pins it
  PACK-2   ``pack_hash`` moves iff FIRING-relevant content moves — a re-build a
           minute later is the same pack; one changed close is not
  PACK-3   a solved threshold agrees with the W3 oracle on BOTH sides of itself,
           and ``condition_at_boundary`` makes the strict inequality unambiguous
  PACK-4   every §7.1 degeneracy is REACHABLE and NAMED — never an absent or
           unbounded level
  PACK-5   a drifted detector spec_hash REFUSES the build, before a price is read
  PACK-6   the inversion proof passes on a healthy pack, and each of its six
           families FAILS under its own seeded defect (PIT-W4-19)
  PACK-7   save/load/prune keep the pointer and the substrate consistent
  PACK-8   the W4/W5 firewall: no field in the manifest needs post-observation
           knowledge

EVERY LOAD-BEARING GUARD CARRIES A MUTATION CONTROL.  A test that only restates
today's behaviour proves the code does what it does; the controls below prove
each property is load-bearing by breaking it and watching the guard fire.

THE FIXTURES ARE SYNTHETIC AND SAY SO.  Closes are generated by a deterministic
trend + ripple (no randomness, no ``data/``, no network, no ``site/``).  A pure
linear trend is deliberately AVOIDED for the oscillator cases: its RSI is
constant, so its StochRSI rolling extremes coincide and %K is NaN everywhere —
that is the ``flat_rsi_nan`` degeneracy, which this suite reaches on purpose with
a separate fixture rather than by accident with all of them.
"""
from __future__ import annotations

import ast
import json
import math
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from engine import session_anchor
from engine.entry_radar import challengers as ch
from engine.entry_radar import detectors as dt
from engine.entry_radar import indicator_core as ic
from engine.entry_radar import live_pack as lp
from engine.entry_radar.contracts import AdmissionReason, ProbeRecord
from engine.entry_radar.universe import ProbeSet

ROOT = Path(__file__).resolve().parents[1]
RADAR_DIR = ROOT / "engine" / "entry_radar"

#: The pack this suite freezes.  A real NYSE session, so the reference calendar
#: answers rather than a synthetic index.
AS_OF = date(2026, 8, 14)
NEXT_SESSION = date(2026, 8, 17)

#: W4's two new engine modules.  Named explicitly so the guards below cannot go
#: vacuous through a glob that matches nothing.
W4_BUILDER_A_MODULES = ("live_pack.py", "live_ledger.py")


# ---------------------------------------------------------------------------
# synthetic fixtures — deterministic, no randomness anywhere
# ---------------------------------------------------------------------------

def ripple(i: int, amp: float = 0.04, period: float = 11.0) -> float:
    return 1.0 + amp * math.sin(2.0 * math.pi * i / period)


def sessions_ending(n: int, end: date = AS_OF) -> pd.DatetimeIndex:
    reference = session_anchor.reference_sessions("US")
    position = int(reference.searchsorted(pd.Timestamp(end).normalize(), side="right"))
    return pd.DatetimeIndex(reference[max(0, position - n):position])


def frame_from_closes(closes, end: date = AS_OF) -> pd.DataFrame:
    index = sessions_ending(len(closes), end)
    values = np.asarray(list(closes)[-len(index):], dtype=float)
    return pd.DataFrame({"open": values, "high": values * 1.01,
                         "low": values * 0.99, "close": values,
                         "volume": np.full(len(values), 1_000.0)},
                        index=index)


def washout_closes() -> list[float]:
    """A long rippled decline, then a steady slide — %K pinned at 0.

    Its prior two ``rawk`` values sit at the 14-bar minimum, which is what leaves
    room for ``K = SMA(3)`` to cross 20 as the appended close moves: the C1 level
    EXISTS for this shape.
    """
    prefix = [(200.0 - 0.5 * i) * ripple(i) for i in range(180)]
    return prefix + [prefix[-1] * (0.975 ** k) for k in range(1, 13)]


def vshape_closes() -> list[float]:
    """A deep washout, then two strong up bars — the saturation shapes.

    C1 is ``never_true`` here (at 3x the close ``rawk`` saturates at 100, so
    ``K >= 33`` whatever the price) and C2a is ``always_true`` (``K - D`` is
    positive across the whole bracket).  Both are §7.1's own named degeneracies.
    """
    prefix = [(200.0 - 0.5 * i) * ripple(i) for i in range(180)]
    body = prefix + [prefix[-1] * (0.97 ** k) for k in range(1, 11)]
    return body + [body[-1] * 1.13, body[-1] * 1.30]


FLAT_CLOSES = [100.0] * 200
SHORT_CLOSES = [100.0 + i for i in range(8)]


def store(**overrides) -> dict[str, pd.DataFrame]:
    frames = {
        "WASH": frame_from_closes(washout_closes()),
        "VSHAPE": frame_from_closes(vshape_closes()),
        "FLAT": frame_from_closes(FLAT_CLOSES),
        "SHORT": frame_from_closes(SHORT_CLOSES),
        # last_confirmed lags AS_OF by weeks — the per-name staleness case
        "STALE": frame_from_closes(washout_closes(), date(2026, 7, 10)),
    }
    frames.update(overrides)
    return frames


def reader_for(frames):
    def reader(ticker: str):
        return frames.get(ticker)
    return reader


def build(frames=None, *, tickers=None, built_at=None, **kwargs) -> lp.LivePack:
    frames = store() if frames is None else frames
    return lp.build_pack(
        probe_set=list(tickers if tickers is not None else sorted(frames)),
        store_reader=reader_for(frames), as_of=AS_OF,
        built_at=built_at or datetime(2026, 8, 15, 2, 0, tzinfo=timezone.utc),
        **kwargs)


@pytest.fixture(scope="module")
def pack() -> lp.LivePack:
    return build()


@pytest.fixture(scope="module")
def proof(pack) -> dict:
    return lp.build_inversion_proof(pack)


def oracle_for(pack: lp.LivePack, ticker: str) -> lp.OracleFrame:
    frame = pack.substrate[ticker]
    return lp.OracleFrame(
        ticker=ticker, closes=frame["close"].astype(float).to_numpy(dtype=float),
        index=pd.DatetimeIndex(frame.index),
        next_session_ts=pd.Timestamp(pack.next_session).normalize())


# ---------------------------------------------------------------------------
# PACK-1 — the freeze
# ---------------------------------------------------------------------------

def test_PACK1_the_frozen_substrate_is_byte_stable_across_builds():
    first, second = build(), build()
    assert sorted(first.substrate) == sorted(second.substrate)
    for ticker, frame in first.substrate.items():
        pd.testing.assert_frame_equal(frame, second.substrate[ticker])
    assert [n.substrate_fingerprint for n in first.names] == \
           [n.substrate_fingerprint for n in second.names]


def test_PACK1_the_freeze_cuts_at_as_of_and_nothing_after_it(pack):
    for ticker, frame in pack.substrate.items():
        last = pd.DatetimeIndex(frame.index)[-1].date()
        assert last <= AS_OF, f"{ticker} carries a row after as_of"


def test_PACK1_a_name_whose_history_lags_as_of_is_STALE_not_silently_current(pack):
    rows = pack.by_ticker()
    assert rows["STALE"].last_confirmed < AS_OF.isoformat()
    assert rows["STALE"].freshness == "stale"
    assert rows["WASH"].freshness == "confirmed"


def test_PACK1_the_fingerprint_pins_the_frozen_bytes():
    frames = store()
    base = build(frames).by_ticker()["WASH"].substrate_fingerprint
    moved = dict(frames)
    bumped = moved["WASH"].copy()
    bumped.iloc[-1, bumped.columns.get_loc("close")] += 0.01
    moved["WASH"] = bumped
    assert build(moved).by_ticker()["WASH"].substrate_fingerprint != base


def test_PACK1_a_missing_name_is_recorded_never_dropped_and_never_raises():
    pack = build(tickers=["WASH", "GONE"])
    assert [row["ticker"] for row in pack.substrate_missing] == ["GONE"]
    assert pack.substrate_missing[0]["reason"] == "substrate_absent"
    assert [n.ticker for n in pack.names] == ["WASH"]


def test_PACK1_a_raising_store_reader_costs_its_own_name_and_nothing_else():
    def reader(ticker):
        if ticker == "BOOM":
            raise OSError("disk on fire")
        return store().get(ticker)

    pack = lp.build_pack(probe_set=["WASH", "BOOM"], store_reader=reader, as_of=AS_OF,
                         built_at=datetime(2026, 8, 15, tzinfo=timezone.utc))
    assert [n.ticker for n in pack.names] == ["WASH"]
    assert pack.substrate_missing[0]["reason"] == "store_read_failed"


def test_PACK1_a_duplicated_session_is_REFUSED_not_silently_deduped():
    frames = store()
    doubled = pd.concat([frames["WASH"], frames["WASH"].iloc[[-1]]])
    pack = build({**frames, "WASH": doubled})
    reasons = {row["ticker"]: row["reason"] for row in pack.substrate_missing}
    assert reasons["WASH"] == "substrate_rejected"


# ---------------------------------------------------------------------------
# PACK-2 — pack_hash coverage
# ---------------------------------------------------------------------------

def test_PACK2_hash_is_stable_when_only_built_at_moves():
    a = build(built_at=datetime(2026, 8, 15, 2, 0, tzinfo=timezone.utc))
    b = build(built_at=datetime(2026, 8, 15, 3, 30, tzinfo=timezone.utc))
    assert a.built_at != b.built_at
    assert a.pack_hash == b.pack_hash


def test_PACK2_hash_moves_when_one_close_moves():
    frames = store()
    base = build(frames).pack_hash
    moved = dict(frames)
    bumped = moved["WASH"].copy()
    bumped.iloc[-1, bumped.columns.get_loc("close")] += 0.01
    moved["WASH"] = bumped
    assert build(moved).pack_hash != base


def _with_moved_level(row: lp.PackName, factor: float = 1.5) -> lp.PackName:
    """The same name with its c1 level shifted — the corruption these tests plant."""
    raw = row.to_dict()
    raw["c1_arm_price"] = {**raw["c1_arm_price"],
                           "price": float(row.c1_arm_price.price) * factor}
    return lp.PackName.from_dict(raw)


def test_PACK2_hash_moves_when_a_solved_threshold_moves(pack):
    names = list(pack.names)
    index = next(i for i, n in enumerate(names)
                 if not n.c1_arm_price.no_threshold_exists)
    names[index] = _with_moved_level(names[index])
    moved = lp.compute_pack_hash(
        schema=pack.schema, as_of=pack.as_of, next_session=pack.next_session,
        price_basis=pack.price_basis, spec_hashes=pack.spec_hashes,
        probe_tickers=pack.probe_set["tickers"], names=names)
    assert moved != pack.pack_hash


def test_PACK2_hash_moves_when_a_spec_hash_moves(pack):
    moved = lp.compute_pack_hash(
        schema=pack.schema, as_of=pack.as_of, next_session=pack.next_session,
        price_basis=pack.price_basis,
        spec_hashes={**pack.spec_hashes, "C1_1D_LIVE_WASHOUT@1": "0" * 16},
        probe_tickers=pack.probe_set["tickers"], names=pack.names)
    assert moved != pack.pack_hash


def test_PACK2_hash_is_order_independent_in_the_probe_set(pack):
    shuffled = list(reversed(pack.probe_set["tickers"]))
    assert lp.compute_pack_hash(
        schema=pack.schema, as_of=pack.as_of, next_session=pack.next_session,
        price_basis=pack.price_basis, spec_hashes=pack.spec_hashes,
        probe_tickers=shuffled, names=pack.names) == pack.pack_hash


def test_PACK2_the_proof_is_a_statement_ABOUT_the_pack_not_part_of_it(pack, proof):
    assert pack.with_proof(proof).pack_hash == pack.pack_hash


# ---------------------------------------------------------------------------
# PACK-3 — the inverted thresholds agree with the oracle
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("condition,margin", [
    ("c1_arm_price", lp._c1_margin),
    ("c2a_cross_price", lp._c2a_margin),
])
def test_PACK3_a_solved_level_agrees_with_the_oracle_on_both_sides(pack, condition,
                                                                   margin):
    row = pack.by_ticker()["WASH"]
    solution = getattr(row, condition)
    assert not solution.no_threshold_exists, f"WASH should solve {condition}"
    frame = oracle_for(pack, "WASH")
    level = float(solution.price)
    for side in (1.0 - lp.PROOF_EPSILON_REL, 1.0 + lp.PROOF_EPSILON_REL):
        price = level * side
        observed = margin(frame, price) > 0.0
        assert observed is solution.holds_at(price), (
            f"{condition} disagrees with the oracle at {price}")


def test_PACK3_the_two_conditions_run_in_OPPOSITE_directions(pack):
    row = pack.by_ticker()["WASH"]
    assert row.c1_arm_price.direction == "below"
    assert row.c2a_cross_price.direction == "above"


def test_PACK3_condition_at_boundary_is_the_oracle_verdict_AT_the_level(pack):
    row = pack.by_ticker()["WASH"]
    frame = oracle_for(pack, "WASH")
    for solution, margin in ((row.c1_arm_price, lp._c1_margin),
                             (row.c2a_cross_price, lp._c2a_margin)):
        if solution.no_threshold_exists:
            continue
        assert solution.condition_at_boundary is (margin(frame, solution.price) > 0.0)
        assert solution.holds_at(solution.price) is solution.condition_at_boundary


def test_PACK3_bisection_meets_the_declared_relative_tolerance(pack):
    row = pack.by_ticker()["WASH"]
    frame = oracle_for(pack, "WASH")
    level = float(row.c1_arm_price.price)
    # Ten tolerances either side must already be decided; the level is not a
    # fuzzy region.
    span = float(row.as_of_close) * lp.BISECTION_REL_TOLERANCE * 10.0
    assert (lp._c1_margin(frame, level - span) > 0.0) is True
    assert (lp._c1_margin(frame, level + span) > 0.0) is False


def test_PACK3_the_oracle_mirrors_build_observation_path_exactly(pack):
    """The level's own construction and the live path's must be one construction.

    If these two diverge the pack becomes a second implementation of the
    oscillator — the exact defect ``indicator_core``'s module docstring exists to
    prevent — and every level in it would be about a series nobody evaluates.
    """
    frame = pack.substrate["WASH"]
    history = ch.DailyHistory(frame=frame, price_basis=ch.BASIS_ADJUSTED,
                              vintage="w4-fixture")
    price = float(pack.by_ticker()["WASH"].as_of_close) * 0.97
    open_dt, _close = ch.session_window_et(NEXT_SESSION)
    tape = ch.SessionTape(
        session=NEXT_SESSION,
        minutes=(ch.MinuteBar(start=open_dt + timedelta(minutes=1), open=price,
                              high=price, low=price, close=price),),
        price_basis=ch.BASIS_ADJUSTED, vintage="w4-fixture")
    observations = ch.build_observation_path(ticker="WASH", daily=history, tapes=[tape])
    live_k = observations[0].k
    oracle_k, _d = oracle_for(pack, "WASH").kd(price)
    assert live_k == pytest.approx(oracle_k, rel=0, abs=0)


# ---------------------------------------------------------------------------
# PACK-4 — every degeneracy is reachable and NAMED
# ---------------------------------------------------------------------------

def test_PACK4_flat_rsi_nan_is_reachable(pack):
    rows = pack.by_ticker()
    for ticker in ("FLAT", "SHORT"):
        assert rows[ticker].confirmed_k is None
        assert rows[ticker].c1_arm_price.reason == "flat_rsi_nan"
        assert rows[ticker].c1_arm_price.price is None


def test_PACK4_never_true_and_always_true_are_reachable(pack):
    row = pack.by_ticker()["VSHAPE"]
    assert row.c1_arm_price.reason == "never_true"
    assert row.c1_arm_price.bracket_verdict is False
    assert row.c2a_cross_price.reason == "always_true"
    assert row.c2a_cross_price.bracket_verdict is True


def test_PACK4_a_saturated_condition_still_answers_the_evaluator(pack):
    """``no_threshold_exists`` is not a hole: the constant verdict is recorded."""
    row = pack.by_ticker()["VSHAPE"]
    assert row.c1_arm_price.holds_at(1.0) is False
    assert row.c1_arm_price.holds_at(10_000.0) is False
    assert row.c2a_cross_price.holds_at(1.0) is True


def test_PACK4_non_monotone_is_reachable_and_refuses_a_level():
    """A margin that reverses must NOT be bisected into a confident wrong level.

    The real oscillator is monotone in the appended close (§7.1), so this
    degeneracy is reached with a hand-written margin — which is also the mutation
    control for the monotonicity check itself.
    """
    def wobbly(price: float) -> float:
        return -(price - 100.0) ** 2 + 25.0

    solution = lp.solve_threshold(wobbly, condition="probe", predicate="probe",
                                  anchor=100.0, decreasing=True)
    assert solution.no_threshold_exists
    assert solution.reason == "non_monotone"
    assert solution.price is None


def test_PACK4_CONTROL_a_monotone_margin_is_solved_not_refused():
    solution = lp.solve_threshold(lambda p: 100.0 - p, condition="probe",
                                  predicate="probe", anchor=100.0, decreasing=True)
    assert not solution.no_threshold_exists
    assert solution.price == pytest.approx(100.0, rel=1e-5)


def test_PACK4_every_named_degeneracy_is_in_the_frozen_reason_list(pack):
    seen = {row.reason for name in pack.names
            for row in (name.c1_arm_price, name.c2a_cross_price)
            if row.no_threshold_exists}
    assert seen, "the fixture set must exercise at least one degeneracy"
    assert seen <= set(lp.DEGENERATE_REASONS)


def test_PACK4_a_level_with_no_price_is_REFUSED_at_construction():
    with pytest.raises(lp.LivePackError, match="absent level"):
        lp.ThresholdSolution(
            condition="c1_arm_price", predicate="K<20", direction="below", price=None,
            condition_at_boundary=None, no_threshold_exists=False, reason=None,
            bracket_low=1.0, bracket_high=3.0)


def test_PACK4_an_unnamed_degeneracy_is_REFUSED_at_construction():
    with pytest.raises(lp.LivePackError, match="EXPLICIT named"):
        lp.ThresholdSolution(
            condition="c1_arm_price", predicate="K<20", direction="below", price=None,
            condition_at_boundary=None, no_threshold_exists=True, reason="dunno",
            bracket_low=1.0, bracket_high=3.0)


def test_PACK4_a_degeneracy_carrying_a_price_is_REFUSED():
    with pytest.raises(lp.LivePackError, match="exclusive"):
        lp.ThresholdSolution(
            condition="c1_arm_price", predicate="K<20", direction="below", price=12.0,
            condition_at_boundary=None, no_threshold_exists=True,
            reason="never_true", bracket_low=1.0, bracket_high=3.0)


def test_PACK4_the_bracket_is_bounded_and_documented(pack):
    row = pack.by_ticker()["WASH"]
    assert row.c1_arm_price.bracket_low == pytest.approx(
        row.as_of_close * lp.BRACKET_LOW_MULTIPLE)
    assert row.c1_arm_price.bracket_high == pytest.approx(
        row.as_of_close * lp.BRACKET_HIGH_MULTIPLE)


# ---------------------------------------------------------------------------
# PACK-5 — the spec-hash gate
# ---------------------------------------------------------------------------

def test_PACK5_the_published_hashes_are_the_registered_ones():
    assert lp.registered_spec_hashes() == lp.PUBLISHED_SPEC_HASHES
    assert lp.assert_published_spec_hashes() == lp.PUBLISHED_SPEC_HASHES


def test_PACK5_F1_FUSION_still_refuses():
    with pytest.raises(dt.NotYetSpecified):
        dt.get_spec("F1_FUSION")


def test_PACK5_a_drifted_registry_hash_REFUSES_the_build(monkeypatch):
    tampered = dt.DetectorSpec(
        detector_id=ch.C1_DETECTOR_ID, version=ch.C1_VERSION, grain=ch.C1_GRAIN,
        bar_family=ch.C1_BAR_FAMILY,
        spec={**ch.C1_SPEC, "oversold_threshold": 21})
    monkeypatch.setitem(dt.DETECTORS, ch.C1_DETECTOR_ID, tampered)
    with pytest.raises(lp.SpecHashDrift, match="REFUSING to build"):
        build()


def test_PACK5_CONTROL_the_untampered_registry_builds(pack):
    assert pack.spec_hashes == lp.PUBLISHED_SPEC_HASHES


# ---------------------------------------------------------------------------
# PACK-6 — the inversion proof (PIT-W4-19)
# ---------------------------------------------------------------------------

def test_PACK6_a_healthy_pack_passes_and_names_its_families(proof):
    assert proof["schema"] == lp.SCHEMA_INVERSION_PROOF
    assert proof["pass"] is True
    assert proof["failures"] == []
    assert set(proof["by_family"]) == {
        "threshold_boundary", "state_micro_path", "rearm", "c2f_rebound",
        "c3_turn", "basis_tolerance"}
    for family, block in proof["by_family"].items():
        assert block["total"] > 0, f"{family} contributed no case"


def test_PACK6_a_healthy_pack_is_not_marked_proof_failed(pack, proof):
    assert pack.with_proof(proof).proof_failed is False


def test_PACK6_an_UNRUN_proof_is_not_a_pass(pack):
    assert pack.proof is None
    assert pack.proof_failed is False, "no proof is not a FAILED proof"
    assert pack.manifest()["proof"] is None


# --- family (a): threshold boundary --------------------------------------

def test_PACK6a_a_corrupted_level_fails_the_proof_and_NAMES_the_case(pack):
    names = list(pack.names)
    index = next(i for i, n in enumerate(names)
                 if not n.c1_arm_price.no_threshold_exists)
    victim = names[index]
    names[index] = _with_moved_level(victim)
    corrupted = lp.LivePack(
        schema=pack.schema, as_of=pack.as_of, next_session=pack.next_session,
        built_at=pack.built_at, price_basis=pack.price_basis,
        spec_hashes=pack.spec_hashes, probe_set=pack.probe_set, names=tuple(names),
        substrate=pack.substrate, pack_hash=pack.pack_hash)
    result = lp.build_inversion_proof(corrupted)
    assert result["pass"] is False
    assert result["by_family"]["threshold_boundary"]["failed"] > 0
    named = {case["case"] for case in result["failures"]}
    assert any(case.startswith(f"{victim.ticker}:c1_arm_price") for case in named), named
    assert corrupted.with_proof(result).proof_failed is True


def test_PACK6a_a_lying_oracle_fails_the_proof(monkeypatch, pack):
    monkeypatch.setattr(lp, "_c1_margin", lambda frame, price: -1.0)
    result = lp.build_inversion_proof(pack)
    assert result["pass"] is False
    assert result["by_family"]["threshold_boundary"]["failed"] > 0


# --- family (b): state micro-paths ---------------------------------------

def test_PACK6b_an_evaluator_that_never_arms_fails_the_proof(monkeypatch, pack):
    monkeypatch.setattr(lp.ch, "run_c1",
                        lambda path: ch.C1Run(readings=(), episodes=(), events=()))
    result = lp.build_inversion_proof(pack)
    assert result["by_family"]["state_micro_path"]["failed"] > 0
    assert result["pass"] is False


def test_PACK6b_the_micro_paths_drive_the_real_evaluator(proof):
    cases = {c["case"] for c in _family(proof, "state_micro_path")}
    assert any(c.endswith(":c1_arm:below") or c.endswith(":c1_arm:bracket_low")
               for c in cases), cases


# --- family (c): re-arm ---------------------------------------------------

def test_PACK6c_a_broken_rearm_rule_fails_the_proof(monkeypatch, pack):
    monkeypatch.setattr(lp.ch, "rearm_eligible", lambda ks, elapsed: True)
    result = lp.build_inversion_proof(pack)
    assert result["by_family"]["rearm"]["failed"] > 0


def test_PACK6c_the_rearm_boundaries_are_probed_on_both_sides(proof):
    cases = {c["case"] for c in _family(proof, "rearm")}
    assert {"k_at_floor", "k_just_above_floor", "sessions_below_cap",
            "sessions_at_cap", "sessions_above_cap"} <= cases


# --- family (d): c2f rebound ---------------------------------------------

def test_PACK6d_a_moved_atr_multiple_fails_the_proof(monkeypatch, pack):
    monkeypatch.setattr(ch, "C2F_ATR_MULTIPLE", 0.9)
    result = lp.build_inversion_proof(pack)
    assert result["by_family"]["c2f_rebound"]["failed"] > 0
    # The FROZEN spec is untouched by the runtime monkeypatch — the proof caught a
    # behaviour change, not a spec edit.
    assert ch.C2_SPEC["rebound_atr_multiple"] == 0.5


def test_PACK6d_a_missing_atr_is_null_never_false(proof):
    cases = {c["case"]: c for c in _family(proof, "c2f_rebound")}
    assert cases["atr_missing_is_null"]["expected"] is None
    assert cases["atr_non_positive_is_null"]["expected"] is None
    assert cases["rebound_at_threshold"]["expected"] is True


# --- family (e): the C3 turn predicate -----------------------------------

def test_PACK6e_a_broken_turn_predicate_fails_the_proof(monkeypatch, pack):
    monkeypatch.setattr(lp, "four_hour_turn", lambda series: True)
    result = lp.build_inversion_proof(pack)
    assert result["by_family"]["c3_turn"]["failed"] > 0


def test_PACK6e_the_warmup_is_null_never_false(proof):
    cases = {c["case"]: c for c in _family(proof, "c3_turn")}
    assert cases["warmup_is_null"]["observed"] is None


# --- family (f): the basis tolerance -------------------------------------

def test_PACK6f_a_broken_basis_audit_fails_the_proof(monkeypatch, pack):
    monkeypatch.setattr(lp, "basis_audit",
                        lambda *a, **k: {"mismatch": True, "gap_pct": 0.0})
    result = lp.build_inversion_proof(pack)
    assert result["by_family"]["basis_tolerance"]["failed"] > 0


def test_PACK6f_the_tolerance_boundary_passes_and_a_hair_past_it_refuses():
    anchor = 100.0
    tol = lp.BASIS_TOLERANCE_PCT
    assert lp.basis_audit(anchor, anchor * (1 - tol / 100.0))["mismatch"] is False
    assert lp.basis_audit(anchor, anchor * (1 - (tol + 1e-4) / 100.0))["mismatch"] is True


def test_PACK6f_an_unavailable_basis_is_null_never_false():
    audit = lp.basis_audit(100.0, None)
    assert audit["mismatch"] is None
    assert audit["reason"] == "basis_unavailable"


def test_PACK6f_the_audit_carries_its_own_numbers():
    audit = lp.basis_audit(100.0, 99.0)
    assert audit["gap_pct"] == pytest.approx(1.0)
    assert audit["tolerance_pct"] == lp.BASIS_TOLERANCE_PCT
    assert audit["as_of_close"] == 100.0 and audit["prev_close"] == 99.0


def _family(proof: dict, family: str) -> list[dict]:
    """Every case of one family — re-derived from the proof's own records."""
    return [c for c in _all_cases(proof) if c["family"] == family]


def _all_cases(proof: dict) -> list[dict]:
    """A healthy proof reports only failures, so re-run to enumerate the cases."""
    return _CASE_CACHE


_CASE_CACHE: list[dict] = []


@pytest.fixture(scope="module", autouse=True)
def _populate_case_cache(pack):
    """Enumerate every proof case once, for the by-family shape assertions."""
    _CASE_CACHE.clear()
    _CASE_CACHE.extend(
        lp._proof_threshold_cases(pack)
        + lp._proof_micro_path_cases(date.fromisoformat(pack.next_session))
        + lp._proof_rearm_cases() + lp._proof_c2f_cases()
        + lp._proof_c3_turn_cases() + lp._proof_basis_cases())
    return _CASE_CACHE


def test_PACK6_every_enumerated_case_carries_the_full_record():
    for case in _CASE_CACHE:
        assert set(case) == {"family", "case", "boundary", "direction", "expected",
                             "observed", "pass"}
        assert case["pass"] is True, case


# ---------------------------------------------------------------------------
# PACK-7 — persistence
# ---------------------------------------------------------------------------

def test_PACK7_save_then_load_roundtrips_the_pack(tmp_path, pack, proof):
    saved = pack.with_proof(proof)
    lp.save_pack(saved, tmp_path)
    got = lp.load_pack(tmp_path)
    assert got is not None
    assert got.as_of == saved.as_of and got.pack_hash == saved.pack_hash
    assert [n.ticker for n in got.names] == [n.ticker for n in saved.names]
    for row, original in zip(got.names, saved.names):
        assert row.to_dict() == original.to_dict()
    for ticker, frame in saved.substrate.items():
        # ``check_index_type=False``: parquet round-trips the datetime index at a
        # different RESOLUTION (us vs s).  The session DATES are compared exactly
        # below; the storage unit is not a property of the substrate.
        pd.testing.assert_frame_equal(
            got.substrate[ticker].astype(float), frame.astype(float),
            check_freq=False, check_names=False, check_index_type=False)
        assert list(pd.DatetimeIndex(got.substrate[ticker].index).date) == \
               list(pd.DatetimeIndex(frame.index).date)
    assert got.proof is not None and got.proof["pass"] is True


def test_PACK7_the_pointer_is_a_file_and_names_the_hash(tmp_path, pack):
    lp.save_pack(pack, tmp_path)
    pointer = json.loads(lp.pointer_path(tmp_path).read_text(encoding="utf-8"))
    assert pointer["as_of"] == pack.as_of
    assert pointer["pack_hash"] == pack.pack_hash
    assert not lp.pointer_path(tmp_path).is_symlink()


def test_PACK7_no_partial_directory_survives_a_save(tmp_path, pack):
    lp.save_pack(pack, tmp_path)
    strays = [p.name for p in lp.pack_root(tmp_path).iterdir()
              if p.name.startswith(".")]
    assert strays == [], strays


def test_PACK7_retention_keeps_the_newest_three_and_never_the_pointer_target(tmp_path,
                                                                            pack):
    for offset, session in enumerate(("2026-08-10", "2026-08-11", "2026-08-12",
                                      "2026-08-13", "2026-08-14")):
        copy = lp.LivePack(
            schema=pack.schema, as_of=session, next_session=pack.next_session,
            built_at=pack.built_at, price_basis=pack.price_basis,
            spec_hashes=pack.spec_hashes, probe_set=pack.probe_set, names=pack.names,
            substrate=pack.substrate, pack_hash=f"{offset:016x}")
        lp.save_pack(copy, tmp_path)
    kept = sorted(p.name for p in lp.pack_root(tmp_path).iterdir() if p.is_dir())
    assert kept == ["2026-08-12", "2026-08-13", "2026-08-14"]
    assert lp.load_pack(tmp_path).as_of == "2026-08-14"


def test_PACK7_load_returns_None_when_there_is_no_pack(tmp_path):
    assert lp.load_pack(tmp_path) is None


def test_PACK7_pack_is_fresh_uses_the_INJECTED_clock(pack):
    fresh_now = datetime(2026, 8, 14, 22, 0, tzinfo=timezone.utc)   # after the close
    stale_now = datetime(2026, 8, 18, 22, 0, tzinfo=timezone.utc)
    assert lp.pack_is_fresh(pack, fresh_now) is True
    assert lp.pack_is_fresh(pack, stale_now) is False
    assert lp.pack_is_fresh(None, fresh_now) is False


def test_PACK7_the_manifest_is_strict_json(tmp_path, pack, proof):
    lp.save_pack(pack.with_proof(proof), tmp_path)
    body = (lp.pack_root(tmp_path) / pack.as_of / "manifest.json").read_text("utf-8")
    json.loads(body)  # raises on NaN/Infinity, which json.dumps(allow_nan=False) blocks
    assert "NaN" not in body and "Infinity" not in body


# ---------------------------------------------------------------------------
# PACK-8 — the W4/W5 firewall + the module fences
# ---------------------------------------------------------------------------

#: Shapes that would require knowing what happened AFTER an observation.
_FORWARD_TOKENS = ("forward_return", "fwd_return", "mfe", "mae", "hit_rate",
                   "win_rate", "grade", "outcome", "pnl", "excess_vs")


def _keys(node, out):
    if isinstance(node, dict):
        for key, value in node.items():
            out.add(str(key).lower())
            _keys(value, out)
    elif isinstance(node, list):
        for value in node:
            _keys(value, out)


def test_PACK8_no_manifest_key_needs_post_observation_knowledge(pack, proof):
    keys: set[str] = set()
    _keys(pack.with_proof(proof).manifest(), keys)
    offenders = sorted(k for k in keys
                       if any(tok in k for tok in _FORWARD_TOKENS))
    assert offenders == [], offenders


def test_PACK8_CONTROL_the_forward_scanner_catches_a_planted_key():
    keys: set[str] = set()
    _keys({"names": [{"forward_return_10d": 0.1}]}, keys)
    assert any(tok in k for k in keys for tok in _FORWARD_TOKENS)


def test_PACK8_no_score_shaped_key_reaches_the_manifest(pack, proof):
    keys: set[str] = set()
    _keys(pack.with_proof(proof).manifest(), keys)
    banned = ("score", "strength", "conviction", "opportunity")
    assert sorted(k for k in keys if any(t in k for t in banned)) == []


@pytest.mark.parametrize("name", W4_BUILDER_A_MODULES)
def test_PACK8_no_w4_module_names_a_data_path(name):
    tree = ast.parse((RADAR_DIR / name).read_text(encoding="utf-8"))
    literals = [n.value for n in ast.walk(tree)
                if isinstance(n, ast.Constant) and isinstance(n.value, str)]
    offenders = [s for s in literals
                 if s.startswith("data/") or "/data/" in s or s == "data"]
    assert offenders == [], offenders


@pytest.mark.parametrize("name", W4_BUILDER_A_MODULES)
def test_PACK8_no_w4_module_imports_a_protected_module(name):
    protected = ("engine.technicals", "engine.entry_signal", "engine.signal_gate",
                 "engine.confluence_tiers", "engine.signal_quality",
                 "engine.washout_turn", "engine.mtf_upturn", "engine.prophet_",
                 "signal_layer")
    tree = ast.parse((RADAR_DIR / name).read_text(encoding="utf-8"))
    seen: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            seen += [a.name for a in node.names]
        elif isinstance(node, ast.ImportFrom) and node.module:
            seen.append(node.module)
    offenders = [m for m in seen if any(m.startswith(p) for p in protected)]
    assert offenders == [], offenders


@pytest.mark.parametrize("name", W4_BUILDER_A_MODULES)
def test_PACK8_the_guard_file_list_points_at_real_files(name):
    assert (RADAR_DIR / name).is_file()


def test_PACK8_the_pack_reads_no_wall_clock(pack):
    """``as_of``, ``built_at`` and ``now`` are arguments, never ``datetime.now()``."""
    tree = ast.parse((RADAR_DIR / "live_pack.py").read_text(encoding="utf-8"))
    offenders = [
        ast.unparse(node) for node in ast.walk(tree)
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
        and node.func.attr in ("now", "utcnow", "today")
    ]
    assert offenders == [], offenders


def test_PACK8_the_probe_set_snapshot_summarises_admission_without_ranking():
    snapshot = lp.probe_set_snapshot({
        "market_session": "2026-08-14",
        "records": [
            {"ticker": "AAA", "admission_layers": ["B"],
             "admission_reasons": [{"reason_code": "index.sp500"}]},
            {"ticker": "BBB", "admission_layers": ["C", "D"],
             "admission_reasons": [{"reason_code": "hot_tape.move"},
                                   {"reason_code": "index.sp500"}]},
        ]})
    assert snapshot["source"] == "probe_set"
    assert snapshot["tickers"] == ["AAA", "BBB"]
    assert snapshot["admission"]["layers"] == {"B": 1, "C": 1, "D": 1}
    assert snapshot["admission"]["reason_codes"] == {"hot_tape.move": 1,
                                                     "index.sp500": 2}
    assert snapshot["market_session"] == "2026-08-14"


def test_PACK8_a_bare_ticker_sequence_is_accepted_and_labelled():
    snapshot = lp.probe_set_snapshot(["ZZZ", "AAA", "ZZZ"])
    assert snapshot["source"] == "ticker_sequence"
    assert snapshot["tickers"] == ["AAA", "ZZZ"]
    assert snapshot["count"] == 2


def _admission(layer: str, code: str) -> AdmissionReason:
    return AdmissionReason(layer=layer, source_id="test.src",
                           reason_code=code, reason_text=code)


def _record(ticker: str, layers: tuple[str, ...],
            codes: tuple[str, ...]) -> ProbeRecord:
    return ProbeRecord(
        ticker=ticker,
        admission_layers=layers,
        admission_reasons=tuple(_admission(layers[0], code) for code in codes),
        eligibility="operating_equity",
    )


def _probe_set(*records: ProbeRecord) -> ProbeSet:
    return ProbeSet(
        records=records,
        assembled_at=datetime(2026, 8, 18, tzinfo=timezone.utc),
        market_session="2026-08-18",
        budget={"state": "ok"},
    )


def test_PACK8_a_real_probe_set_snapshot_keeps_every_ticker():
    """Production collapse: live ProbeSet.records → to_dict()['probes'], adapter read 'records'."""
    probe_set = _probe_set(
        _record("BBB", ("C", "D"), ("hot_tape.move", "index.sp500")),
        _record("AAA", ("B",), ("index.sp500",)),
    )
    dumped = probe_set.to_dict()
    snapshot = lp.probe_set_snapshot(probe_set)
    serialized = lp.probe_set_snapshot(dumped)
    assert dumped["probes"] and "records" not in dumped
    assert snapshot["tickers"] == ["AAA", "BBB"]
    assert snapshot["count"] == 2
    assert snapshot["source"] == "probe_set"
    assert snapshot["market_session"] == "2026-08-18"
    assert snapshot["admission"]["layers"] == {"B": 1, "C": 1, "D": 1}
    assert snapshot["admission"]["reason_codes"] == {"hot_tape.move": 1,
                                                     "index.sp500": 2}
    assert snapshot == serialized


def test_PACK8_a_nonempty_probe_set_must_not_silently_collapse_to_zero_tickers():
    assert lp.probe_set_snapshot(_probe_set())["tickers"] == []
    blank = _probe_set(_record("", ("B",), ("index.sp500",)))
    with pytest.raises(lp.LivePackError, match="collapsed"):
        lp.probe_set_snapshot(blank)
    with pytest.raises(lp.LivePackError, match="collapsed"):
        lp.probe_set_snapshot({"probes": [{"ticker": "", "admission_layers": ["B"]}]})


def test_PACK8_build_pack_requests_every_real_probe_set_ticker():
    probe_set = _probe_set(
        _record("WASH", ("B",), ("index.sp500",)),
        _record("FLAT", ("C",), ("hot_tape.move",)),
    )
    requested: list[str] = []
    frames = store()

    def spy(ticker: str):
        requested.append(ticker)
        return frames.get(ticker)

    lp.build_pack(
        probe_set=probe_set, store_reader=spy, as_of=AS_OF,
        built_at=datetime(2026, 8, 15, 2, 0, tzinfo=timezone.utc),
    )
    assert requested == ["FLAT", "WASH"]


def test_PACK8_next_reference_session_is_calendar_not_arithmetic():
    # 2026-08-15/16 is a weekend: the next session after Friday is Monday.
    assert lp.next_reference_session(date(2026, 8, 14)) == date(2026, 8, 17)
    assert lp.next_reference_session(date(2026, 8, 17)) == date(2026, 8, 18)


def test_PACK8_the_atr_is_the_house_atr_on_the_frozen_frame(pack):
    frame = pack.substrate["WASH"]
    expected = ic.last_finite(ic.atr14(frame["high"], frame["low"], frame["close"]))
    assert pack.by_ticker()["WASH"].atr14_prior_confirmed == expected


def test_PACK8_the_confirmed_kd_are_the_canonical_stochrsi(pack):
    frame = pack.substrate["WASH"]
    k_series, d_series = ic.stoch_rsi_kd(frame["close"].astype(float))
    row = pack.by_ticker()["WASH"]
    assert row.confirmed_k == ic.last_finite(k_series)
    assert row.confirmed_d == ic.last_finite(d_series)
