"""
tests/test_signal_bus_doc.py — Freshness gate + determinism + coverage tests for SIGNAL_BUS.md.

(a) Regenerating into a temp file yields EXACTLY the committed bytes — the doc cannot drift
    from the registry.
(b) Determinism: two consecutive generate() calls return identical strings.
(c) All registered artifact ids appear in the generated content.
(d) Mermaid block is syntactically plausible: balanced backtick fences and starts 'flowchart'.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest
import yaml

# ---------------------------------------------------------------------------
# Locate repo root and import the generator
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SYNAPSE_YML = _REPO_ROOT / "config" / "synapse.yml"
_COMMITTED_DOC = _REPO_ROOT / "docs" / "SIGNAL_BUS.md"

# Import the generator function directly
import importlib.util, sys

_spec = importlib.util.spec_from_file_location(
    "gen_signal_bus_doc",
    _REPO_ROOT / "scripts" / "gen_signal_bus_doc.py",
)
_mod = importlib.util.module_from_spec(_spec)  # type: ignore[arg-type]
_spec.loader.exec_module(_mod)  # type: ignore[union-attr]
generate = _mod.generate


# ---------------------------------------------------------------------------
# (a) Freshness gate — regenerated bytes must match committed doc exactly
# ---------------------------------------------------------------------------


def test_signal_bus_doc_is_fresh():
    """Regenerating docs/SIGNAL_BUS.md must yield byte-for-byte identical content."""
    committed = _COMMITTED_DOC.read_text(encoding="utf-8")
    regenerated = generate(_SYNAPSE_YML)
    assert regenerated == committed, (
        "docs/SIGNAL_BUS.md is out of date with config/synapse.yml.\n"
        "Run: python -m scripts.gen_signal_bus_doc\n"
        f"First diff at char {next(i for i,(a,b) in enumerate(zip(regenerated,committed)) if a!=b) if len(regenerated)==len(committed) else 'lengths differ: {} vs {}'.format(len(regenerated),len(committed))}"
    )


# ---------------------------------------------------------------------------
# (b) Determinism — two runs must be identical
# ---------------------------------------------------------------------------


def test_signal_bus_doc_deterministic():
    """Two consecutive generate() calls must return identical strings."""
    first = generate(_SYNAPSE_YML)
    second = generate(_SYNAPSE_YML)
    assert first == second, "generate() is not deterministic — output differs between calls."


# ---------------------------------------------------------------------------
# (c) All artifact ids appear in the content
# ---------------------------------------------------------------------------


def test_all_artifact_ids_present():
    """Every artifact id registered in synapse.yml must appear in the generated doc."""
    with _SYNAPSE_YML.open(encoding="utf-8") as fh:
        registry = yaml.safe_load(fh)
    artifact_ids = list(registry.get("artifacts", {}).keys())
    assert len(artifact_ids) == 645, (
        f"Expected 645 artifacts in synapse.yml, found {len(artifact_ids)}. "
        "Update the test if the registry count changed intentionally."
        " (Grey Deer GD-2 registered risk-envelope-settled — the settled"
        " mastermind.risk_envelope/v1 projection composed by engine/risk_envelope.py;"
        " weights=none because the composer selects and carries source-native states"
        " and mints no new weighted number; birth authority descriptive-only, all"
        " authority booleans hard-false = 644->645);"
        " (AD-1 registered options-intel-brief — the Daily EOD Options Intelligence"
        " Brief display-tier research-priority artifact; sole consumer is the Options"
        " Workspace; zero Prophet/NW/Sector consumers by design = 643->644);"
        " (GMI W3A registered theme-graph-capability — the nightly re-derived"
        " capability side-car, display tier, all six authority booleans false"
        " = 642->643);"
        " (Options signal campaign v2 registered canonical revision, anchored"
        " outcome, and exact-prefix checkpoint artifacts = 639->642);"
        " (GMI W1b theme-graph spine registered the nodes, edges, and evidence"
        " product-data-plane stores, all six authority booleans false = 636->639);"
        " (Options signal campaigns registered the immutable zero-authority"
        " exact-contract research-cohort ledger = 635->636);"
        " (Release Radar CPI truth registered the preregistered sample, official"
        " archive, receipts, collection manifest, coherent target history, parity"
        " report, completion boundary, and official-actual defect sidecar = 627->635);"
        " (TOP ANATOMY W1 registered top-maturation-latest — the nightly Winner"
        " Health maturation read, display tier with zero authority. Both this lane"
        " and the VIXCLS receipt below independently pinned 625->626 while in"
        " flight; the merge carries BOTH registrations, so the reconciled count is"
        " 626->627 — the racing-merge pin drift this list has recorded before);"
        " (Price Pressure registered immutable VIXCLS stamp-completion receipts"
        " = 625->626);"
        " (Price Pressure registered its current display projection and immutable"
        " point-in-time event ledger = 623->625);"
        " (Government Revenue registered the exact append-only issuance correction"
        " control for the eight-row 5fc incident = 622->623);"
        " (Government Revenue registered the operator-reviewed, exact-source"
        " historical non-issuance control = 621->622);"
        " (Blocked-entry override registered site-basket-washout-history — the per-notch"
        " retro-marking intervals sibling of the state artifact, same builder and step"
        " = 620->621);"
        " (Options signal episodes registered a separate immutable"
        " EOD/1d/3d/5d/10d session-outcome ledger = 619->620);"
        " (Blocked-entry A1b display support registered the nightly, display-only"
        " basket washout state artifact = 618->619);"
        " (Private Options Issue Desk registered separate operator-only append-only"
        " proposal and decision ledgers = 616->618);"
        " (Filing Forensics offrender-lane heal, deferred from #4986, registered"
        " fundamental-forensics-disclosure-bundle — the scheduled SEC lane's published"
        " render input; current main carried 615 artifacts while this pin still said"
        " 607, so the reconciled count is 615->616);"
        " (Government Revenue SBIR progression registered five observation,"
        " receipt, projection, status, and heartbeat artifacts; Release Radar"
        " registered target vintages, official actuals, and inflation context"
        " = 607->615);"
        " (Options Prophet shadow registered its display-only projection,"
        " signing-quality context gate, and dislocation research gate = 604->607);"
        " (Polygon intraday price cache registered the receipt-bound H+60 input"
        " consumed by the outcome builder = 603->604);"
        " (Polygon intraday price receipt registered the causal cache sidecar"
        " consumed by H+60 accrual = 602->603);"
        " (Dated live-flow PIT event stage registered as the episode builder's"
        " critical R2 source = 601->602);"
        " (Options signal episode durable-stage checkpoint = 600->601);"
        " (Options signal episodes registered the immutable PIT decision ledger"
        " and append-only H+60 outcome ledger = 598->600);"
        " (Prophet-US W1-D added us-basket-turn + us-basket-turn-ledger — the US"
        " washout-lifecycle organ, port of china_basket_turn = 595->597;"
        " Biopharma Seasonality program watch then registered"
        " data-seasonality-program-watch, the operator-facing tripwire = 597->598);"
        " (pin drifted: registry carried 595 while pin said 594 — racing merges during the"
        " 2026-08-05/06 Prophet-US + CN wave trains; repaired here);"
        " (CN Prophet W-C registered the loser/miss telemetry artifact + its forward"
        " log, the CN episode track ledger, and the two PIT basket-membership"
        " histories = 588->593; (pin drifted during the W-C rebase: a racing merge"
        " added one registration while W-C carried its five — repaired here = 594;"
        " (Biopharma Seasonality Lane 6 added the Neural Web shadow state and its"
        " append-only forward outcome ledger = 586->588;"
        " (Government Revenue Wave9A candidate foundation added candidate ledger,"
        " queue, projection state, projection status, and public queue artifacts = 581->586;"
        " (Earnings Evidence Spine Wave 2 added the protected exact-evidence"
        " context catalog = 580->581;"
        " (Capital Structure authenticated share-count materialization added ledger,"
        " current-pointer, signed-receipt, and external-head artifacts = 576->580;"
        " (Capital Structure Company Facts intake added coverage, receipt, source-manifest,"
        " and current-pointer artifacts = 572->576;"
        " (Government Revenue Foresight Wave 6 added subaward snapshots, receipts,"
        " activation state, ingest status, heartbeat, and canonical/public dossiers = 562->569;"
        " (Capital Structure Wave 2C added the retrieval-queue fairness receipt = 561->562;"
        " (Government Revenue Foresight recipient activation added the reviewed"
        " exact-ID graph and independent resolution coverage = 559->561;"
        " (Government Revenue Foresight Wave 5 added canonical and public"
        " dossier artifacts = 557->559;"
        " Stock Seasonality calendar clock + review-findings pass carry it to 565;"
        " (Capital Structure Wave 2B added capital-structure-document-term-observations = 556->557;"
        " (Government Revenue Foresight Wave 4 added receipt-bound award-event snapshot,"
        " action-version, and activation-state artifacts = 553->556;"
        " (Capital Structure Wave 2A added canonical and public observed-filing-state"
        " projections = 551->553;"
        " (Government Revenue Foresight W2 added USAspending hash-only collection receipt = 550->551;"
        " (Government Revenue Foresight W2 added SAM current/revision/document/status/heartbeat"
        " and canonical/site workspace artifacts = 543->550;"
        " (Filing Forensics Wave 2 added fundamental-forensics-sec-source-snapshot = 542->543;"
        " (Chronicle earnings-call bridge added chronicle-earnings-call-events = 541->542;"
        " (Capital Structure Intelligence W0-W1 added discovery, index-coverage,"
        " retrieval-attempts, source-manifest, event-versions, event-edges,"
        " review-queue, telemetry = 533->541;"
        " (Biopharma Seasonality foundation added site-biopharma-seasonality-methodology = 532->533;"
        " (Filing Forensics v1 added fundamental-forensics-private-state = 531->532;"
        " (Government Revenue Foresight W1 added entity, award, action, snapshot,"
        " ingest-status, heartbeat, engine-payload, and site-payload artifacts = 523->531;"
        " (Crypto Cockpit W3 added btc-options, crypto-asset-states,"
        " crypto-class-state = 520->523;"
        " (OIP E3 positioning persistence promoted the per-strike chain snapshots to a"
        " registered nerve: polygon-gex-chains = 519->520;"
        " (OIP E1 session digest added live-flow-surface-dated, live-flow-tide-dated,"
        " live-flow-dte-tide-dated, options-session-records, options-session-latest,"
        " options-session-ledger = 513->519;"
        " (Crypto Cockpit W0 added crypto-cockpit = 512->513;"
        " (china W3 #3844 added site-china-calendar = 511->512;"
        " (PSS-RH1 prospective hazard added frozen manifest + membership + ledger + state = 507->511;"
        " (PSS-F4H serving added terminality model manifest + 2 tree payloads + ledger + state = 502->507;"
        " (china_native W2 added china-funding-store, china-cb-store, china-fund-issuance-store = 499->502;"
        "(Chronicle W0 added chronicle-events, chronicle-state-log, chronicle-manifest = 496->499;"
        "(PSS-W3 added personality-gate-shadow-ledger, personality-gate-shadow-state = 494->496;"
        "(TXI W4 #3527 added transmission-chains-state = 493->494;"
        "(Personality Codex W2 #3460 added personality-timing-codex = 492->493;"
        "(MWR-W1 added shadow-book, shadow-state, prophet-confluence = 489->492;"
        "(MWR-W0 added mag7-washout-latest, mag7-washout-triggers = 487->489;"
        "(Darkpool lobe #3314 added darkpool-context-latest = 486->487;"
        "(SGA W2 added stage-analysis-context-latest = 485->486;"
        "(RIC-W7 added rates-command-latest = 484->485;"
        "(Marketing lobe added marketing-state, marketing-lobe = 482->484;"
        "(MSP W1 added market-structure-latest, market-structure-history,"
        " market-structure-ledger = 479->482;"
        "(Prophet W2 added prophet-status, prophet-suggestions, prophet-pick-autopsies = 476->479;"
        "(SS-NW-W1 added special-sits-context-latest = 475->476;"
        "(FWS B4 added site-factor-seasonality, site-momentum-display = 473->475;"
        "(CA-W3-E added crossasset-history, crossasset-shadow-latest = 471->473;"
        "(Prophet W1 added us-track-history = 470->471;"
        "(RIC-W4 EVW added event-windows-forward-log, event-windows-snapshot = 468->470;"
        "(RIC-W3 added opex-risk-snapshot, opex-windows-forward-log = 466->468;"
        "(RIC-W2 added options-surface-index-etf, options-surface-sector-etf,"
        " options-surface-industry-etf = 463->466;"
        "(CSP-W1 added rsr-leadership-crack-latest, rsr-deterioration-cascade-latest,"
        " risk-radar-intl-forward-logs = 460->463;"
        "(E1 audit 2026-07-17: 5 site-mirror registrations"
        " site-confluence-graph, site-kernel-families, site-kernel-half-lives,"
        " site-liquidity-plumbing, site-cortex-memo = 455->460;"
        " XSR-R2 us-sector-rotation-latest = 454->455 (was never pinned);"
        "(sector-central site-payload registration added site-sector-central,"
        " site-china-sector-central = 452->454;"
        "(MLC-W2b added site-stance-matrix = 451->452;"
        "(CCW-W3 added ccw-credit-momentum-json, ccw-forward-log = 449->451;"
        "(CCW-W2 #2556 added ccw-issuer-daily, ccw-theme-daily, ccw-sector-daily,"
        " ccw-market-daily, ccw-maturity-wall, ccw-bond-panel-latest,"
        " ccw-latest-json, ccw-validation-json = 441->449;"
        "(risk-radar self-monitoring #2518 added data-risk-radar-scorecard,"
        " site-riskdata-scorecard = 439->441;"
        "(CBF W2 added cbf-flow-regime-latest, cbf-flow-regime-history = 437->439;"
        "(W-AI orchestrator face added neuralweb-orchestrator-runlog,"
        " site-neuralweb-orchestrator-runlog = 435->437;"
        " (RC-R14 HK added site-marketdata-rotation-events-hk,"
        " data-rotation-events-hk-ledger = 433->435;"
        " (LHB-W3 A2 pilot added edgar-statements-quarterly, pricing-power-states,"
        " pricing-power-manifest = 430->433;"
        " (LHB-W3 A1 packet added long-hold-falsifier-packets,"
        " long-hold-falsifier-packets-manifest = 428->430;"
        " (SA-W5 v2 grader hook added us-board-ledger-snapshots-v2,"
        " us-board-ledger-retro-grades-v2, us-board-track-v2 = 425->428;"
        " (SA-W2 CN foundations added china-regime-pit-daily,"
        " china-standout-cn-attribution, china-standout-cn-evidence,"
        " china-standout-cn-audit-scoreboard, china-standout-cn-audit-state,"
        " china-standout-cn-fitness = 419->425;"
        " (SA-W1 standout accountability added us-standout-attribution,"
        " us-standout-evidence, us-audit-scoreboard, us-standout-fitness-card,"
        " us-standout-audit-state = 414->419;"
        " (IRD-W2 added ird-intl-risk-latest = 413->414;"
        " (RC-R14 China port added site-marketdata-rotation-events-china,"
        " data-rotation-events-china-ledger = 411->413;"
        " (LHB-W2c symbol-directory archival added long-hold-symbol-directory = 410->411;"
        " (White House Treasury Watch added treasury-watch = 409->410;"
        " (RC deep-integration added site-marketdata-rotation-events,"
        " data-rotation-events-ledger, site-marketdata-subsector-confluence = 406->409;"
        " (LHB-W1 A3 Delivery Waterfall added long-hold-delivery-waterfall,"
        " long-hold-delivery-waterfall-panel = 404->406;"
        " (RLT-R2 added rebalance-pulse-events, rebalance-pulse-latest,"
        " rebalance-pulse-site = 401->404;"
        " (FL-B flow-cohorts added options-flow-cohorts-parquet,"
        " options-flow-cohorts-json = 391->393;"
        " (mag7-regime engine Lane C added mag7-regime-latest, mag7-regime-site,"
        " mag7-regime-ledger = 388->391;"
        " (NW W4 'the eye' added confluence-strength, confluence-tape,"
        " confluence-sequence, confluence-candidates = 384->388;"
        " (leader-radar W2a fix-round declared rs-series-store, leader-radar-revisions-history"
        " = 382->384;"
        " (leader-radar W2a added site-leader-radar, leader-radar-state-history"
        " = 380->382;"
        " (RL W1 #2240 added oracle-ratio-lens-feed, oracle-ratio-lens-ledger"
        " = 378->380 — pin catch-up rode in #2242, missed in the RL W1 merge;"
        " (IGN WB added ignition-radar-latest, ignition-log-us = 376->378;"
        " (FL W2 added site-flow-leaders, site-flow-leaders-page = 374->376;"
        " NW read layer added neuralweb-market-plane, site-neuralweb-market-plane,"
        " site-neuralweb-health-history, site-neuralweb-governance-recent,"
        " fred-wresbal = 369->374;"
        " (IFT added intraday-flow-base, intraday-flow-pulse,"
        " intraday-flow-ledger = 366->369;"
        " (SF Lane D added signal-foundry-candidates, signal-foundry-results,"
        f" signal-foundry-forward, signal-foundry-lane-status = 362->366;"
        " (Metabolism V2-B unit-6 added metabolism-build-claims = 361->362;"
        " (Metabolism V2-C added lobe-charters+lifecycle+authority-audit artifacts = 357->361;"
        " (NAR-W3 review fixes added narrative-first-coverage, stock-narrative-witness-history = 350->353"
        " (includes 1 artifact from other PRs merged during rebase);"
        " NAR-W3 added stock-narrative-flares = 349->350;"
        " NAR-W1 added stock-flare-persistence, stock-flare-persistence-history = 347->349;"
        " Metabolism V2-A added metabolism-organism-state, metabolism-insight-bus,"
        " metabolism-agenda, metabolism-trajectory = 339->343;"
        " (Metabolism Phase A added metabolism-journal, metabolism-til-fitness,"
        " metabolism-verify, metabolism-budget-ledger, metabolism-digest = 334->339;"
        " Metabolism Phase 0 F3 added capability-manifest, capability-audit = 332->334;"
        " TIL W11 added theme-options-witness, site-options-witness — pin healed to actual 332 at merge;"
        " (TSU U2 added stock-mtf-upturn = 329->330;"
        " (TIL W10 added neuralweb-theme-clinical, site-clinical-pipeline = 327->329"
        " — pin healed post-merge; W10's rebase auto-merged the pin hunk without conflict"
        " and the stale pin rode in;"
        " (TIL W8 added neuralweb-theme-trade-flows, site-trade-flows = 325->327;"
        " TIL W9 added site-phrase-velocity, site-github-adoption, neuralweb-discovery-confluence = 322->325;"
        " CHF-W6 added causal-confluence-audit = 321->322;"
        " CHF-W5 added causal-brainstorm-runs, causal-llm-lane = 317->319;"
        " TIL W7 added dol-certs-store, hiring-velocity, site-hiring-intent = 314->317;"
        " FTR W9 fix-round added basket-turn-cohort-grades = 313->314;"
        " FTR W9 added basket-turn-cohort-claims-log, tape-disagreement-ledger = 311->313;"
        " tech-lab suite added site-factordata-tech-lab = 310->311;"
        " CHF-W3 added causal-edges, causal-nulls, causal-frontier,"
        " causal-surprise-queue, causal-lab-state, site-causal-lab-state = 304->310;"
        " FTR W4 added site-basket-turn-watch = 303->304;"
        " HK Pick Lab added hk-pick-lab-snapshots, hk-pick-lab-entry-ledger,"
        " hk-1d-velocity-desk-artifact = 300->303;"
        " (CN Pick Lab added cn-pick-lab-snapshots, cn-pick-lab-entry-ledger,"
        " cn-reversion-desk-artifact = 297->300;"
        " (Pick Lab added pick-lab-snapshots, pick-lab-entry-ledger,"
        " pick-lab-longhold-ledger = 294->297;"
        " (policy-shock W2-F added site-policy-lever = 293->294;"
        "(policy-shock W1-C added flip-confirmation-events, flip-confirmation-snapshot = 291->293;"
        "(policy-shock W2-E added shock-deescalation-firings,"
        " shock-deescalation-state = 289->291;"
        " PR-4 M2 added attention-deterministic + site-attention-deterministic = 287->289;"
        " PR-3 review-fix added nw-health-run-history = 286->287;"
        " PR-3 M3 escalation added ops-push-nw-health = 285->286;"
        " CHF-W4 added causal-mechanisms = 284->285;"
        " TIL PR-0 pre-registered theme-thesis-ledger, site-theme-thesis, theme-pathways,"
        " site-theme-pathways, theme-asymmetry, site-theme-asymmetry,"
        " foresight-earliness-grades, theme-placebo-tape, qledger-falsifier-evaluations"
        " = 275->284 (entries land before the W1/W2/W3/W6 producer lanes to avoid"
        " four-way synapse merge races);"
        " TIL W0 PR-A added theme-state, site-theme-state, theme-phase-history = 272->275;"
        " CHF-W1 added causal-feature-inventory = 271->272;"
        " liquidity-plumbing lobe added by neural-web registry build = 270->271;"
        " CN-SYS W6 spine added site-china-cycle-phase, site-china-market-state = 267->269;"
        " china-alpha registration gap fix added site-china-altdata-mastermind,"
        " site-china-altdata-by-ticker, site-china-altdata-feed = 264->267;"
        " nw-context-intelligence W4 added context-candidates = 263->264;"
        " nw-context-intelligence W3 added context-risk, site-context-risk = 261->263;"
        " R6 NW Cross-Asset Depth added crossasset-latest = 260->261;"
        " MRI PR-K added kalshi-releases-store = 245->246;"
        " B6 watchlist sentinel added watchlist-alerts-jsonl, watchlist-sentinel-states,"
        " watchlist-sentinel-cooldown = 223->226;"
        " W7b added machine-registry, cortex-attention-grades, cortex-probation = 104->107;"
        " W6b added ops-push-basket-freeze, ops-push-signal-sanity, ops-push-healthcheck = 107->110;"
        " signal bus registry now carries 112 artifacts;"
        " W3 event-intelligence added 6 event-priors artifacts = 112->118;"
        " Signal Commons W2 added kernel-half-lives = 118->119;"
        " entry-stack B0-1 added bottom-sensors-json, bottom-sensors-parquet = 119->121;"
        " options-nw W-A added options-entry-state, options-entry-gate, options-skew-snapshots,"
        " options-ivspread-snapshots, live-options-flow-current = 121->126;"
        " nwqs-B added research-queue = 126->127;"
        " gex-nerve added gex-state-history = 127->128;"
        " oracle reversion promo P0+P1 added oracle-reversion-forward-ledger, oracle-reversion-state = 128->130;"
        " long-hold W1 PR-E added long-hold-labels, long-hold-labels-manifest = 130->132;"
        " long-hold W1 dead-name build added long-hold-dead-name-prices = 132->133;"
        " OTA W6 turn desk added oracle-turn-desk, oracle-turn-desk-ledger = 133->135;"
        " long-hold W1 PR-F killtest added long-hold-killtest-results = 135->136;"
        " NW-rails PR-4 added dispersion-regime = 136->137;"
        " long-hold W2 PR-J two clocks added long-hold-clocks = 137->138;"
        " NW-rails PR-1 added rule-experiment-registry, rule-experiment-summaries = 141->143;"
        " NW-rails PR-6 added grading-closure = 143->144;"
        " long-hold W2 PR-I added long-hold-compounder-features = 144->145;"
        " long-hold W2 PR-K added moat-falsifier-sensors, great-company-trap = 145->147;"
        " NW-rails PR-8 added operator-action-ledger = 147->148;"
        " nw-mastermind-bridge W1 added kernel-decisions, neuralweb-mastermind-context,"
        " site-neuralweb-mastermind-context = 148->151;"
        " OTA W7 qualitative fusion added oracle-qual-filter-registry, oracle-qual-filter-stamps,"
        " oracle-qual-filter-accrual = 151->154;"
        " research-factory W1 added research-factory-candidates, research-factory-transitions,"
        " research-factory-paper-monitor = 154->157;"
        " factor-intel NW W1 added factor-intelligence-state, site-factor-intelligence-state,"
        " factor-state-history, fire-coordinates, factor-contradictions-ledger = 157->162;"
        " long-hold LT-2a added long-hold-expect-drift-manifest, long-hold-expect-drift-panel = 162->164;"
        " insider-LH panel build added insider-lh-panel, insider-lh-panel-manifest,"
        " insider-lh-ruler-p-results = 164->167;"
        " long-hold LT-3a added capital-allocation-delta = 167->168;"
        " SRSS Phase 2 added subsector-sponsorship-spine = 168->169;"
        " long-hold LT-2b added expect-drift-ruler-p-results = 169->170;"
        " long-hold LT-2c added long-hold-expectation-state = 170->171;"
        " PR-C nw-health added neuralweb-health, site-neuralweb-health = 171->173;"
        " china-intel W2 added site-china-special-sits = 173->174;"
        " SRSS revert (#1479 merged in race despite BLOCK-superseded review; §C3"
        " sponsorship_state in bottom_sensors.py is canonical) removed"
        " subsector-sponsorship-spine = 174->173;"
        " PR-D nw-daily-brief added neuralweb-daily-brief, site-neuralweb-daily-brief,"
        " neuralweb-daily-brief-history = 173->176;"
        " long-hold LT-1c added ticker-sectors = 176->177;"
        " (pin drifted: registry carried 180 while pin said 177 — racing merges; repaired here);"
        " CPI substrate v0 added cycle-pattern-entities, cycle-pattern-state-monthly,"
        " cycle-pattern-outcomes, cycle-pattern-truths, signal-archive-context-daily = 180->185;"
        " CPI P2 state_daily_live adapter added cycle-pattern-state-daily-live = 185->186;"
        " china-intel W4 added site-china-intel-command = 186->187;"
        " NW next-lobes DQ-2 operator-action grading harness added operator-grading = 187->188;"
        " short-side BD-AVOID-1 Phase-1 added bd-avoid1-ledger = 188->189;"
        " NEXT3 W-EX added operator-exposure-log, operator-exposure-summary = 189->191;"
        " (pin drifted: registry carried 198 while pin said 191 — racing merges; repaired here);"
        " DT-NW-1 added dt-contra-state = 198->199;"
        " R-ORTH PR-3 added covariance-spine, site-covariance-spine, covariance-spine-history = 199->202;"
        " CPI netliq artifact added fed-net-liquidity = 202->203;"
        " CPI IX-1 substrate added hazard-panel-index-v0 = 203->204;"
        " CPI P-D5-1 phase 4a added regime-v2-pit = 204->205;"
        " (pin drifted: registry carried 210 while pin said 205 — racing merges"
        " during the 2026-07-06 CPI wave train; repaired here);"
        " CPI P6 wave 1 added cycle-pattern-state = 210->211;"
        " active-build-map added active-builds = 211->212;"
        " feedback-contract W2 added site-mastermind-nw-feedback, mastermind-feedback-summary = 212->214;"
        " Ruling Graph v1 added site-neuralweb-ruling-graph = 214->215;"
        " ETM added entity-thesis-mechanism-registry = 215->216;"
        " evidence-clock PR-1 added evidence-clock, evidence-clock-reviews = 216->218;"
        " codex-docket event-landmine added event-windows = 218->219;"
        " NW core-cognition W1 added mechanism-pathways, mechanism-pathways-history, site-mechanism-pathways = 219->222;"
        " nasdaq-internals program added nasdaq-internals = 222->223;"
        " B6 watchlist sentinel added watchlist-alerts-jsonl, watchlist-sentinel-states,"
        " watchlist-sentinel-cooldown = 223->226;"
        " momoedge Wave 1 Package A (#1815) options sensor contract added"
        " options-structure-gex-state, options-flow-chain-heat, options-structure-matrix,"
        " options-structure-structural, prophet-trade-plan, prophet-management-state = 226->232;"
        " MRI PR-C added cleveland-nowcast-store, release-forecast-latest,"
        " release-forecast-ledger, release-forecast-scoreboard, site-release-forecast = 232->237;"
        " momoedge Package E strike-expiry matrix landed in a racing merge = 237->239;"
        " Winner Autopsy Lab (long-hold top-down department) added winner-episodes,"
        " winner-episodes-manifest, breakaway-watch-states, breakaway-watch-history,"
        " winner-autopsy-panel, winner-autopsy-manifest = 239->245;"
        " MRI PR-K added kalshi-releases-store = 245->246;"
        " nw-macro-rail R5 added forex-latest, transmission-latest, bond-health, commodity-latest,"
        " china-regime-latest, hk-regime-latest, canada-regime-latest, site-intelligence-briefing,"
        " site-factor-series, site-alerts-triage, macro-snapshots-latest, macro-snapshots-ledger,"
        " macro-transitions, macro-context-latest = 246->260;"
        " nw-context analyst feed added analyst-targets (yfinance targets/ratings context) = 269->270; leader-radar LRV-W1 declared sec-insider-quarterly = 396->397; IRD-W1 added imf-weo-store, ird-cb-calendar, fred-swpt, fred-wlcfll = 397->401)"
    )
    content = generate(_SYNAPSE_YML)
    missing = [aid for aid in artifact_ids if aid not in content]
    assert not missing, (
        f"The following artifact ids are missing from SIGNAL_BUS.md: {missing}"
    )


# ---------------------------------------------------------------------------
# (d) Mermaid block is syntactically plausible
# ---------------------------------------------------------------------------


def test_mermaid_block_plausible():
    """Mermaid code block must be balanced (open+close) and start with 'flowchart'."""
    content = generate(_SYNAPSE_YML)

    # Find all ```mermaid ... ``` blocks
    blocks = re.findall(r"```mermaid\n(.*?)```", content, re.DOTALL)
    assert blocks, "No ```mermaid``` block found in SIGNAL_BUS.md"

    for i, block in enumerate(blocks):
        stripped = block.strip()
        assert stripped.startswith("flowchart"), (
            f"Mermaid block {i} does not start with 'flowchart':\n{stripped[:120]}"
        )
        # Must have at least one edge line (-->)
        assert "-->" in stripped, (
            f"Mermaid block {i} contains no edges (-->):\n{stripped[:300]}"
        )

    # Verify backtick fences are balanced in the full document
    fence_count = content.count("```")
    assert fence_count % 2 == 0, (
        f"Odd number of backtick fences in SIGNAL_BUS.md ({fence_count}); "
        "at least one code block is unclosed."
    )
