"""Reviewed ZH replacements for ASCII-only ``.l-zh`` fallbacks.

Keyed by the exact English visible string. ``apply_zh_parity`` never uses a
regex wildcard: a missing key stays ASCII so the parity gate fails closed.
"""
from __future__ import annotations

from typing import Mapping

# Exact English → reviewed Chinese. Enumerated; no wildcard.
ZH_PARITY: dict[str, str] = {
    "N/a": "不适用",
    "Pct pts": "百分点",
    "Higher more expansionary": "数值越高＝越宽松",
    "Usd mn": "百万美元",
    "Owner native census": "所有者原生盘点",
    "Yoy pct change": "同比变化",
    "Higher more inflationary": "数值越高＝通胀压力越大",
    "Higher more restrictive": "数值越高＝越紧缩",
    "Usd millions sa": "百万美元（季调）",
    "Ratio 0 1": "比率（0–1）",
    "Constant maturity investment basis": "固定期限投资口径",
    "Higher accelerating": "数值越高＝加速越快",
    "Pp": "百分点",
    "Index pt": "指数点",
    "Pct saar": "年化百分比",
    "Issuers": "发行主体",
    "Owner disclosed unavailable": "所有者已披露为不可用",
    "Owner native categorical": "所有者原生分类",
    "Higher tightening impulse": "收紧脉冲更强",
    "Higher broader": "数值越高＝覆盖越广",
    "Pct yoy": "同比百分比",
    "Trailing 13w pct change": "过去13周百分比变化",
    "Trailing 13w level change": "过去13周水平变化",
    "Same date disciplined spread": "同日对齐利差",
    "Index pts": "指数点",
    "Leg level not separable": "分项水平无法拆分",
    "Persons thousands": "千人",
    "Seasonally adjusted not original vintage": "季调后（非原始版本）",
    "Deteriorating to accelerating": "从恶化到加速",
    "Weak to strong": "从弱到强",
    "Higher more persistent broad": "数值越高＝越持久、越广泛",
    "Level": "水平值",
    "Higher more accommodative": "数值越高＝越宽松",
    "Days": "日",
    "Higher easier funding": "数值越高＝融资越容易",
    "Events": "事件",
    "Thousands of units saar": "千套（年化季调）",
    "Higher more supply pipeline": "数值越高＝供给储备越多",
    "Single auction level": "单次拍卖水平",
    "Higher tighter policy stance": "数值越高＝政策立场越紧",
    "Realized reference rate": "已实现参考利率",
    "Index pts mom6": "指数点（6个月变化）",
    "Six month momentum": "6个月动能",
    "Pct legs positive": "上升分项占比",
    "Index 0 100": "指数（0–100）",
    "Z": "z 值",
    "Rebased 100 composite": "以100为基准的综合指数",
    "6m change": "6个月变化",
    "Ema of 6m change": "6个月变化的指数移动平均",
    "Share of legs rising 6m": "6个月内上升分项占比",
    "Sign of 6m momentum": "6个月动能方向",
    "Legs": "分项",
    "Higher broader input coverage": "数值越高＝输入覆盖越广",
    "Count of available legs": "可用分项数量",
    "Months": "月",
    "Year over year": "同比",
    "Realized policy rate": "已实现政策利率",
    "Market implied futures price not forecast": "市场隐含期货价格（不是预测）",
    "Higher more inflation priced": "数值越高＝定价的通胀越多",
    "Lower more imminent": "数值越低＝越临近",
    "Owner precomputed at cb desk build time": "央行台构建时预计算",
    "Standardized monetary contribution": "标准化货币贡献",
    "Standardized funding contribution": "标准化融资贡献",
    "Trailing 52w pct change": "过去52周百分比变化",
    "Units saar": "套数（年化季调）",
    "Higher more spending": "数值越高＝支出越多",
    "Usd billions sa": "十亿美元（季调）",
    "Higher more credit outstanding": "数值越高＝未偿信贷越多",
    "Higher faster credit growth": "数值越高＝信贷增长越快",
    "Bid to cover ratio": "投标倍数",
    "Positive is yields rising over 13w": "正值表示收益率在13周内上升",
    "Higher steeper curve": "数值越高＝曲线越陡",
    "Higher leg a trading rich to leg b": "数值越高＝A端相对B端越贵",
    "Leading tier index": "领先层指数",
    "Lagging tier index": "滞后层指数",
    "Lagging tier diffusion": "滞后层扩散",
    "Higher more risk": "数值越高＝风险越大",
    "Sahm rule value": "萨姆规则读数",
    "Persons": "人",
    "Higher looser": "数值越高＝越宽松",
    "Pct mom": "环比百分比",
    "Monthly proxy series": "月度代理序列",
    "Real 10y": "10年期实际收益率",
    "Usd billions": "十亿美元",
    "Roc 13w": "13周变化率",
    "Z score pts": "z 值点数",
    "Weekly change in expanding z score": "扩张 z 值的周变化",
    "Higher more coverage": "数值越高＝覆盖越广",
    "Higher more classified": "数值越高＝已分类越多",
    "Higher more restrictive financing": "数值越高＝融资越紧",
    "Higher more expensive": "数值越高＝越贵",
    "Higher more expensive rent": "数值越高＝租金越贵",
    "Higher more confident": "数值越高＝信心越强",
    "Higher more precautionary saving": "数值越高＝预防性储蓄越多",
    "Higher more delinquency stress": "数值越高＝拖欠压力越大",
    "Positive is tga building reserve draining negative is draining reserve injecting":
        "正值表示财政部现金增加、准备金被抽走；负值相反",
    "Higher more supply pressure": "数值越高＝供给压力越大",
    "Trailing 4w sum": "过去4周合计",
    "Usd mn per day": "百万美元/日",
    "Higher stronger auction demand": "数值越高＝拍卖需求越强",
    "Bid to cover ratio pts": "投标倍数点数",
    "Auctions": "拍卖",
    "Count of auctions actually used": "实际使用的拍卖次数",
    "Years": "年",
    "Level quarterly period end": "季度末水平",
    "Pct pts of gdp trend gap": "相对 GDP 趋势的百分点缺口",
    "Higher more restrictive real financing cost": "数值越高＝实际融资成本越紧",
    "Tips constant maturity investment basis": "TIPS 固定期限投资口径",
    "Market derived breakeven inflation": "市场推导的盈亏平衡通胀",
    "Business days": "交易日",
    "Longer run more entrenched regime": "持续时间越长＝状态越稳固",
    "Consecutive shared date rows": "连续同日对齐行数",
    "Higher more surplus": "数值越高＝顺差越大",
    "Same date disciplined ratio": "同日对齐比率",
    "Index nsa": "指数（非季调）",
    "Gdpnow growth": "GDPNow 增长",
    "Wei growth": "周度经济指数增长",
    "Pct annualized equiv": "年化等值百分比",
    "Leading tier momentum": "领先层动能",
    "Coincident tier momentum": "同步层动能",
    "Leading diffusion": "领先扩散",
    "Coincident diffusion": "同步扩散",
    "Coincident index level": "同步指数水平",
    "Lagging tier momentum": "滞后层动能",
    "Recession risk score": "衰退风险评分",
    "Probability 0 1": "概率（0–1）",
    "Real income proxy yoy": "实际收入代理同比",
    "Leading tier trend": "领先层趋势",
    "Leading tier diffusion": "领先层扩散",
    "Leading tier direction": "领先层方向",
    "Leading tier leg count": "领先层分项数",
    "Coincident tier index": "同步层指数",
    "Coincident tier trend": "同步层趋势",
    "Coincident tier diffusion": "同步层扩散",
    "Coincident tier direction": "同步层方向",
    "Falling": "下降",
    "Coincident tier leg count": "同步层分项数",
    "Lagging tier trend": "滞后层趋势",
    "Lagging tier direction": "滞后层方向",
    "Lagging tier leg count": "滞后层分项数",
    "Ratio pt": "比率点",
    "6m change of ratio": "比率的6个月变化",
    "Recession signal state": "衰退信号状态",
    "Off": "关闭",
    "Three ds rule": "三项门槛规则",
    "Recession signal depth": "衰退信号深度",
    "Leading mom6 below threshold": "领先6个月动能低于门槛",
    "Recession signal breadth": "衰退信号广度",
    "Diffusion at or below cutoff": "扩散处于或低于截止值",
    "Recession signal months active": "衰退信号持续月数",
    "Consecutive months in state": "连续处于该状态的月数",
    "Business cycle phase": "商业周期阶段",
    "Recovery": "复苏",
    "Leading x coincident momentum sign": "领先与同步动能方向",
    "Recession signal oos catch rate": "衰退信号样本外捕捉率",
    "Higher more reliable": "数值越高＝越可靠",
    "Leave one recession out": "留出一次衰退",
    "Survey composite pmi": "调查综合 PMI",
    "Diffusion index 50 line": "扩散指数50分界",
    "Higher expansion below50 contraction": "高于50为扩张，低于50为收缩",
    "Diffusion index": "扩散指数",
    "New orders demand": "新订单需求",
    "Production utilization": "产能利用率",
    "Inventory cycle phase": "库存周期阶段",
    "Capex orders growth": "资本开支订单增长",
    "Shipments sales growth": "出货与销售增长",
    "Initial claims 4wk": "初请失业金（4周）",
    "Four week moving average": "四周移动平均",
    "Continued claims": "续请失业金",
    "Claims yoy pct": "失业金申领同比",
    "Claims z": "失业金申领 z 值",
    "Indeed postings index": "Indeed 职位发布指数",
    "Indeed chg 3m pct": "Indeed 三个月变化",
    "Three month change": "三个月变化",
    "Withheld tax yoy pct": "代扣税同比",
    "Recession claims subscore": "衰退申领分项评分",
    "Score 0 1": "评分（0–1）",
    "Payrolls nfp change and revision": "非农就业变化与修订",
    "Unemployment rate u3": "失业率（U3）",
    "Labor force participation rate": "劳动参与率",
    "Jolts job openings": "职位空缺",
    "Jolts quits rate": "主动离职率",
    "Avg hourly earnings yoy": "平均时薪同比",
    "Adp bls payroll divergence": "ADP 与劳工部就业差",
    "Headline cpi yoy pct": "整体 CPI 同比",
    "Headline cpi mom pct": "整体 CPI 环比",
    "Core cpi yoy pct": "核心 CPI 同比",
    "Core cpi mom pct": "核心 CPI 环比",
    "Core cpi annualized 6m pct": "核心 CPI 6个月年化",
    "Sticky cpi annualized 3m pct": "黏性 CPI 3个月年化",
    "Higher more persistent": "数值越高＝越持久",
    "Flexible cpi annualized 3m pct": "灵活 CPI 3个月年化",
    "Higher more transitory": "数值越高＝越短暂",
    "Next cpi core release projection mom pct": "下次核心 CPI 公布的环比估计",
    "Pct mom sa": "环比百分比（季调）",
    "Release radar champion projection": "发布雷达主估计",
    "Next cpi release date": "下次 CPI 发布日期",
    "Bls calendar": "劳工统计局日历",
    "Current month pressure direction": "本月价格压力方向",
    "Upward price pressure": "向上的价格压力",
    "Model nowcast": "模型即时估计",
    "Pp spread": "百分点利差",
    "Ecb deposit rate": "欧央行存款利率",
    "Boj policy rate": "日本央行政策利率",
    "Global policy divergence bp": "全球政策分歧（基点）",
    "Higher more divergent": "数值越高＝分歧越大",
    "Max minus min across reporting cbs": "各央行最高减最低",
    "Higher more hikes priced": "数值越高＝定价的加息越多",
    "Market implied funds m6": "市场隐含联邦基金利率（6个月）",
    "Market implied funds m12": "市场隐含联邦基金利率（12个月）",
    "Fed dot median nearest": "美联储最近一次点阵中位",
    "Fomc sep median dot owner native": "FOMC 经济预测中位点",
    "Positive when market prices above fed dot": "正值表示市场定价高于美联储点阵",
    "Fed dot vs market implied gap": "美联储点阵与市场隐含之差",
    "Policy uncertainty state": "政策不确定性状态",
    "Elevated": "偏高",
    "Nominal 10y": "10年期名义收益率",
    "Tips implied real yield": "TIPS 隐含实际收益率",
    "Higher steeper": "数值越高＝越陡",
    "Tips breakeven inflation expectation": "TIPS 盈亏平衡通胀预期",
    "Fed balance sheet level": "美联储资产负债表水平",
    "Fed balance sheet impulse 13w": "美联储资产负债表脉冲（13周）",
    "Ecb balance sheet impulse 13w": "欧央行资产负债表脉冲（13周）",
    "Boj balance sheet impulse 13w": "日本央行资产负债表脉冲（13周）",
    "Recession prob nyfed": "纽约联储衰退概率",
    "Higher more recession risk": "数值越高＝衰退风险越大",
    "Ny fed term spread model": "纽约联储期限利差模型",
    "Core pce vs target pp": "核心 PCE 相对目标（百分点）",
    "Higher more above target": "数值越高＝越高于目标",
    "Core pce yoy minus 2pct target": "核心 PCE 同比减 2% 目标",
    "Next fomc meeting days": "距下次 FOMC 会议天数",
    "Next ecb meeting days": "距下次欧央行会议天数",
    "Next boj meeting days": "距下次日本央行会议天数",
    "Ofr fsi pctile": "OFR 金融压力分位",
    "Hy oas z": "高收益利差 z 值",
    "Real 10y pctile": "10年期实际收益率分位",
    "Real 10y chg 63d bp": "10年期实际收益率 63 日变化（基点）",
    "Roc 63d": "63 日变化率",
    "Ofr fsi change 13w": "OFR 金融压力 13 周变化",
    "Ofr funding functional": "OFR 融资功能",
    "Vix": "VIX",
    "Vol pts": "波动率点数",
    "Vol regime risk score": "波动率体制风险评分",
    "Risk appetite score": "风险偏好评分",
    "Higher more risk off": "数值越高＝越避险",
    "Ig oas pct": "投资级利差百分比",
    "Dollar index pctile": "美元指数分位",
    "Lending channel score": "借贷渠道评分",
    "Rates channel score": "利率渠道评分",
    "Credit channel score": "信贷渠道评分",
    "Dollar funding channel score": "美元融资渠道评分",
    "Equities vol channel score": "股市波动渠道评分",
    "Prior only expanding z score of weekly change": "仅用先验的周变化扩张 z 值",
    "Glt monetary stance": "全球流动性货币立场",
    "Expanding z score": "扩张 z 值",
    "Glt orthogonalised impulse": "全球流动性正交脉冲",
    "Causal regression residual z units": "因果回归残差（z 值）",
    "Share 0 to 1": "份额（0–1）",
    "Higher broader agreement": "数值越高＝方向一致越广",
    "Share of components agreeing with direction": "与方向一致的分项占比",
    "Expanding z score positive is easier": "扩张 z 值为正表示更宽松",
    "Glt policy liquidity impulse": "全球政策流动性脉冲",
    "Glt credit impulse global": "全球信贷脉冲",
    "Higher more credit expansion": "数值越高＝信贷扩张越多",
    "Cross country credit impulse comparison": "跨国信贷脉冲比较",
    "Glt state label": "全球流动性状态标签",
    "Flat": "持平",
    "Glt state quality label": "全球流动性质量标签",
    "Mixed": "混合",
    "State vs us quality agreement label": "相对美国质量是否一致",
    "Glt confidence": "全球流动性置信度",
    "Higher more coverage and pit reliability": "数值越高＝覆盖与同点可靠性越高",
    "Glt monetary coverage ratio": "全球货币覆盖率",
    "Glt funding coverage ratio": "全球融资覆盖率",
    "Glt fed monetary contribution z": "美联储货币贡献 z 值",
    "Glt ecb monetary contribution z": "欧央行货币贡献 z 值",
    "Glt boj monetary contribution z": "日本央行货币贡献 z 值",
    "Glt broad dollar contribution z": "广义美元贡献 z 值",
    "Glt high yield oas contribution z": "高收益利差贡献 z 值",
    "Glt real yield 10y contribution z": "10年期实际收益率贡献 z 值",
    "Cb fed balance sheet level": "美联储资产负债表水平",
    "Cb fed balance sheet impulse 52w": "美联储资产负债表脉冲（52周）",
    "Cb ecb balance sheet level": "欧央行资产负债表水平",
    "Eur billions": "十亿欧元",
    "Cb ecb balance sheet impulse 13w": "欧央行资产负债表脉冲（13周）",
    "Cb ecb balance sheet impulse 52w": "欧央行资产负债表脉冲（52周）",
    "Cb boj balance sheet level": "日本央行资产负债表水平",
    "Jpy billions": "十亿日元",
    "Cb boj balance sheet impulse 13w": "日本央行资产负债表脉冲（13周）",
    "Cb boj balance sheet impulse 52w": "日本央行资产负债表脉冲（52周）",
    "Cs edge count": "资本结构关系边数",
    "Edges": "边",
    "Cs owner generation age hours": "所有者生成距今小时数",
    "Hours": "小时",
    "Cs coverage state": "资本结构覆盖状态",
    "Partial": "部分",
    "Cs event detection freshness state": "事件检测新鲜度",
    "Stale": "已过期",
    "Cs generation freshness state": "生成新鲜度",
    "Fresh": "新鲜",
    "Cs source status": "来源状态",
    "Ok": "正常",
    "Cs horizon state": "视野状态",
    "Degraded discovery": "发现能力下降",
    "Cs event classification rate": "事件分类率",
    "Classified over total events": "已分类占全部事件",
    "Cs review backlog ratio": "复核积压比率",
    "Higher more backlog": "数值越高＝积压越多",
    "Pending review over total events": "待复核占全部事件",
    "Cs issuer records count": "发行主体记录数",
    "Cs issuer latest event classified count": "发行主体最新已分类事件数",
    "Cs issuer latest event classified share": "发行主体最新已分类占比",
    "Classified over total issuer records": "已分类占全部发行主体记录",
    "Cs issuer pending review count": "发行主体待复核数",
    "Cs issuer shelf registration count": "发行主体储架注册数",
    "Cs issuer shelf registration share": "发行主体储架注册占比",
    "Higher more shelf activity": "数值越高＝储架活动越多",
    "Shelf over total issuer records": "储架占全部发行主体记录",
    "Cs issuer with relationships count": "有关系的发行主体数",
    "Cs issuer correction present count": "有更正的发行主体数",
    "Cs issuer contradiction flagged count": "标有矛盾的发行主体数",
    "Cs active instrument overhang": "在途工具存量",
    "Cs cash runway": "现金可维持时间",
    "Cs financing probability": "融资概率",
    "Cs fully diluted shares": "完全稀释股本",
    "Cs instruments": "融资工具",
    "Cs normalized terms": "标准化条款",
    "Cs offering ability": "发行能力",
    "Cs remaining capacity": "剩余额度",
    "Market rate level": "市场利率水平",
    "Mortgage 30y rate change 13w": "30年期房贷利率 13 周变化",
    "Housing starts level": "新屋开工水平",
    "Building permits level": "营建许可水平",
    "Permits minus starts spread": "许可减开工之差",
    "Higher more pipeline ahead of starts": "数值越高＝开工前储备越多",
    "Level difference permits minus starts": "许可减开工的水平差",
    "Case shiller national hpi level": "全国房价指数水平",
    "Index pt jan2000 100": "指数点（2000年1月=100）",
    "National rent zori level": "全国租金指数水平",
    "Usd per month": "美元/月",
    "National rent zori yoy": "全国租金指数同比",
    "Existing home sales": "成屋销售",
    "New home sales": "新屋销售",
    "Housing completions": "住房竣工",
    "Pending home sales redfin": "待售签约（Redfin）",
    "Active listings redfin": "在售房源（Redfin）",
    "Price drop share redfin": "降价房源占比（Redfin）",
    "Median days on market redfin": "中位挂牌天数（Redfin）",
    "Retail sales mom": "零售销售环比",
    "Mom pct change": "环比变化",
    "Index 1966q1 100": "指数（1966年一季度=100）",
    "Consumer credit total level": "消费者信贷总额",
    "Consumer credit total yoy": "消费者信贷总额同比",
    "Consumer credit revolving level": "循环信贷水平",
    "Consumer credit revolving yoy": "循环信贷同比",
    "Consumer credit nonrevolving level": "非循环信贷水平",
    "Consumer credit nonrevolving yoy": "非循环信贷同比",
    "Personal saving rate level": "个人储蓄率",
    "Personal saving rate change 3m": "个人储蓄率 3 个月变化",
    "Trailing 3m level change": "过去 3 个月水平变化",
    "Real disposable income level": "实际可支配收入",
    "Usd billions chained saar": "链式十亿美元（年化季调）",
    "Higher more income": "数值越高＝收入越多",
    "Real disposable income yoy": "实际可支配收入同比",
    "Higher more income growth": "数值越高＝收入增长越快",
    "Cc delinquency rate level": "信用卡拖欠率",
    "Mortgage delinquency rate level": "房贷拖欠率",
    "Payments panel card network": "支付面板（卡网络）",
    "Household debt panel nyfed qhdc": "家庭债务面板（纽约联储）",
    "Higher stronger momentum": "数值越高＝动能越强",
    "Higher more cash parked at the fed mechanically tighter bank reserves":
        "数值越高＝停在美联储的现金越多，银行准备金越紧",
    "Tga impulse 4w": "财政部现金脉冲（4周）",
    "Trailing 4w level change": "过去 4 周水平变化",
    "Tga impulse 13w": "财政部现金脉冲（13周）",
    "Net issuance sum 4w": "净发行合计（4周）",
    "Trailing 13w sum": "过去 13 周合计",
    "Net issuance pace delta 4w vs 13w avg daily": "净发行节奏：4周相对13周日均差",
    "Positive is accelerating issuance pace": "正值表示发行节奏在加快",
    "Trailing 4w avg daily minus trailing 13w avg daily": "4周日均减13周日均",
    "Withheld taxes level": "代扣税水平",
    "Higher more daily withheld receipts": "数值越高＝每日代扣收入越多",
    "Withheld taxes sum 4w": "代扣税合计（4周）",
    "Higher more trailing revenue": "数值越高＝近期收入越多",
    "Withheld taxes yoy 4w": "代扣税同比（4周）",
    "Higher stronger income and employment growth": "数值越高＝收入与就业增长越强",
    "Yoy pct change of trailing 4w sum": "过去4周合计的同比变化",
    "Trailing up to 8 auctions with btc": "最近最多8次有投标倍数的拍卖",
    "Auction bid to cover baseline avg": "拍卖投标倍数基线均值",
    "Trailing 365d auctions with btc": "过去365天有投标倍数的拍卖",
    "Auction demand spread recent vs baseline": "拍卖需求：近期相对基线",
    "Positive is strengthening demand vs baseline": "正值表示需求相对基线走强",
    "Recent avg minus baseline avg": "近期均值减基线均值",
    "Auction recent window count": "近期窗口拍卖次数",
    "Auction baseline window count": "基线窗口拍卖次数",
    "Auction latest bid to cover": "最近一次拍卖投标倍数",
    "Higher stronger demand at that auction": "数值越高＝该次拍卖需求越强",
    "Auction latest high yield": "最近一次拍卖最高收益率",
    "Higher more expensive financing at that auction": "数值越高＝该次拍卖融资越贵",
    "Auction latest security type": "最近一次拍卖证券类型",
    "Bill": "短期国债",
    "Auction latest tenor years": "最近一次拍卖期限（年）",
    "Percent of disposable income": "占可支配收入百分比",
    "Higher more household debt service burden": "数值越高＝家庭偿债负担越重",
    "Credit gap level": "信贷缺口水平",
    "Higher more credit expansion relative to trend": "数值越高＝相对趋势的信贷扩张越多",
    "Score 0 100": "评分（0–100）",
    "Higher more healthy": "数值越高＝越健康",
    "Bond desk health label": "债市交易台健康标签",
    "Healthy": "健康",
    "Bond desk cycle phase": "债市交易台周期阶段",
    "Late": "后期",
    "Debt outstanding total": "未偿债务总额",
    "Debt held by public": "公众持有的债务",
    "Debt intragovernmental holdings": "政府内部持有的债务",
    "Fiscal deficit primary balance": "财政赤字与基本余额",
    "Net interest burden": "净利息负担",
    "Debt weighted average maturity": "债务加权平均期限",
    "Auction tail bp": "拍卖尾差（基点）",
    "Auction indirect bidder share": "拍卖间接投标人占比",
    "Foreign holdings tic": "外国持有（TIC）",
    "Contingent liabilities": "或有负债",
    "Debt to gdp ratio": "债务占 GDP 比重",
    "Percent of gdp": "占 GDP 百分比",
    "Usd bn per day": "十亿美元/日",
    "Us3m level": "3个月美债收益率",
    "Us6m level": "6个月美债收益率",
    "Us1y level": "1年期美债收益率",
    "Us3y level": "3年期美债收益率",
    "Us5y level": "5年期美债收益率",
    "Us7y level": "7年期美债收益率",
    "Us20y level": "20年期美债收益率",
    "Us30y level": "30年期美债收益率",
    "Us5y real level": "5年期实际收益率",
    "Us10y real level": "10年期实际收益率",
    "Breakeven 10y level": "10年期盈亏平衡通胀",
    "Breakeven 5y5y level": "5年后再5年远期通胀",
    "Higher more term compensation demanded": "数值越高＝要求的期限补偿越多",
    "Kim wright term premium model": "Kim-Wright 期限溢价模型",
    "Effr level": "有效联邦基金利率",
    "Obfr level": "隔夜银行融资利率",
    "Sofr level": "SOFR 水平",
    "Iorb level": "准备金利息水平",
    "Us2y change 13w": "2年期美债 13 周变化",
    "Us10y change 13w": "10年期美债 13 周变化",
    "Us30y change 13w": "30年期美债 13 周变化",
    "Term premium 10y change 13w": "10年期期限溢价 13 周变化",
    "Positive is term compensation rising over 13w": "正值表示期限补偿在13周内上升",
    "Curve 3m10y level": "3个月至10年期利差",
    "Curve 5s30s level": "5年期至30年期利差",
    "Curve 2s10s inversion run length bd": "2年与10年倒挂持续交易日",
    "Curve 3m10y inversion run length bd": "3个月与10年倒挂持续交易日",
    "Curvature butterfly 2s5s10s": "2-5-10 年蝶式曲率",
    "Higher more humped curve": "数值越高＝曲线越拱",
    "Same date disciplined butterfly": "同日对齐蝶式",
    "Nominal real breakeven residual 10y": "名义/实际/盈亏平衡 10 年残差",
    "Magnitude indicates cross curve interpolation noise": "幅度表示跨曲线插值噪声",
    "Same date disciplined decomposition residual": "同日对齐分解残差",
    "Corridor effr minus iorb bp": "走廊：有效联邦基金减准备金利息（基点）",
    "Corridor sofr minus effr bp": "走廊：SOFR 减有效联邦基金（基点）",
    "Corridor sofr minus iorb bp": "走廊：SOFR 减准备金利息（基点）",
    "Trade balance avg 3m": "贸易差额 3 个月均值",
    "Trailing 3m average": "过去 3 个月均值",
    "Trade balance yoy change": "贸易差额同比变化",
    "Positive is balance improving": "正值表示差额在改善",
    "Yoy level change": "同比水平变化",
    "Higher more exports": "数值越高＝出口越多",
    "Exports yoy": "出口同比",
    "Higher faster export growth": "数值越高＝出口增长越快",
    "Higher more imports": "数值越高＝进口越多",
    "Imports yoy": "进口同比",
    "Higher faster import growth": "数值越高＝进口增长越快",
    "Higher more export coverage of imports": "数值越高＝出口对进口覆盖越多",
    "Import price index level": "进口价格指数",
    "Higher more expensive imports": "数值越高＝进口越贵",
    "Import price index yoy": "进口价格指数同比",
    "Higher faster import price inflation": "数值越高＝进口价格涨得越快",
    "Export price index level": "出口价格指数",
    "Higher more expensive exports": "数值越高＝出口越贵",
    "Export price index yoy": "出口价格指数同比",
    "Higher faster export price inflation": "数值越高＝出口价格涨得越快",
    "Terms of trade proxy": "贸易条件代理",
    "Higher more favorable terms of trade": "数值越高＝贸易条件越有利",
    "Trade balance share of flows pct": "贸易差额占流量比重",
    "Higher more surplus relative to flow volume": "数值越高＝相对流量的顺差越大",
    "Same date disciplined share": "同日对齐占比",
    "Trade balance identity residual": "贸易差额恒等残差",
    "Magnitude indicates cross series revision vintage mismatch":
        "幅度表示跨序列修订版本不一致",
    "Same date disciplined identity residual": "同日对齐恒等残差",
    "Bilateral country trade detail": "双边国别贸易明细",
    "Petroleum specific trade flows": "石油专项贸易流动",
    "Customs tariff receipts": "关税收入",
    "Trade services detail": "服务贸易明细",
    "Usd bn": "十亿美元",
}


_CJK = __import__("re").compile(
    r"[\u3000-\u303f\u3400-\u9fff\uf900-\ufaff\uff00-\uffef]"
)
_LETTERS = __import__("re").compile(r"[A-Za-z]")


def zh_is_ascii_letters_only(text: str) -> bool:
    """True when visible ZH copy is English letters (the M1 fail shape)."""
    if not text or not _LETTERS.search(text):
        return False
    return _CJK.search(text) is None


def apply_zh_parity(node: Mapping[str, str] | None) -> dict[str, str] | None:
    """Replace an ASCII-only ZH twin from the enumerated table."""
    if not node:
        return None
    en = str(node.get("en") or "")
    zh = str(node.get("zh") or "")
    if zh_is_ascii_letters_only(zh):
        fixed = ZH_PARITY.get(zh) or ZH_PARITY.get(en)
        if fixed:
            return {"en": en, "zh": fixed}
    return dict(node)
