(function(){
'use strict';
const root=document.getElementById('bm-main'),panel=document.getElementById('bm-panel'),announcement=document.getElementById('bm-announcement');
if(!root||!panel)return;
const journeys=[
{id:'nutrien',company:'Nutrien',family:'fertilizers',en:{question:'Did better realization become better unit economics?',lens:'Price is not retained margin',guard:'Keep the manufactured-product scope distinct from a global commodity benchmark.'},zh:{question:'更高实现价格是否转化为更好的单位经济？',lens:'价格不等于留存利润',guard:'保持制成品范围与全球商品基准之间的区别。'}},
{id:'novonix',company:'NOVONIX',family:'battery-strategic',en:{question:'What separates testing from commercial sales?',lens:'Qualification is not revenue',guard:'Internal testing, customer acceptance, shipment and collected cash are separate states.'},zh:{question:'测试与商业销售之间还差什么？',lens:'客户验证不等于收入',guard:'内部测试、客户验收、发货与现金回收是不同状态。'}},
{id:'wheaton',company:'Wheaton / Antamina',family:'precious-metals',en:{question:'Which contract terms determine value capture?',lens:'A financial right, not a mine',guard:'Contractual participation is not physical mine ownership or extra supply.'},zh:{question:'哪些合同条款决定价值获取？',lens:'金融权益，不是矿山所有权',guard:'合同参与权益不等于矿山实物所有权或新增供给。'}},
{id:'weyerhaeuser',company:'Weyerhaeuser',family:'forest-packaging',en:{question:'What cash remains after actual investment?',lens:'Cash spent still counts',guard:'An adjusted distribution measure cannot make actual investment cash disappear.'},zh:{question:'实际投资后还剩多少现金？',lens:'已花出的现金仍需计入',guard:'调整后的分配指标不能让实际投资支出消失。'}}
];
const copy={
en:{understand:'Understand',compare:'Compare businesses',evidence:'Check evidence',start:'Start with the business question',empty:'No worked journey is included for this family yet.',inspect:'What to preserve',families:'Selected journey templates',question:'Economic question',lens:'Interpretive lens',guard:'Boundary',subject:'Research subject',source:'Source evidence',identity:'Company identity',rights:'Current display rights',unavailable:'Not connected',sourceDesc:'Original-source admission and exact receipts are not connected to this shell.',identityDesc:'Canonical issuer/security mapping is not consumed by this shell yet.',rightsDesc:'The shell does not treat a candidate rights decision as production permission.',compareNote:'These businesses answer different economic questions. No common score is computed.',announce:'Dossier view updated'},
zh:{understand:'理解',compare:'比较企业',evidence:'核查证据',start:'从企业问题开始',empty:'此类别暂未包含已完成的研究案例。',inspect:'需要保留的边界',families:'精选研究案例模板',question:'经济问题',lens:'解读视角',guard:'边界',subject:'研究对象',source:'来源证据',identity:'公司身份',rights:'当前展示权利',unavailable:'未接入',sourceDesc:'原始来源准入与精确凭据尚未接入此页面。',identityDesc:'此页面尚未消费规范化的发行人/证券映射。',rightsDesc:'此页面不会把候选版权利决定当作生产权限。',compareNote:'这些企业回答不同的经济问题，不计算统一评分。',announce:'档案视图已更新'}
};
let task='understand',family='',selected='nutrien';
function lang(){return document.documentElement.getAttribute('data-lang')==='zh'?'zh':'en'}
function t(key){return copy[lang()][key]||copy.en[key]||key}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function visible(){return journeys.filter(j=>!family||j.family===family)}
function normalizedTask(value){return ['understand','compare','evidence'].includes(value)?value:'understand'}
function syncHash(push){const params=new URLSearchParams();params.set('task',task);if(family)params.set('family',family);params.set('journey',selected);const next='#'+params.toString();if(location.hash===next)return;if(push)history.pushState(null,'',next);else history.replaceState(null,'',next)}
function readHash(){const params=new URLSearchParams(location.hash.replace(/^#/,''));task=normalizedTask(params.get('task'));const requestedFamily=params.get('family')||'';const familyButton=document.querySelector('[data-bm-family="'+CSS.escape(requestedFamily)+'"]');family=familyButton?requestedFamily:'';const wanted=params.get('journey')||'nutrien';selected=journeys.some(j=>j.id===wanted)?wanted:'nutrien';if(family&&!visible().some(j=>j.id===selected)){const first=visible()[0];if(first)selected=first.id}}
function renderTabs(){document.querySelectorAll('[data-bm-tab]').forEach(button=>{const on=button.dataset.bmTab===task;button.setAttribute('aria-selected',String(on));button.tabIndex=on?0:-1});panel.setAttribute('aria-labelledby','bm-tab-'+task)}
function renderFamilies(){document.querySelectorAll('[data-bm-family]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.bmFamily===family)))}
function renderUnderstand(){const list=visible(),heading=el('div','bm-section-heading'),left=el('div');left.append(el('p','bm-kicker',t('families')),el('h2','',t('start')));heading.append(left,el('span','bm-count',String(list.length)+' / '+String(journeys.length)));panel.append(heading);if(!list.length){panel.append(el('div','bm-empty',t('empty')));return}const layout=el('div','bm-journey-layout'),nav=el('div','bm-journey-list');list.forEach((j,index)=>{const b=el('button','bm-journey');b.type='button';b.id='bm-journey-'+j.id;b.setAttribute('aria-pressed',String(j.id===selected));const num=el('span','bm-journey-num',String(index+1).padStart(2,'0')),words=el('span','bm-journey-copy');words.append(el('strong','',j.company),el('span','',j[lang()].question));b.append(num,words,el('span','bm-arrow','›'));b.addEventListener('click',()=>{selected=j.id;syncHash(true);render();b.focus()});nav.append(b)});const current=list.find(j=>j.id===selected)||list[0];if(current.id!==selected)selected=current.id;const card=el('article','bm-lens-card');card.append(el('p','bm-kicker',t('inspect')),el('h2','',current[lang()].lens),el('p','bm-question',current[lang()].question));const guard=el('div','bm-guard');guard.append(el('strong','',t('guard')),el('p','',current[lang()].guard));card.append(guard);layout.append(nav,card);panel.append(layout)}
function renderCompare(){const wrap=el('div','bm-section-heading'),left=el('div');left.append(el('p','bm-kicker',t('compare')),el('h2','',t('question')));wrap.append(left);panel.append(wrap,el('p','bm-copy',t('compareNote')));const scroll=el('div','bm-table-wrap');scroll.tabIndex=0;scroll.setAttribute('role','region');scroll.setAttribute('aria-label',t('compare'));const table=el('table','bm-table');table.append(el('caption','visually-hidden',t('compare')));const thead=el('thead'),tr=el('tr');[t('subject'),t('question'),t('lens'),t('guard')].forEach(label=>{const th=el('th','',label);th.scope='col';tr.append(th)});thead.append(tr);table.append(thead);const tbody=el('tbody');journeys.forEach(j=>{const row=el('tr'),h=el('th','',j.company);h.scope='row';row.append(h,el('td','',j[lang()].question),el('td','',j[lang()].lens),el('td','',j[lang()].guard));tbody.append(row)});table.append(tbody);scroll.append(table);panel.append(scroll)}
function evidenceRow(title,desc){const row=el('article','bm-evidence-row'),words=el('div');words.append(el('h3','',title),el('p','',desc));row.append(words,el('span','bm-state-chip',t('unavailable')));return row}
function renderEvidence(){const h=el('div','bm-section-heading'),left=el('div');left.append(el('p','bm-kicker',t('evidence')),el('h2','',t('unavailable')));h.append(left);panel.append(h);const list=el('div','bm-evidence-list');list.append(evidenceRow(t('source'),t('sourceDesc')),evidenceRow(t('identity'),t('identityDesc')),evidenceRow(t('rights'),t('rightsDesc')));panel.append(list)}
function render(){renderTabs();renderFamilies();panel.replaceChildren();if(task==='understand')renderUnderstand();else if(task==='compare')renderCompare();else renderEvidence();announcement.textContent=t('announce')+': '+t(task)}
document.querySelectorAll('[data-bm-tab]').forEach(button=>{button.addEventListener('click',()=>{task=button.dataset.bmTab;syncHash(true);render();button.focus()});button.addEventListener('keydown',event=>{const order=['understand','compare','evidence'];let i=order.indexOf(task);if(event.key==='ArrowRight')i=(i+1)%order.length;else if(event.key==='ArrowLeft')i=(i+order.length-1)%order.length;else if(event.key==='Home')i=0;else if(event.key==='End')i=order.length-1;else return;event.preventDefault();task=order[i];syncHash(true);render();document.getElementById('bm-tab-'+task).focus()})});
document.querySelectorAll('[data-bm-family]').forEach(button=>button.addEventListener('click',()=>{family=button.getAttribute('aria-pressed')==='true'?'':button.dataset.bmFamily;const list=visible();if(list.length&&!list.some(j=>j.id===selected))selected=list[0].id;syncHash(true);render();button.focus()}));
window.addEventListener('popstate',()=>{readHash();render();document.getElementById('bm-tab-'+task).focus()});
document.addEventListener('langchange',render);
readHash();syncHash(false);render();
})();