"""scripts/build_regime_prior.py — emit site/regimedata/regime_prior.js (W4.5).

Two responsibilities:

  1. ARTIFACT — write site/regimedata/regime_prior.js as a script-tag data file
     (window.REGIME_PRIOR = {...}) consumed by all cycle-family pages.

  2. PIT ACCRUAL — append one row to data/regime/market_state_history.parquet
     (keep-first per date) so market_state can become a model feature once n_days >= 250.
     The keep-FIRST discipline ensures build reruns on the same day do not overwrite
     the morning snapshot with an afternoon value.

Called from:
  • scripts/build_cycle.main()
  • scripts/build_markets.main()
  (both call build_regime_prior.emit() before rendering their own artifact)

Can also be run standalone: python -m scripts.build_regime_prior
"""
from __future__ import annotations

import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

log = logging.getLogger(__name__)


def emit(
    data_dir: Path | None = None,
    site_dir: Path | None = None,
    *,
    dry_run: bool = False,
) -> dict:
    """Compose the regime prior, write the JS artifact, append PIT row.

    Returns the prior dict.  Never raises — failures are logged.
    """
    from lib import config
    from engine.regime_prior import regime_prior as _compose

    if data_dir is None:
        data_dir = config.data_dir()
    if site_dir is None:
        cfg = config.load()
        site_dir = config.ROOT / cfg["storage"]["site_dir"]

    # ---- 1. Compose --------------------------------------------------------
    prior = _compose(data_dir=data_dir, site_dir=site_dir)

    # ---- 2. Write site/regimedata/regime_prior.js (script-tag, A11) --------
    if not dry_run:
        _write_js(site_dir, prior)

    # ---- 3. Append PIT row to market_state_history.parquet -----------------
    if not dry_run:
        _append_pit(data_dir, prior)

    return prior


def _write_js(site_dir: Path, prior: dict) -> None:
    """Write window.REGIME_PRIOR = {...} to site/regimedata/regime_prior.js."""
    try:
        out_dir = site_dir / "regimedata"
        out_dir.mkdir(parents=True, exist_ok=True)
        body = json.dumps(prior, ensure_ascii=False, separators=(",", ":"))
        js = (
            "/* regime_prior.js — GENERATED by scripts/build_regime_prior.py (W4.5).\n"
            "   window.REGIME_PRIOR: single conditioning prior for all cycle pages.\n"
            "   Sources: regime/latest.json + market_state/latest.json + vol_regime + business_cycle.\n"
            "   market_state is DISPLAY-ONLY (not_a_model_input: true).\n"
            "   Do not edit by hand — regenerate via `python -m scripts.build_regime_prior`. */\n"
            "window.REGIME_PRIOR = " + body + ";\n"
        )
        out_path = out_dir / "regime_prior.js"
        out_path.write_text(js, encoding="utf-8")
        log.info(
            "regime_prior.js: quad=%s liquidity=%s market_state=%s vol=%s bc_phase=%s status=%s",
            prior.get("quad"), prior.get("liquidity"),
            (prior.get("market_state") or {}).get("verdict"),
            prior.get("vol_regime"), prior.get("bc_phase"),
            prior.get("status"),
        )
    except Exception as e:  # noqa: BLE001
        log.warning("build_regime_prior: JS write failed: %s", e)


def _append_pit(data_dir: Path, prior: dict) -> None:
    """Append one row to data/regime/market_state_history.parquet (keep-first per date).

    Row schema:
        date          YYYY-MM-DD string (the build date, UTC)
        quad          Q1/Q2/Q3/Q4 | None
        liquidity     expanding/contracting/neutral | None
        ms_verdict    RISK_ON/MIXED/RISK_OFF | None
        ms_score      int | None
        vol_regime    str | None
        bc_phase      str | None
        status        fresh/stale/partial/unavailable
        built_at      ISO-8601 UTC datetime
    """
    try:
        import pandas as pd
    except ImportError:
        log.warning("build_regime_prior: pandas not available — skipping PIT accrual")
        return
    try:
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        ms = prior.get("market_state") or {}
        row = {
            "date": today,
            "quad": prior.get("quad"),
            "liquidity": prior.get("liquidity"),
            "ms_verdict": ms.get("verdict"),
            "ms_score": ms.get("score"),
            "vol_regime": prior.get("vol_regime"),
            "bc_phase": prior.get("bc_phase"),
            "status": prior.get("status"),
            "built_at": datetime.now(timezone.utc).isoformat(),
        }
        out_path = data_dir / "regime" / "market_state_history.parquet"

        # Load existing history
        if out_path.exists():
            existing = pd.read_parquet(out_path)
        else:
            existing = pd.DataFrame(columns=list(row.keys()))

        # Keep-first per date: only append if today is not already present
        if "date" in existing.columns and today in existing["date"].values:
            log.info(
                "build_regime_prior: PIT accrual — date %s already present, skipping (keep-first)",
                today,
            )
            return

        new_row = pd.DataFrame([row])
        history = pd.concat([existing, new_row], ignore_index=True)
        history.to_parquet(out_path, index=False)
        n = len(history)
        log.info(
            "build_regime_prior: PIT accrual — appended %s (total %d rows; "
            "come-back when n_days >= 250 to assess market_state as model feature)",
            today, n,
        )
    except Exception as e:  # noqa: BLE001
        log.warning("build_regime_prior: PIT accrual failed (non-fatal): %s", e)


def main() -> int:
    from lib import config
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s %(message)s")
    cfg = config.load()
    data_dir = config.data_dir()
    site_dir = config.ROOT / cfg["storage"]["site_dir"]
    prior = emit(data_dir=data_dir, site_dir=site_dir)
    print(json.dumps(prior, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
