"""
scripts/check_synapse_reads.py — Synapse read-gate: literal-path scan v1 + horizon firewall.

For every artifact registered in config/synapse.yml, scans engine/*.py,
scripts/*.py, and collectors/*.py for string literals that contain the
artifact's path (or its directory prefix for per-ticker pattern paths).
Undeclared readers — modules that reference the path but are NOT the registered
producer, a known_extra_writer, or a declared consumer — are findings.

Two severity tiers:
  WARN (exit 0):  any undeclared reader → print + GitHub ::warning:: annotation.
  HARD FAIL (exit 1): an undeclared reader that is an Article-2 surface module
                       (the money-path set defined in synapse.yml meta.article2_surfaces).

Baseline (data/neuralweb/read_gate_baseline.json):
  Generated by --write-baseline; contains the snapshot of ALL findings at time
  of generation, sorted for determinism. Normal runs suppress baseline entries
  and print their count. New findings (not in baseline) are warned/failed.
  Stale baseline entries (in baseline but no longer firing) are printed as
  'stale baseline entry — prune'.

Usage
-----
  python scripts/check_synapse_reads.py [--root PATH] [--write-baseline] [--selftest]

Options
-------
  --root PATH         Repo root (default: parent of scripts/).
  --write-baseline    Scan all files, write findings to baseline, exit 0.
  --selftest          Inject a synthetic module with an undeclared read and prove
                      both WARN and HARD FAIL findings are detected. Exit 0 on pass.

Article-2 surface→module mapping (money-path set):
  alert_triage     -> engine/alert_triage.py
  board_ordering   -> scripts/build_stock_library.py
  top_setups       -> scripts/build_site.py
  attention_queue  -> []  (future cortex/reflex modules; no module yet)
  push_floor       -> []  (future push-notification floor; no module yet)

Scan scope:
  engine/*.py, scripts/*.py, collectors/*.py
  Excludes: __pycache__, this script itself, check_synapse_registry.py

IMPORTANT HONESTY RULE: this is a LITERAL-PATH scan (string literals in source).
It does NOT trace runtime file-access paths, AST data-flow, or dynamic open()
calls. A module that builds a path via os.path.join() without a matching literal
will NOT be detected by v1. AST data-flow tracing is deferred to a later wave.

---

Horizon firewall (LH-R1, Long-Hold Thesis Masterplan W0)
---------------------------------------------------------
Every registered artifact carries horizon_role ∈ {tactical_entry, hold_thesis, dual, context}.
The firewall enforces bidirectional isolation between entry and hold horizons:

  Direction A — hold bleeds into entry:
    A hold_thesis artifact's scored_path_surfaces or consumers lists an entry
    Article-2 surface/module → HARD FAIL.

  Direction B — entry bleeds into hold:
    A tactical_entry artifact's scored_path_surfaces or consumers lists a
    hold-thesis surface/module (when hold surfaces are registered) → HARD FAIL.

  dual  → passes both directions (it has separate per-horizon calibrations; a
           notes field justifying dual use is required by the registry schema).
  context → passes both directions (horizon-agnostic descriptive/diagnostic).

The check operates on the registry declarations (scored_path_surfaces and
consumers fields), not on source-file literals, so it catches violations at
registration time before any code is written.

The hold-surface map mirrors the article2 map pattern but for hold-thesis
surfaces. It is empty now (first hold_thesis artifacts arrive in W1); entries
are added here when hold-thesis Article-2-equivalent surfaces are chartered.
"""
from __future__ import annotations

import argparse
import ast
import io
import json
import re
import sys
import textwrap
import tokenize
from pathlib import Path
from typing import NamedTuple

# Allow running as a standalone script from the repo root.  Unconditional: an
# already-present root further down sys.path still loses to a foreign package
# ahead of it, so this must pin position 0 every time (see scripts/__init__.py).
_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parent
sys.path.insert(0, str(_REPO_ROOT))

from engine.neuralweb.synapse import load_registry  # noqa: E402

# ---------------------------------------------------------------------------
# Article-2 surface → module mapping (money-path)
# ---------------------------------------------------------------------------
# Derived from synapse.yml meta.article2_surfaces. Each surface maps to the
# concrete module files that implement it.
# attention_queue -> [] (future cortex/reflex modules; no file yet)
# push_floor      -> [] (future push-notification reflex; no file yet)

_ARTICLE2_MAP: dict[str, list[str]] = {
    "alert_triage": ["engine/alert_triage.py"],
    "board_ordering": ["scripts/build_stock_library.py"],
    "top_setups": ["scripts/build_site.py"],
    "attention_queue": [],   # future cortex/reflex module — not yet created
    "push_floor": [],        # future push-notification floor — not yet created
}

# ---------------------------------------------------------------------------
# Horizon firewall maps (LH-R1)
# ---------------------------------------------------------------------------
# Entry Article-2 surface names (the "entry surface" side of the firewall).
# Derived from synapse.yml meta.article2_surfaces; held here as a set for
# fast membership tests in the horizon firewall check.
_ENTRY_ARTICLE2_SURFACES: frozenset[str] = frozenset(_ARTICLE2_MAP.keys())

# Entry Article-2 module paths — used when checking consumers lists.
_ENTRY_ARTICLE2_MODULES: frozenset[str] = frozenset(
    mod for mods in _ARTICLE2_MAP.values() for mod in mods
)

# Hold-thesis surface map (mirrors _ARTICLE2_MAP for the hold horizon).
# Empty now — first hold_thesis surfaces are chartered in W3 (PR-L/M).
# When a hold-thesis Article-2-equivalent surface is registered, add it here:
#   "long_hold_committee": ["scripts/build_site.py:long_thesis_section"]
_HOLD_SURFACE_MAP: dict[str, list[str]] = {}

_HOLD_SURFACE_NAMES: frozenset[str] = frozenset(_HOLD_SURFACE_MAP.keys())
_HOLD_SURFACE_MODULES: frozenset[str] = frozenset(
    mod for mods in _HOLD_SURFACE_MAP.values() for mod in mods
)

# ---------------------------------------------------------------------------
# Baseline path
# ---------------------------------------------------------------------------

_BASELINE_PATH_REL = "data/neuralweb/read_gate_baseline.json"

# ---------------------------------------------------------------------------
# Finding data structure
# ---------------------------------------------------------------------------


class Finding(NamedTuple):
    module: str       # repo-relative path, e.g. "engine/foo.py"
    artifact_id: str
    line_no: int
    severity: str     # "WARN" or "HARD"

    def as_dict(self) -> dict:
        return {
            "module": self.module,
            "artifact_id": self.artifact_id,
            "line_no": self.line_no,
            "severity": self.severity,
        }

    def baseline_key(self) -> tuple:
        """Stable sort key for baseline comparison (line_no excluded — files change)."""
        return (self.module, self.artifact_id)

    @classmethod
    def from_dict(cls, d: dict) -> "Finding":
        return cls(
            module=d["module"],
            artifact_id=d["artifact_id"],
            line_no=d.get("line_no", 0),
            severity=d["severity"],
        )


# ---------------------------------------------------------------------------
# Horizon firewall violation data structure (LH-R1)
# ---------------------------------------------------------------------------


class HorizonViolation(NamedTuple):
    """
    A registry-level horizon firewall violation.

    Unlike Finding (which is a source-scan finding), HorizonViolation is
    detected purely from the synapse.yml declarations — scored_path_surfaces
    and consumers — without reading any source files.

    direction:
      "hold_into_entry"  — a hold_thesis artifact routes to an entry surface
      "entry_into_hold"  — a tactical_entry artifact routes to a hold surface
    channel:
      "scored_path_surfaces"  — the artifact's scored_path_surfaces field
      "consumers"             — the artifact's consumers field
    surface_or_module:
      The offending surface name (for scored_path_surfaces) or module path
      (for consumers).
    """

    artifact_id: str
    artifact_role: str         # "hold_thesis" or "tactical_entry"
    direction: str             # "hold_into_entry" or "entry_into_hold"
    channel: str               # "scored_path_surfaces" or "consumers"
    surface_or_module: str     # the offending surface name or module path

    def as_dict(self) -> dict:
        return {
            "artifact_id": self.artifact_id,
            "artifact_role": self.artifact_role,
            "direction": self.direction,
            "channel": self.channel,
            "surface_or_module": self.surface_or_module,
        }

    def label(self) -> str:
        return (
            f"[HORIZON FIREWALL HARD FAIL] artifact={self.artifact_id!r} "
            f"role={self.artifact_role!r} direction={self.direction!r} "
            f"channel={self.channel!r} offender={self.surface_or_module!r}"
        )


# ---------------------------------------------------------------------------
# Path normalization helpers
# ---------------------------------------------------------------------------

_PLACEHOLDER_RE = re.compile(r"<[A-Z_]+>")


def _normalize_search_path(path: str) -> str:
    """
    For a registered artifact path, produce the string literal we search for.

    Per-ticker pattern paths (containing <SYM>-style placeholders) are
    reduced to their directory prefix, e.g.:
      "site/signals/<SYM>.json"  ->  "site/signals/"
    Plain paths are returned as-is.
    """
    m = _PLACEHOLDER_RE.search(path)
    if not m:
        return path
    # Strip from the first placeholder onward; keep the dir prefix including trailing /
    before = path[: m.start()]
    # Ensure we end at a directory boundary
    slash_pos = before.rfind("/")
    if slash_pos >= 0:
        return before[: slash_pos + 1]
    return before


# ---------------------------------------------------------------------------
# Prose masking — a MENTION is not a READ
# ---------------------------------------------------------------------------


def _blank_span(lines: list[str], span: tuple[int, int, int, int]) -> None:
    """Overwrite one (srow, scol, erow, ecol) span with spaces, in place.

    Equal-length replacement on purpose: every line keeps its length and the
    file keeps its line count, so the line numbers reported downstream stay the
    file's real ones and never need translating back.
    """
    srow, scol, erow, ecol = span
    if not (1 <= srow <= len(lines)) or not (1 <= erow <= len(lines)):
        return
    if srow == erow:
        line = lines[srow - 1]
        end = min(ecol, len(line))
        start = min(scol, end)
        lines[srow - 1] = line[:start] + " " * (end - start) + line[end:]
        return
    first = lines[srow - 1]
    start = min(scol, len(first))
    lines[srow - 1] = first[:start] + " " * (len(first) - start)
    for row in range(srow + 1, erow):
        lines[row - 1] = " " * len(lines[row - 1])
    last = lines[erow - 1]
    end = min(ecol, len(last))
    lines[erow - 1] = " " * end + last[end:]


def _prose_masked_source(source_text: str) -> str:
    """Return ``source_text`` with docstring and comment bodies blanked out.

    A registered artifact path that appears ONLY in prose is a MENTION, not a
    read. Docstrings in this repo routinely name the upstream store a function
    reasons about — ``scripts/build_stock_library.py::_name_score_asof`` explains
    a measured (date, ticker) join against ``data/name_score/us_calls.parquet``
    without ever opening it — and a raw substring scan read that sentence as an
    Article-2 money-path consumer and hard-failed the fleet on a paragraph
    (#5674's docstring; the read it describes lives in the grader).

    Masking is deliberately narrow. ONLY two things are blanked:

      * docstrings — the leading bare string expression of a module, class or
        function. A bare string statement is never a read by construction.
      * comments — never executed, so never a read.

    Every OTHER string literal still counts, including one merely assigned to a
    variable, so no real read can hide from this. The same distinction
    ``tests/test_render_builder_ownership.py`` already draws for render's
    builder closure ("comments that merely name another builder").

    Fails OPEN: a module that will not parse is returned UNCHANGED and is
    scanned exactly as before. A guard that cannot read a file must keep its old
    reach over it, never go quietly blind on it.
    """
    try:
        tree = ast.parse(source_text)
    except (SyntaxError, ValueError, RecursionError):
        return source_text

    lines = source_text.splitlines()
    if not lines:
        return source_text

    spans: list[tuple[int, int, int, int]] = []

    for node in ast.walk(tree):
        if not isinstance(
            node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)
        ):
            continue
        body = getattr(node, "body", None)
        if not body:
            continue
        first = body[0]
        if (
            isinstance(first, ast.Expr)
            and isinstance(first.value, ast.Constant)
            and isinstance(first.value.value, str)
            and first.value.end_lineno is not None
            and first.value.end_col_offset is not None
        ):
            const = first.value
            spans.append(
                (const.lineno, const.col_offset, const.end_lineno, const.end_col_offset)
            )

    try:
        for tok in tokenize.generate_tokens(io.StringIO(source_text).readline):
            if tok.type == tokenize.COMMENT:
                spans.append((tok.start[0], tok.start[1], tok.end[0], tok.end[1]))
    except (tokenize.TokenError, SyntaxError, IndentationError, ValueError):
        # Keep the docstring masking already collected; comments stay visible.
        pass

    for span in spans:
        _blank_span(lines, span)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Module discovery
# ---------------------------------------------------------------------------

_THIS_SCRIPT = Path(__file__).name
_REGISTRY_SCRIPT = "check_synapse_registry.py"


def _scan_dirs(root: Path) -> list[Path]:
    """Return all .py files in engine/, scripts/, collectors/ (excluding __pycache__)."""
    files: list[Path] = []
    for subdir in ("engine", "scripts", "collectors"):
        d = root / subdir
        if not d.is_dir():
            continue
        for f in sorted(d.rglob("*.py")):
            # Relative to the scan root `d`: an absolute-parts prune also matches
            # anything ABOVE the root, which silently skips every file when the
            # checkout path happens to contain the token (#3802).
            if "__pycache__" in f.relative_to(d).parts:
                continue
            if f.name in (_THIS_SCRIPT, _REGISTRY_SCRIPT):
                continue
            files.append(f)
    return files


# ---------------------------------------------------------------------------
# Article-2 module set builder
# ---------------------------------------------------------------------------


def _build_article2_modules(root: Path, reg: dict) -> set[str]:
    """
    Return the set of repo-relative module paths that are Article-2 surfaces.
    Derives the surface list from meta.article2_surfaces and looks them up in
    _ARTICLE2_MAP for the concrete file names.
    """
    surfaces = (reg.get("meta") or {}).get("article2_surfaces") or []
    modules: set[str] = set()
    for surface in surfaces:
        for mod in _ARTICLE2_MAP.get(surface, []):
            modules.add(mod)
    return modules


# ---------------------------------------------------------------------------
# Scanner core
# ---------------------------------------------------------------------------


def scan_findings(
    root: Path,
    reg: dict | None = None,
    extra_files: dict[str, str] | None = None,
) -> list[Finding]:
    """
    Scan for undeclared readers of registered artifacts.

    Parameters
    ----------
    root        : Repo root path.
    reg         : Parsed registry dict (loaded from synapse.yml if None).
    extra_files : Optional dict of {repo-relative-path: source_text} for
                  synthetic files (used by selftest and unit tests).
                  When provided, ONLY these files are scanned (not disk).

    Returns
    -------
    List of Finding objects, sorted by (module, artifact_id).
    """
    if reg is None:
        reg = load_registry(root)

    artifacts = reg.get("artifacts") or {}
    article2_modules = _build_article2_modules(root, reg)

    # Build per-artifact search config
    # Each entry: {artifact_id, search_path, producer_rel, declared_set, extra_writers_set}
    artifact_configs: list[dict] = []
    for art_id, entry in artifacts.items():
        if not isinstance(entry, dict):
            continue
        raw_path = entry.get("path", "")
        if not raw_path:
            continue

        search_path = _normalize_search_path(raw_path)

        # Registered producer (may include line reference like "engine/run.py:705")
        producer_raw = entry.get("producer", "") or ""
        producer_rel = producer_raw.split(":")[0].strip()

        # known_extra_writers: each entry is "scripts/foo.py — description"
        extra_writers: set[str] = set()
        for ew in (entry.get("known_extra_writers") or []):
            if isinstance(ew, str):
                mod = ew.split("—")[0].strip().split(" ")[0].strip()
                if mod:
                    extra_writers.add(mod)

        # declared consumers
        consumers: set[str] = set(entry.get("consumers") or [])

        artifact_configs.append({
            "artifact_id": art_id,
            "search_path": search_path,
            "producer_rel": producer_rel,
            "extra_writers": extra_writers,
            "consumers": consumers,
        })

    # Determine files to scan
    if extra_files is not None:
        # Synthetic mode: only scan the provided text
        file_iter: list[tuple[str, str]] = list(extra_files.items())
    else:
        # Real disk scan
        disk_files = _scan_dirs(root)
        file_iter = []
        for fp in disk_files:
            rel = str(fp.relative_to(root))
            try:
                text = fp.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            file_iter.append((rel, text))

    findings: list[Finding] = []

    for rel_path, source_text in file_iter:
        # Normalize path separators
        mod = rel_path.replace("\\", "/")

        # Scan CODE, not prose. Docstrings and comments are blanked (same offsets,
        # so line numbers below stay real) because a path named in a paragraph is a
        # MENTION, not a read — see _prose_masked_source. Unparseable files come
        # back unchanged and are scanned exactly as before.
        code_text = _prose_masked_source(source_text)

        for ac in artifact_configs:
            search_path = ac["search_path"]
            # Quick pre-check: path string present at all?
            if search_path not in code_text:
                continue

            # Skip registered producer
            if mod == ac["producer_rel"]:
                continue
            # Skip known extra writers
            if mod in ac["extra_writers"]:
                continue
            # Skip declared consumers
            if mod in ac["consumers"]:
                continue

            # Confirmed undeclared reader — find line numbers. Line-matching uses
            # the masked text too, so the reported line is a line of CODE and never
            # a paragraph that merely names the store.
            lines = code_text.splitlines()
            found_lines: list[int] = []
            for i, line in enumerate(lines, start=1):
                if search_path in line:
                    found_lines.append(i)

            if not found_lines:
                continue

            # Determine severity
            severity = "HARD" if mod in article2_modules else "WARN"

            # One finding per first match line (grouping by module+artifact)
            findings.append(
                Finding(
                    module=mod,
                    artifact_id=ac["artifact_id"],
                    line_no=found_lines[0],
                    severity=severity,
                )
            )

    # Sort deterministically
    findings.sort(key=lambda f: (f.module, f.artifact_id, f.line_no))
    return findings


# ---------------------------------------------------------------------------
# Baseline helpers
# ---------------------------------------------------------------------------


def _baseline_key(f: Finding) -> str:
    """Compact string key for baseline membership test."""
    return f"{f.module}|{f.artifact_id}"


def _load_baseline(root: Path) -> dict[str, dict] | None:
    """Load baseline from disk. Returns None if file doesn't exist."""
    bp = root / _BASELINE_PATH_REL
    if not bp.exists():
        return None
    with open(bp, encoding="utf-8") as fh:
        raw = json.load(fh)
    # Index by baseline_key for fast lookup
    return {f"{e['module']}|{e['artifact_id']}": e for e in raw.get("findings", [])}


def _write_baseline(root: Path, findings: list[Finding]) -> None:
    """Write findings to the baseline file, sorted for determinism."""
    bp = root / _BASELINE_PATH_REL
    bp.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "schema": "synapse-read-gate-baseline-v1",
        "description": (
            "Snapshot of all undeclared-reader findings at baseline generation time. "
            "Only-shrinks ratchet: new findings that do NOT appear here trigger "
            "WARN or HARD FAIL. Stale entries (no longer firing) are reported as "
            "'stale baseline entry — prune'."
        ),
        "findings": [f.as_dict() for f in sorted(findings, key=lambda f: (f.module, f.artifact_id, f.line_no))],
    }
    with open(bp, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2)
    print(f"baseline written: {bp} ({len(findings)} findings)")


# ---------------------------------------------------------------------------
# Output / annotation helpers
# ---------------------------------------------------------------------------


def _github_annotation(severity: str, path: str, line: int, message: str) -> str:
    level = "error" if severity == "HARD" else "warning"
    return f"::{level} file={path},line={line}::{message}"


def _report_findings(
    findings: list[Finding],
    baseline: dict[str, dict] | None,
    root: Path,
) -> tuple[int, int]:
    """
    Print findings and GitHub annotations; return (n_new_warn, n_new_hard).

    Baseline entries that no longer fire are printed as 'stale baseline entry — prune'.
    """
    n_suppressed = 0
    new_findings: list[Finding] = []

    fired_keys: set[str] = set()

    for f in findings:
        key = _baseline_key(f)
        fired_keys.add(key)
        if baseline is not None and key in baseline:
            n_suppressed += 1
        else:
            new_findings.append(f)

    # Print stale baseline entries
    if baseline is not None:
        for key, entry in sorted(baseline.items()):
            if key not in fired_keys:
                print(f"stale baseline entry — prune: {entry['module']} / {entry['artifact_id']}")

    if n_suppressed:
        print(f"  ({n_suppressed} baseline-suppressed finding(s) — run --write-baseline to update)")

    n_warn = 0
    n_hard = 0
    for f in new_findings:
        msg = (
            f"undeclared reader: {f.module!r} reads artifact {f.artifact_id!r} "
            f"(path literal) but is not declared as a consumer"
        )
        if f.severity == "HARD":
            msg += " [Article-2 HARD FAIL — money-path surface]"
            n_hard += 1
        else:
            n_warn += 1

        print(f"  [{f.severity}] {f.module}:{f.line_no} → {f.artifact_id}")
        print(f"         {msg}")
        print(_github_annotation(f.severity, f.module, f.line_no, msg))

    return n_warn, n_hard


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------

def _run_selftest(root: Path) -> int:
    """
    Inject synthetic module texts and prove WARN + HARD findings are detected.
    Returns 0 on pass, 1 on failure.
    """
    reg = load_registry(root)
    artifacts = reg.get("artifacts") or {}

    # Pick a real artifact with a non-pattern path to use as test target
    target_art_id: str | None = None
    target_path: str | None = None
    for art_id, entry in artifacts.items():
        if not isinstance(entry, dict):
            continue
        p = entry.get("path", "")
        if p and "<" not in p and "site/" not in p:  # prefer a data/ path
            target_art_id = art_id
            target_path = p
            break

    if target_art_id is None or target_path is None:
        print("selftest FAIL — could not find a suitable artifact for synthetic test")
        return 1

    print(f"selftest: using artifact {target_art_id!r} (path {target_path!r})")

    all_passed = True

    # ---- Test 1: undeclared reader -> WARN finding ----
    synthetic_warn = {
        "engine/_selftest_warn.py": textwrap.dedent(f"""\
            # synthetic undeclared reader — WARN
            import json
            path = "{target_path}"
            data = json.load(open(path))
        """),
    }
    warn_findings = scan_findings(root, reg=reg, extra_files=synthetic_warn)
    warn_match = any(
        f.artifact_id == target_art_id
        and f.severity == "WARN"
        and f.module == "engine/_selftest_warn.py"
        for f in warn_findings
    )
    status = "PASS" if warn_match else "FAIL"
    if not warn_match:
        all_passed = False
    print(f"  selftest [{status}] undeclared reader -> WARN (module not in Article-2)")
    if not warn_match:
        print(f"    findings returned: {warn_findings}")

    # ---- Test 2: Article-2 surface undeclared reader -> HARD finding ----
    # Use a module path that IS in our article2 map
    # alert_triage is an Article-2 surface mapped to engine/alert_triage.py
    article2_mod = "engine/alert_triage.py"
    # Check the artifact is NOT already declared as consumer in alert_triage
    target_entry = artifacts.get(target_art_id, {})
    declared_consumers = set(target_entry.get("consumers") or [])
    # If alert_triage is already a declared consumer, pick a different artifact
    art2_target_id = target_art_id
    art2_target_path = target_path
    if article2_mod in declared_consumers:
        for art_id, entry in artifacts.items():
            if not isinstance(entry, dict):
                continue
            p = entry.get("path", "")
            if p and "<" not in p and "site/" not in p:
                consumers_here = set(entry.get("consumers") or [])
                if article2_mod not in consumers_here and art_id != art2_target_id:
                    producer = (entry.get("producer") or "").split(":")[0].strip()
                    if article2_mod != producer:
                        art2_target_id = art_id
                        art2_target_path = p
                        break

    synthetic_hard = {
        article2_mod: textwrap.dedent(f"""\
            # synthetic undeclared reader in Article-2 surface — HARD
            import json
            path = "{art2_target_path}"
            data = json.load(open(path))
        """),
    }
    hard_findings = scan_findings(root, reg=reg, extra_files=synthetic_hard)
    hard_match = any(
        f.artifact_id == art2_target_id
        and f.severity == "HARD"
        and f.module == article2_mod
        for f in hard_findings
    )
    status = "PASS" if hard_match else "FAIL"
    if not hard_match:
        all_passed = False
    print(f"  selftest [{status}] Article-2 undeclared reader -> HARD (engine/alert_triage.py)")
    if not hard_match:
        print(f"    target: artifact={art2_target_id!r} path={art2_target_path!r}")
        print(f"    findings returned: {hard_findings}")

    # ---- Test 3: declared consumer -> clean ----
    # Build a synthetic file for a declared consumer of target_art_id
    # Use the first declared consumer that starts with "engine/" or "scripts/"
    declared_consumer_mod: str | None = None
    for cons in declared_consumers:
        if cons.startswith(("engine/", "scripts/")):
            declared_consumer_mod = cons
            break

    if declared_consumer_mod:
        synthetic_clean = {
            declared_consumer_mod: textwrap.dedent(f"""\
                # synthetic declared consumer — should produce no finding
                import json
                path = "{target_path}"
                data = json.load(open(path))
            """),
        }
        clean_findings = scan_findings(root, reg=reg, extra_files=synthetic_clean)
        clean_match = not any(
            f.artifact_id == target_art_id and f.module == declared_consumer_mod
            for f in clean_findings
        )
        status = "PASS" if clean_match else "FAIL"
        if not clean_match:
            all_passed = False
        print(f"  selftest [{status}] declared consumer -> clean (no finding for {declared_consumer_mod!r})")
    else:
        print("  selftest [SKIP] declared consumer -> clean (no engine/scripts consumer available)")

    print()
    if all_passed:
        print("selftest PASSED — all synthetic cases handled correctly")
        return 0
    else:
        print("selftest FAILED — one or more synthetic cases not caught")
        return 1


# ---------------------------------------------------------------------------
# Horizon firewall checker (LH-R1)
# ---------------------------------------------------------------------------


def check_horizon_firewall(reg: dict) -> list[HorizonViolation]:
    """
    Inspect the registry and return all horizon firewall violations.

    The check is registry-declaration-level (scored_path_surfaces + consumers
    fields), not a source-file scan. It detects violations at the point of
    registration — before any code is written to implement the dependency.

    Rules (per LH-R1):
      - hold_thesis artifact → entry Article-2 surface or entry module: VIOLATION
      - tactical_entry artifact → hold-thesis surface or hold module: VIOLATION
      - dual artifact: PASSES both directions (bidirectional by design)
      - context artifact: PASSES both directions (horizon-agnostic)

    Returns sorted list of HorizonViolation (deterministic order).
    """
    artifacts = reg.get("artifacts") or {}
    violations: list[HorizonViolation] = []

    for art_id, entry in artifacts.items():
        if not isinstance(entry, dict):
            continue

        role = entry.get("horizon_role", "")

        # dual and context are exempt — they may appear in any surface.
        if role in ("dual", "context"):
            continue

        scored_surfaces: list[str] = list(entry.get("scored_path_surfaces") or [])
        consumers: list[str] = list(entry.get("consumers") or [])

        if role == "hold_thesis":
            # Direction A: hold bleeding into entry surfaces.
            for surface in scored_surfaces:
                if surface in _ENTRY_ARTICLE2_SURFACES:
                    violations.append(
                        HorizonViolation(
                            artifact_id=art_id,
                            artifact_role=role,
                            direction="hold_into_entry",
                            channel="scored_path_surfaces",
                            surface_or_module=surface,
                        )
                    )
            for consumer_mod in consumers:
                # Normalize: strip line references (e.g. "engine/foo.py:123")
                mod = consumer_mod.split(":")[0].strip()
                if mod in _ENTRY_ARTICLE2_MODULES:
                    violations.append(
                        HorizonViolation(
                            artifact_id=art_id,
                            artifact_role=role,
                            direction="hold_into_entry",
                            channel="consumers",
                            surface_or_module=mod,
                        )
                    )

        elif role == "tactical_entry":
            # Direction B: entry bleeding into hold surfaces.
            for surface in scored_surfaces:
                if surface in _HOLD_SURFACE_NAMES:
                    violations.append(
                        HorizonViolation(
                            artifact_id=art_id,
                            artifact_role=role,
                            direction="entry_into_hold",
                            channel="scored_path_surfaces",
                            surface_or_module=surface,
                        )
                    )
            for consumer_mod in consumers:
                mod = consumer_mod.split(":")[0].strip()
                if mod in _HOLD_SURFACE_MODULES:
                    violations.append(
                        HorizonViolation(
                            artifact_id=art_id,
                            artifact_role=role,
                            direction="entry_into_hold",
                            channel="consumers",
                            surface_or_module=mod,
                        )
                    )

    violations.sort(key=lambda v: (v.artifact_id, v.direction, v.channel, v.surface_or_module))
    return violations


def _report_horizon_violations(violations: list[HorizonViolation]) -> int:
    """
    Print horizon firewall violations and GitHub annotations; return count.
    All violations are HARD FAIL — there is no warn tier for the firewall.
    """
    for v in violations:
        print(v.label())
        annotation_msg = (
            f"horizon firewall: {v.artifact_role!r} artifact {v.artifact_id!r} "
            f"routes to {v.direction.replace('_', '-')} surface {v.surface_or_module!r} "
            f"via {v.channel!r}"
        )
        print(f"::error ::{annotation_msg}")
    return len(violations)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=_REPO_ROOT,
        help="Repo root (default: parent of scripts/)",
    )
    parser.add_argument(
        "--write-baseline",
        action="store_true",
        help="Scan and write ALL findings to the baseline file, then exit 0",
    )
    parser.add_argument(
        "--selftest",
        action="store_true",
        help="Run self-test with synthetic files; exit 0 on pass",
    )
    args = parser.parse_args()

    root = args.root.resolve()

    if args.selftest:
        print("Running synapse read-gate self-test...")
        return _run_selftest(root)

    # Load registry
    try:
        reg = load_registry(root)
    except FileNotFoundError as exc:
        print(f"[ERROR] {exc}")
        return 1

    # --- Horizon firewall check (LH-R1) always runs before the literal scan ---
    fw_violations = check_horizon_firewall(reg)
    n_fw_violations = _report_horizon_violations(fw_violations)
    if n_fw_violations > 0:
        print(
            f"\nhorizon-firewall HARD FAIL: {n_fw_violations} cross-horizon registry "
            f"violation(s) [LH-R1 — research/LONG_HOLD_THESIS_MASTERPLAN_BY_FABLE.md].\n"
            f"Entry (~2-4wk) and hold-thesis (~12-36mo) horizons must remain mechanically "
            f"separated at the registry level.\n"
            f"Fix options: (a) correct the horizon_role stamp on the offending artifact, or "
            f"(b) remove the cross-horizon surface/consumer entry from config/synapse.yml, or "
            f"(c) reclassify the artifact as 'dual' if both horizons are genuinely intended "
            f"(requires a 'notes' field explaining the dual use)."
        )
        return 1
    else:
        n_hold = sum(
            1 for v in (reg.get("artifacts") or {}).values()
            if isinstance(v, dict) and v.get("horizon_role") == "hold_thesis"
        )
        n_entry = sum(
            1 for v in (reg.get("artifacts") or {}).values()
            if isinstance(v, dict) and v.get("horizon_role") == "tactical_entry"
        )
        print(
            f"horizon-firewall CLEAN — {n_hold} hold_thesis artifact(s), "
            f"{n_entry} tactical_entry artifact(s); no cross-horizon violations"
        )

    # Scan
    findings = scan_findings(root, reg=reg)

    if args.write_baseline:
        _write_baseline(root, findings)
        return 0

    # Load baseline
    baseline = _load_baseline(root)

    n_artifacts = len(reg.get("artifacts") or {})
    print(
        f"synapse read-gate: scanned {n_artifacts} artifacts "
        f"({len(findings)} total finding(s))"
    )

    if not findings and baseline is None:
        print("read-gate CLEAN — no undeclared readers found (no baseline)")
        return 0

    n_warn, n_hard = _report_findings(findings, baseline, root)

    if n_hard > 0:
        print(
            f"\nread-gate HARD FAIL: {n_hard} Article-2 money-path undeclared reader(s). "
            f"Declare them as consumers in config/synapse.yml to pass."
        )
        return 1

    if n_warn > 0:
        print(
            f"\nread-gate WARN: {n_warn} undeclared reader(s) (warn tier — exit 0). "
            f"Declare them as consumers in config/synapse.yml to suppress."
        )
    else:
        print("read-gate CLEAN — all findings are baseline-suppressed")

    return 0


if __name__ == "__main__":
    sys.exit(main())
