#!/usr/bin/env python3
"""Rasterize the committed annotation-grammar sample SVGs to PNG.

The SVG fixtures under ``tests/fixtures/chart_render/`` are regenerated by
``CHART_GRAMMAR_REGEN=1 python -m pytest tests/test_chart_render_grammar.py``.
This script turns the ones an operator should LOOK at into PNGs committed next
to them, which is what gets embedded in the PR body — charts are user-facing
surfaces and the masterplan's §0.1 gate is "rendered PNG crops posted in the PR
body", not "the tests are green".

Usage:
    python -m scripts.dev_render_chart_grammar_pngs            # the PR-body set
    python -m scripts.dev_render_chart_grammar_pngs --all      # every sample

Needs headless Chrome (chart_render.rasterize_svg). Fail-soft by design: no
Chrome ⇒ it says so and exits non-zero rather than writing an empty file.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from engine.marketing.chart_render import find_chrome, rasterize_svg  # noqa: E402

FIXTURES = ROOT / "tests" / "fixtures" / "chart_render"

# The four the operator reviews: the full composite plus three primitives whose
# technique is hardest to judge from a diff (discs, the receipt box, the
# claim-unit sub-panes).
PR_BODY_SET = (
    "composite_weekly",
    "spotlights",
    "measure_box",
    "panes_streak_squeeze",
)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--all", action="store_true",
                    help="rasterize every sample, not just the PR-body set")
    ap.add_argument("--scale", type=int, default=1,
                    help="device pixel ratio (default 1 — these are review "
                         "artifacts, not posted media)")
    args = ap.parse_args()

    if find_chrome() is None:
        print("no headless Chrome found — cannot rasterize", file=sys.stderr)
        return 2

    names = ([p.stem for p in sorted(FIXTURES.glob("*.svg"))] if args.all
             else list(PR_BODY_SET))
    rc = 0
    for name in names:
        src = FIXTURES / f"{name}.svg"
        if not src.exists():
            print(f"missing {src.name} — run the test suite with "
                  f"CHART_GRAMMAR_REGEN=1 first", file=sys.stderr)
            rc = 1
            continue
        png = rasterize_svg(src.read_text(encoding="utf-8"), scale=args.scale)
        if not png:
            print(f"raster failed for {name}", file=sys.stderr)
            rc = 1
            continue
        dest = FIXTURES / f"{name}.png"
        dest.write_bytes(png)
        print(f"{dest.relative_to(ROOT)}  {len(png):,} bytes")
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
