"""S&P / Macro Vector — Phase 0 honest-baseline harness.

The HARD GATE before any signal work (research/SP_VECTOR_VIABILITY.md §9):
reproduce the dumb-baseline numbers with the cash leg credited, so every later
candidate signal can be measured against them net-of-cost out-of-sample.

Baselines (all long/flat, alloc in [0,1], next-bar, bill carry on the flat sleeve):
  - buy & hold          (the benchmark to beat)
  - 200-day SMA switch  (Faber's naive timer at a daily cadence)
  - net-liquidity gate  (flat only when WALCL-RRP-TGA RoC is contracting)
  - 200dma + liquidity  (Growth-Trend-Timing-style double-confirm reference)

Run:
  python -m scripts.spvector_baseline                # scorecard + report
  python -m scripts.spvector_baseline --fetch-gspc   # first pull ^GSPC -> 1927

Writes reports/spvector-baseline.md. No commit, no site build — pure harness.
"""
from __future__ import annotations

import sys

import pandas as pd
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

from engine import equity_alloc as ea  # noqa: E402
from lib import config, store  # noqa: E402

COST_BPS = 3.0                       # liquid index ETF one-way (SPY/QQQ ~1-3 bps)
INDICES = ["SPY", "_DJI", "_RUT", "_GSPC"]   # _GSPC = ^GSPC long backbone (price index)
# SCENARIO ASSUMPTION — not a tax ruling. Symbolic rate for the after-tax
# sensitivity row.  Change this constant to run alternative scenarios;
# outputs change proportionally but are not tax advice.  Default preserved
# at 0.35 so existing report outputs are unchanged.  (RUL-F3.10)
ST_TAX = 0.35


def fetch_gspc() -> pd.DataFrame:
    """Pull ^GSPC daily to 1927 via yfinance and upsert to data/yahoo/_GSPC.parquet
    — roughly triples the independent-bear count (~4 -> ~12-14), the single biggest
    lever on confidence. ^GSPC is a PRICE index (no dividends); use SPY for the
    modern total-return path, ^GSPC for episode-counting / long-history context."""
    import yfinance as yf
    raw = yf.download("^GSPC", period="max", auto_adjust=True, progress=False)
    if raw is None or raw.empty:
        raise RuntimeError("empty ^GSPC response")
    if isinstance(raw.columns, pd.MultiIndex):
        raw.columns = raw.columns.get_level_values(0)
    keep = [c for c in ("Close", "Volume") if c in raw.columns]
    sub = raw[keep].rename(columns={"Close": "close", "Volume": "volume"}).dropna(subset=["close"])
    sub.index = pd.to_datetime(sub.index)
    store.upsert("yahoo", "^GSPC", sub)
    print(f"[fetch] ^GSPC -> _GSPC.parquet : {len(sub)} rows {sub.index.min().date()}..{sub.index.max().date()}")
    return sub


def _row(s: dict) -> str:
    return (f"| {s['label']:<20} | {s['cagr']:>6} | {s['cagr_nocarry']:>6} | "
            f"{s['sharpe']:>5} | {s['sortino']:>5} | {s['maxdd']:>6} | "
            f"{s['time_in_market']:>5} | {s['turnover_annual']:>5} | {s['final_mult']:>6} |")


def run_index(ticker: str, bills: pd.Series) -> tuple[list[dict], list[str]]:
    close = ea.index_close(ticker)
    strategies = {
        "buy & hold": ea.buy_hold(close),
        "200dma switch": ea.sma_switch(close, 200),
        "net-liquidity gate": ea.liquidity_gate(close),
        "200dma + liquidity": ea.sma_liquidity(close, 200),
    }
    rows = [ea.summarize(close, alloc, label, cash_yield=bills, cost_bps=COST_BPS,
                         bootstrap=(label in ("200dma switch", "net-liquidity gate")))
            for label, alloc in strategies.items()]
    lines = [f"\n### {ticker}  ({rows[0]['years']}yr, cost {COST_BPS}bps one-way, cash credited at DTB3)\n",
             "| strategy | CAGR% | CAGR(no carry) | Sharpe | Sortino | MaxDD% | %inMkt | turn/yr | wealth× |",
             "|---|--:|--:|--:|--:|--:|--:|--:|--:|"]
    lines += [_row(s) for s in rows]
    if ticker == "_GSPC":
        lines.append("\n> ⚠️ `_GSPC` (^GSPC) is a PRICE index — no dividends. Buy & hold here understates "
                     "total return by ~2-4%/yr while the switch's cash sleeve earns REAL bill carry, so the "
                     "apparent CAGR-beat is a dividend-omission artifact. Use `_GSPC` for DRAWDOWN, "
                     "episode-counting and Sharpe-SHAPE only; the honest CAGR benchmark is SPY (total-return).")
    # bootstrap CIs
    for s in rows:
        bc = s.get("bootstrap")
        if bc:
            lines.append(f"\n- `{s['label']}` block-bootstrap 95% CI — Sharpe {bc.get('sharpe_ci')}, "
                         f"MaxDD% {bc.get('maxdd_ci_pct')}, P(Sharpe>0)={bc.get('sharpe_gt0_prob')}")
    return rows, lines


def main() -> int:
    if "--fetch-gspc" in sys.argv:
        fetch_gspc()

    bills = ea.bill_yield()
    print(f"[data] bill yield {bills.index.min().date()}..{bills.index.max().date()} "
          f"(last {bills.iloc[-1]:.2f}%)")

    md = ["# S&P / Macro Vector — Phase 0 baseline scorecard",
          "",
          "*Generated by `scripts/spvector_baseline.py`. The dumb-baseline gate: every later "
          "candidate signal must beat these net-of-cost, out-of-sample, on Sharpe AND MaxDD.*",
          "",
          "Allocation is long/flat (alloc in [0,1]), acts next-bar (no look-ahead). The flat "
          "sleeve earns the prevailing 3-mo T-bill yield (DTB3); `CAGR(no carry)` strips it so "
          "the rate-regime-dependent carry is transparent. Buy & hold stays all-equity."]

    all_rows: dict[str, list[dict]] = {}
    for tkr in INDICES:
        try:
            rows, lines = run_index(tkr, bills)
            all_rows[tkr] = rows
            md += lines
            print("\n".join(lines))
        except FileNotFoundError as e:
            print(f"[skip] {tkr}: {e}")
            md.append(f"\n### {tkr}\n_skipped — {e}_")

    # after-tax sensitivity (SPY 200dma — the headline taxable-account warning)
    md += ["", "## After-tax sensitivity (taxable account, SPY 200dma switch)", ""]
    try:
        spy = ea.index_close("SPY")
        at = ea.after_tax(spy, ea.sma_switch(spy, 200), bills, st_rate=ST_TAX, cost_bps=COST_BPS)
        line = (f"At a {int(at['st_rate']*100)}% short-term rate, the 200dma switch nets "
                f"**{at['after_tax_cagr']}% after-tax CAGR ({at['after_tax_final_mult']}× wealth)** vs "
                f"buy & hold **{at['hodl_cagr']}% ({at['hodl_final_mult']}×)** — buy & hold defers all "
                f"equity tax. Cumulative tax paid ≈ {at['cumulative_tax_paid_x']}× initial capital. "
                f"_Approximate model — a sensitivity, not the gate._")
        md += [line]
        print("\n" + line)
    except Exception as e:  # noqa: BLE001
        md.append(f"_after-tax skipped: {e}_")
        print(f"[skip] after-tax: {e}")

    # honest-N: independent bear episodes per index (the true sample size)
    md += ["", "## Honest-N — independent bear episodes (the true sample size for a switch)", "",
           "| index | history | ≥20% bears | ≥15% bears |", "|---|---|--:|--:|"]
    print("\n--- Honest-N: independent bear episodes ---")
    for tkr in INDICES:
        try:
            close = ea.index_close(tkr)
            b20 = ea.bear_episodes(close, 0.20)
            b15 = ea.bear_episodes(close, 0.15)
            span = f"{close.index.min().date()}-{close.index.max().date()}"
            md.append(f"| {tkr} | {span} | {len(b20)} | {len(b15)} |")
            detail = ", ".join("{}({}%)".format(e["trough"][:7], e["drawdown_pct"]) for e in b20)
            print(f"{tkr:<6} {span}  >=20%: {len(b20)}  >=15%: {len(b15)}  | {detail}")
        except FileNotFoundError as e:
            md.append(f"| {tkr} | — | — | — |  _{e}_")
    md += ["", "_The episode count — not the row count — governs overfitting: a get-out/"
           "get-back-in switch gets one near-binary draw per bear. SPY's ~4 independent ≥20% "
           "bears is why any single-config CAGR beat is suspect; ^GSPC (_GSPC) to 1927 lifts the "
           "count to the only level that materially moves confidence._"]

    out = config.ROOT / config.load()["storage"]["reports_dir"] / "spvector-baseline.md"
    out.write_text("\n".join(md) + "\n")
    print(f"\n[report] {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
