"""IBKR securities-lending collector — borrow FEE and lendable AVAILABILITY.

Interactive Brokers publishes its shortable-stock file keylessly over anonymous
FTP, refreshed every ~15 minutes through the session:

    ftp://shortstock:@ftp2.interactivebrokers.com/usa.txt
    #BOF|<YYYY.MM.DD>|<HH:MM:SS>                     <- IBKR stamp, US/Eastern
    #SYM|CUR|NAME|CON|ISIN|REBATERATE|FEERATE|AVAILABLE|FIGI|
    ZYME|USD|Zymeworks|...|3.2351|0.3949|1900000|BBG019XSYC89|

`fee_pct` is the indicative annualised borrow fee; `avail_shares` is the lendable
quantity IBKR can currently source. Together they are the two short-side inputs
the house has never had: the bi-monthly FINRA snapshot says how much is *already*
short, this says what it *costs* to add and whether there is anything left to
borrow. Measured on 2026-08-05: 19,475 US symbols carry a fee, median 1.22%,
p90 17.9%, p99 176% — the long hard-to-borrow tail the literature prices.

WHY THIS COLLECTOR IS TIME-CRITICAL. There is no history and no backfill: IBKR
serves only the live snapshot. Every day this does not run is a day of borrow
data that can never be recovered. Unlike the FINRA short-interest API (which
serves settlements back to 2018-01-12 and so can be rebuilt at will), the borrow
panel can only ever accrue forward from first capture.

PIT CONTRACT + STORAGE SHAPE. The file mutates intraday, so a row is only
meaningful with the capture time attached. We take ONE snapshot per run and write
it to its OWN immutable file, data/ibkr_borrow/daily/<YYYY-MM-DD>.parquet.
`snapshot_et` records the #BOF clock so a consumer can verify captures are
comparable rather than assuming they are.

One-file-per-date is deliberate and is a git constraint, not a style choice. A
single rolling panel.parquet would be rewritten every night, so git would store a
complete new ~220KB→56MB blob on each of ~252 commits a year — gigabytes of churn
for an append-only capture. Per-date files are written once and never touched
again: ~56MB a year total, no rewrite churn. Same shape as
data/sec_insider/panel/<quarter>.parquet. These files ARE committed — like
data/hk_shorts/, they cannot be regenerated by re-scraping, so leaving them
Mac-local would put the whole accrual one disk failure from zero.

BORROW FEE IS NEAR-CONSTANT IN OUR UNIVERSE — measured, not assumed. On the
2026-08-05 snapshot the full file runs median 1.10% with 50.9% of names at or
above 1%; our covered universe runs median 0.35% with 18 of 1,519 names (1.2%)
at or above 1%, exactly one above 5%, and none above 20%. The entire borrow-fee
cross-section the literature prices lives in the ~9.7k hard-to-borrow names we do
NOT cover. So within our universe this is a RARE-EVENT FLAG (a large-cap crossing
into hard-to-borrow is real and informative), never a continuous ranking input —
the same structural-constancy trap already filed against single-name gamma_regime
(audit #29). Any consumer that z-scores fee across our universe alone is scoring
noise around a flat line.

That measurement drives the capture rule: we keep our universe UNION every name
at or above HTB_FEE_PCT, whatever its membership. The out-of-universe tail is
what gives the flag a real reference distribution to be rare *against*, and it is
the half that would be unrecoverable if we ever widen coverage. ~11k rows/day.

Display/context tier only. Borrow fee is a well-documented *bearish* cross-
sectional signal (expensive-to-borrow names underperform), and the same
literature shows the long/short version of that edge is eaten by the borrow fee
itself — so this feeds avoid/de-risk context, never a scored alpha leg and never
a short recommendation. See research/short_side/SP1_SHORT_PRESSURE_PREREG.md.
"""
from __future__ import annotations

import logging
import re
import urllib.request
from datetime import datetime, timezone

import pandas as pd

from collectors.base import Adapter, is_connection_error
from lib import config

log = logging.getLogger(__name__)

# ftp2 is the host that answers; ftp3 is IBKR's documented alias and is kept as a
# fallback because reachability differs by network egress (ftp3 times out from the
# Mac Studio, but may resolve from a hosted runner).
HOSTS = ("ftp2.interactivebrokers.com", "ftp3.interactivebrokers.com")
PATH = "/usa.txt"
GROUP = "ibkr_borrow"
TIMEOUT = 90

# IBKR reports "more than ten million lendable" as a literal token rather than a
# number. Coercing it to 10_000_000 would invent a precise tightness reading for
# exactly the names that are NOT tight; coercing it to NaN would drop the general-
# collateral majority out of every panel. It gets its own boolean instead.
UNLIMITED = ">10000000"

# The file carries bonds and non-US lines (CUSIP-shaped symbols like 049323AB4,
# a handful of EUR/CAD rows). Equity tickers are letters plus . and - only.
_TICKER_RE = re.compile(r"^[A-Z][A-Z.\-]{0,7}$")

# Names at/above this fee are kept regardless of universe membership — see the
# structural-constancy note in the module docstring. 1% is ~the full file's median
# and ~the 99th percentile of our own universe, i.e. the point where "expensive to
# borrow" stops being general collateral and starts being a statement.
HTB_FEE_PCT = 1.0


def _daily_dir():
    return config.data_dir() / GROUP / "daily"


def _daily_path(d) -> object:
    return _daily_dir() / f"{pd.Timestamp(d).date()}.parquet"


def load_panel(since=None) -> pd.DataFrame:
    """Concatenate the per-date captures into one frame. `since` limits the read
    to recent files so a consumer that only needs the latest snapshot does not
    pay for years of history."""
    d = _daily_dir()
    if not d.exists():
        return pd.DataFrame()
    files = sorted(d.glob("*.parquet"))
    if since is not None:
        cut = str(pd.Timestamp(since).date())
        files = [f for f in files if f.stem >= cut]
    frames = []
    for f in files:
        try:
            frames.append(pd.read_parquet(f))
        except Exception as e:  # noqa: BLE001 — one bad capture must not blind the rest
            log.warning("ibkr_borrow: unreadable capture %s (%s)", f, e)
    return pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()


def _universe_tickers() -> set[str]:
    """Our covered names, read from the breadth close-caches — same lean filter
    collectors/finra_short_volume.py uses. Empty set -> keep every equity row."""
    out: set[str] = set()
    for grp in ("breadth", "smallcap_breadth", "midcap_breadth"):
        p = config.data_dir() / grp / "_closes_cache.parquet"
        if p.exists():
            try:
                out.update(str(c) for c in pd.read_parquet(p).columns)
            except Exception:  # noqa: BLE001 — best-effort filter
                continue
    return out


def _fetch_text() -> str:
    last: Exception | None = None
    for host in HOSTS:
        url = f"ftp://shortstock:@{host}{PATH}"
        try:
            with urllib.request.urlopen(url, timeout=TIMEOUT) as r:
                return r.read().decode("utf-8", "replace")
        except Exception as e:  # noqa: BLE001
            log.debug("ibkr_borrow: %s unreachable (%s)", host, e)
            last = e
    raise ConnectionError(f"ibkr_borrow: no IBKR host reachable ({last})")


def _parse(text: str) -> tuple[pd.DataFrame, str | None]:
    """Parse one usa.txt snapshot -> (rows, '#BOF' ET timestamp).

    Fields are read from the RIGHT (`f[-3]` etc.) because NAME is free text and a
    pipe inside it would shift every positional index after it. Measured on the
    live file every row has exactly 9 pipes, but reading from the right costs
    nothing and cannot be broken by a future issuer name containing one.
    """
    rows: list[dict] = []
    stamp = snap_date = None
    for line in text.splitlines():
        if line.startswith("#BOF"):
            parts = line.split("|")
            if len(parts) >= 3:
                snap_date, stamp = parts[1].replace(".", "-"), parts[2]
            continue
        if line.startswith("#") or not line.strip():
            continue
        f = line.split("|")
        if len(f) < 9:
            continue
        sym, cur = f[0].strip().upper(), f[1].strip().upper()
        if cur != "USD" or not _TICKER_RE.match(sym):
            continue
        avail_raw = f[-3].strip()
        rows.append({
            "ticker": sym,
            "rebate_pct": _num(f[-5]),
            "fee_pct": _num(f[-4]),
            "avail_shares": float(avail_raw) if avail_raw.isdigit() else float("nan"),
            "avail_unlimited": avail_raw == UNLIMITED,
        })
    df = pd.DataFrame(rows)
    if not df.empty and snap_date:
        df["date"] = pd.Timestamp(snap_date)
        df["snapshot_et"] = stamp
    return df, stamp


def _num(s: str) -> float:
    try:
        return float(s.strip())
    except (ValueError, AttributeError):
        return float("nan")


class IbkrBorrowAdapter(Adapter):
    name = "ibkr_borrow"
    group = GROUP
    stale_after_days = 4          # daily feed; tolerate weekends/holidays

    def fetch(self, full_history: bool = False) -> dict[str, pd.DataFrame]:
        try:
            text = _fetch_text()
        except Exception as e:
            if is_connection_error(e) or isinstance(e, ConnectionError):
                raise
            raise
        fresh, stamp = _parse(text)
        if fresh.empty or "date" not in fresh.columns:
            raise RuntimeError("ibkr_borrow: snapshot parsed to 0 usable rows")

        universe = _universe_tickers()
        if universe:
            # universe UNION the hard-to-borrow tail. Filtering to the universe
            # alone would retain 18 of 9,686 HTB names (0.2%) and leave the flag
            # with no cross-section to be rare against.
            keep = fresh["ticker"].isin(universe) | (fresh["fee_pct"] >= HTB_FEE_PCT)
            fresh = fresh[keep]
            fresh = fresh.assign(in_universe=fresh["ticker"].isin(universe))
        else:
            fresh = fresh.assign(in_universe=True)
        if fresh.empty:
            raise RuntimeError("ibkr_borrow: no universe overlap in snapshot")

        # A ticker can appear once per snapshot; guard anyway so a duplicated
        # listing line cannot silently double a date's row count.
        fresh = fresh.drop_duplicates(subset=["date", "ticker"], keep="last")

        last = fresh["date"].max()
        path = _daily_path(last)
        path.parent.mkdir(parents=True, exist_ok=True)
        # One immutable file per capture date. A same-day re-run overwrites only
        # today's file with the newer snapshot; every PRIOR date is never touched
        # or rewritten — that is both the PIT guarantee and the reason git does
        # not accumulate a full-panel blob per night.
        fresh = fresh.sort_values("ticker").reset_index(drop=True)
        fresh.to_parquet(path, index=False)
        fee = fresh["fee_pct"].dropna()
        in_uni = fresh[fresh["in_universe"]]
        n_captures = len(list(_daily_dir().glob("*.parquet")))
        log.info("ibkr_borrow: %d names @ %s (ET %s) — %d in-universe, %d HTB tail; "
                 "%d captures on disk; fee median %.2f%% p90 %.2f%%; "
                 "in-universe fee>=%.0f%%: %d; %d unlimited-avail",
                 len(fresh), last.date(), stamp, len(in_uni), len(fresh) - len(in_uni),
                 n_captures,
                 fee.median() if len(fee) else float("nan"),
                 fee.quantile(0.9) if len(fee) else float("nan"),
                 HTB_FEE_PCT, int((in_uni["fee_pct"] >= HTB_FEE_PCT).sum()),
                 int(fresh["avail_unlimited"].sum()))
        hb = pd.DataFrame({"names": [len(fresh)],
                           "fee_median": [float(fee.median()) if len(fee) else float("nan")],
                           "captured_utc": [datetime.now(timezone.utc).isoformat(timespec="seconds")]},
                          index=[last])
        return {"ibkr_borrow__snapshot": hb}


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    IbkrBorrowAdapter().fetch()
