/* ═══════════════════════════════════════════════════════════════════════════
   LIVE ENTRY RADAR — W8 reference fixtures
   SYNTHETIC / REFERENCE ONLY. Not a live evaluator payload. Not production.
   Every row carries synthetic:true. Tickers are REF.* / FIX.* demo names.
   W6 Research Priority and W7 Opportunity are NEVER numeric here.
   ═══════════════════════════════════════════════════════════════════════════ */
window.RADAR_META = {
  synthetic: true,
  authority: "REFERENCE ONLY — no production UI deployment",
  workstream: "WS:LIVE-ENTRY-RADAR",
  wave: "W8",
  pinned_prophet_merge: "168a9be006914441051cff393927ce465e39138e",
  pinned_prophet_tree: "d540f493a097cb37f3f91e4c7bc81a39b876d069",
  origin_main_at_pin: "cc6f53f619f439683a4da7aa366843aef6079768",
  asof: "2026-08-15T13:55:00Z",
  session: "RTH",
  session_label_en: "US cash session · open",
  session_label_zh: "美股现金时段 · 开市",
  evaluator: "degraded", /* default board is healthy; state=degraded flips this */
  freshness_s: 240,
  probe_set: 42,
  note_en: "All names, prices, and episodes on this page are synthetic reference fixtures.",
  note_zh: "本页全部名称、价格与情节均为合成参考夹具，不是实盘。",
};

/* Expert identities — never flatten. C4 cannot fire. */
window.RADAR_EXPERTS = {
  G0: { id: "G0_GREY_DOT@1", lane: "g0", firing: true, grain: "confirmed-daily", refresh: "nightly" },
  C1: { id: "C1_1D_LIVE_WASHOUT@1", lane: "c1", firing: true, grain: "1D-LIVE", refresh: "5m" },
  C2: { id: "C2_1D_TURN@1", lane: "c2", firing: true, grain: "1D-LIVE", refresh: "5m",
        variants: ["c2a_kd_cross","c2b_k_slope","c2c_higher_k_low","c2d_hist_trough","c2e_hist_curvature","c2f_rebound_atr"] },
  C3: { id: "C3_1D_4H_RECOVERY@1", lane: "c3", firing: true, grain: "confirmed-4H", refresh: "session" },
  C4: { id: "C4_MTF_TURN@1", lane: null, firing: false, role: "stratification_only" },
  C5: { id: "C5_BOTTOM_WATCH@1", lane: "c5", firing: true, grain: "event-bound", refresh: "event" },
};

window.RADAR_C2_VARIANT_LABEL = {
  c2a_kd_cross:      { en: "K crossed above D", zh: "K上穿D" },
  c2b_k_slope:       { en: "K rising", zh: "K上行" },
  c2c_higher_k_low:  { en: "Higher K pivot low", zh: "K低点抬高" },
  c2d_hist_trough:   { en: "Histogram trough", zh: "柱状图见底" },
  c2e_hist_curvature:{ en: "Histogram curvature", zh: "柱状图拐弯" },
  c2f_rebound_atr:   { en: "0.5 ATR rebound", zh: "反弹满0.5 ATR" },
};

function _ep(o) {
  return Object.assign({
    synthetic: true,
    research_priority: { state: "ACCRUING", value: null, until: "W6" },
    opportunity: { state: "NOT_YET_MEASURED", value: null, until: "W7" },
    c4: null,
    false_starts: [],
    spark: null,
    featured: false,
  }, o);
}

/* ── fixture library. state=board unions a many-candidate slice. ─────────── */
window.RADAR_FIXTURES = {

  /* G0 only — nightly confirmed grey dot, no 1D challenger */
  g0: _ep({
    id: "ep-g0-refdot",
    ticker: "REF.DOT",
    name_en: "Reference Grey Co",
    name_zh: "参考灰点公司",
    price: 41.20, change: -0.84,
    expert: "G0", expert_id: "G0_GREY_DOT@1",
    lifecycle: "candidate",
    bar_state: "confirmed",
    freshness: { kind: "nightly_confirmed", age_s: 3600 * 14, label_en: "nightly · confirmed", label_zh: "夜间 · 已确认" },
    known_at: "2026-08-14T20:10:00Z",
    asof: "2026-08-14",
    why_probe_en: "Lobe nomination from the Terminal grey-dot slice.",
    why_probe_zh: "终端灰点切片的脑叶提名。",
    why_armed_en: "Raw grey anticipation dot printed on the confirmed daily bar.",
    why_armed_zh: "已确认日线上打印了原始灰色预判点。",
    why_candidate_en: "G0 records the exact Terminal early-dot family — not a Radar score.",
    why_candidate_zh: "G0记录的是终端早期点家族本身，不是雷达分数。",
    invalidation_en: "Next confirmed daily close reclaims the prior swing high.",
    invalidation_zh: "下一根已确认日线收盘收回前高。",
    expiry_en: "Expires at the next nightly Terminal slice if the dot is gone.",
    expiry_zh: "若夜间切片不再带点，则在下次夜间切片过期。",
    cohort_en: "Confirmed-bar · nightly",
    cohort_zh: "确认K线 · 夜间",
    spark: [38, 39, 40.2, 39.1, 38.4, 37.9, 38.6, 40.1, 41.2],
  }),

  /* C1 1D LIVE provisional — first arm IS candidate */
  c1: _ep({
    id: "ep-c1-livek",
    ticker: "FIX.WASH",
    name_en: "Fixture Washout Inc",
    name_zh: "夹具洗盘公司",
    price: 18.44, change: 0.31,
    expert: "C1", expert_id: "C1_1D_LIVE_WASHOUT@1",
    lifecycle: "candidate",
    bar_state: "provisional_1d_live",
    freshness: { kind: "live", age_s: 180, label_en: "5m ago · 1D LIVE · provisional", label_zh: "5分钟前 · 1D LIVE · 临时" },
    known_at: "2026-08-15T13:52:00Z",
    asof: "2026-08-15T13:50:00Z",
    why_probe_en: "Hot-universe member; 1D StochRSI path entered the Probe Set at the open.",
    why_probe_zh: "热门宇宙成员；开盘时1D随机RSI路径进入探针集。",
    why_armed_en: "Provisional K printed below 20 on the 5-minute sample.",
    why_armed_zh: "5分钟采样上临时K跌破20。",
    why_candidate_en: "Washout just printed on the live 1D path. Not a confirmed daily close.",
    why_candidate_zh: "实时1D路径刚打印洗盘。不是已确认日线收盘。",
    invalidation_en: "Confirmed K holds above 20 for the rearm sessions, or max-session expiry.",
    invalidation_zh: "已确认K连续高于20达到再武装会话数，或达到最长会话过期。",
    expiry_en: "Rearm law: confirmed K above floor, or max sessions, whichever first.",
    expiry_zh: "再武装法：已确认K高于下限，或达到最长会话，先到为准。",
    cohort_en: "1D LIVE · provisional",
    cohort_zh: "1D LIVE · 临时",
    spark: [22.1, 21.4, 20.0, 19.2, 18.1, 17.6, 17.9, 18.2, 18.44],
    c4: { role: "context", state: "quiet", note_en: "C4 MTF turn is context only — not a fire.", note_zh: "C4多周期拐点仅为分层语境，不是开火。" },
  }),

  /* C2 candidate with inspectable variant */
  c2: _ep({
    id: "ep-c2-kdx",
    ticker: "FIX.TURN",
    name_en: "Fixture Turn Labs",
    name_zh: "夹具拐点实验室",
    price: 63.10, change: 1.12,
    expert: "C2", expert_id: "C2_1D_TURN@1",
    c2_variant: "c2a_kd_cross",
    lifecycle: "candidate",
    bar_state: "provisional_1d_live",
    freshness: { kind: "live", age_s: 240, label_en: "4m ago · 1D LIVE · provisional", label_zh: "4分钟前 · 1D LIVE · 临时" },
    known_at: "2026-08-15T13:51:00Z",
    asof: "2026-08-15T13:50:00Z",
    why_probe_en: "Already inside an open C1 washout episode — C2 is a strict subset.",
    why_probe_zh: "已在未结束的C1洗盘情节内——C2是其严格子集。",
    why_armed_en: "Underlying C1 armed first; no C2 fire is legal before that arm.",
    why_armed_zh: "底层C1先武装；在该武装之前C2不得开火。",
    why_candidate_en: "K just crossed above D on the live 1D path.",
    why_candidate_zh: "实时1D路径上K刚上穿D。",
    invalidation_en: "Parent C1 episode ends, or this variant's own inputs become unavailable.",
    invalidation_zh: "父C1情节结束，或该变体自身输入变为不可用。",
    expiry_en: "Tied to the parent C1 episode window.",
    expiry_zh: "绑定父C1情节窗口。",
    cohort_en: "1D turn · six variants, not a blend",
    cohort_zh: "1D拐点 · 六个变体，不混合",
    spark: [58, 56.4, 55.1, 54.8, 55.6, 57.2, 59.0, 61.4, 63.1],
    c4: { role: "context", state: "aligning", note_en: "Weekly turn context aligning — stratification only.", note_zh: "周线拐点语境对齐——仅分层。" },
  }),

  /* C3 confirmed 4H */
  c3: _ep({
    id: "ep-c3-4h",
    ticker: "FIX.FOUR",
    name_en: "Fixture Four-Hour Co",
    name_zh: "夹具四小时公司",
    price: 112.05, change: 0.40,
    expert: "C3", expert_id: "C3_1D_4H_RECOVERY@1",
    lifecycle: "candidate",
    bar_state: "confirmed_4h",
    freshness: { kind: "confirmed", age_s: 1800, label_en: "30m ago · confirmed 4H", label_zh: "30分钟前 · 已确认4小时" },
    known_at: "2026-08-15T13:30:00Z",
    asof: "2026-08-15T13:30:00Z",
    why_probe_en: "Confirmed-daily arm plus a completed session-open-anchored 4H bar.",
    why_probe_zh: "已确认日线武装，加上一根完成的以开盘锚定的4小时K。",
    why_armed_en: "Confirmed daily washout arm printed on the prior session.",
    why_armed_zh: "上一交易日打印了已确认日线洗盘武装。",
    why_candidate_en: "Completed 4H histogram trough on the RTH grid — not a 1D LIVE print.",
    why_candidate_zh: "RTH网格上完成的4小时柱状图见底——不是1D LIVE打印。",
    invalidation_en: "15-session arm expiry, or the confirmed 4H recovery fails.",
    invalidation_zh: "15个会话武装过期，或已确认4小时修复失败。",
    expiry_en: "§10 15-session arm expiry.",
    expiry_zh: "§10 的15个会话武装过期。",
    cohort_en: "Confirmed 4H · not provisional",
    cohort_zh: "已确认4小时 · 非临时",
    spark: [108, 106, 104.5, 103.8, 105.2, 107.4, 109.8, 111.2, 112.05],
  }),

  /* C5 watch / event-bound */
  c5: _ep({
    id: "ep-c5-watch",
    ticker: "FIX.WAIT",
    name_en: "Fixture Watch Event",
    name_zh: "夹具观察事件",
    price: 9.18, change: -0.06,
    expert: "C5", expert_id: "C5_BOTTOM_WATCH@1",
    lifecycle: "pre_candidate",
    bar_state: "event_bound",
    freshness: { kind: "event", age_s: 5400, label_en: "event-bound · known 1h 30m ago", label_zh: "事件绑定 · 1小时30分钟前已知" },
    known_at: "2026-08-15T12:25:00Z",
    asof: "2026-08-15T12:25:00Z",
    event_id: "evt-fix-wait-001",
    why_probe_en: "Bound to a preserved W2 bottom-watch event by event_id.",
    why_probe_zh: "通过event_id绑定一条已保存的W2底部观察事件。",
    why_armed_en: "Watch event is live; C5 does not invent a second fire.",
    why_armed_zh: "观察事件仍有效；C5不另造第二次开火。",
    why_candidate_en: "Not a candidate yet — event-bound watch, waiting on the bound event.",
    why_candidate_zh: "尚未成为候选——事件绑定观察，等待被绑定事件。",
    invalidation_en: "Bound event invalidates or expires; C5 cannot outlive it.",
    invalidation_zh: "被绑定事件失效或过期；C5不能比它活得更久。",
    expiry_en: "Expires with the bound event's own clock.",
    expiry_zh: "随被绑定事件自身时钟过期。",
    cohort_en: "Watch / event-bound",
    cohort_zh: "观察 / 事件绑定",
    spark: [10.4, 10.1, 9.7, 9.4, 9.22, 9.15, 9.20, 9.16, 9.18],
  }),

  /* Same ticker, multiple expert lanes — three sibling episodes, never flattened */
  multi_g0: _ep({
    id: "ep-multi-g0",
    ticker: "FIX.MANY",
    name_en: "Fixture Multi-Lane",
    name_zh: "夹具多车道",
    price: 27.55, change: 0.22,
    expert: "G0", expert_id: "G0_GREY_DOT@1",
    lifecycle: "candidate",
    bar_state: "confirmed",
    freshness: { kind: "nightly_confirmed", age_s: 3600 * 12, label_en: "nightly · confirmed", label_zh: "夜间 · 已确认" },
    known_at: "2026-08-14T20:10:00Z", asof: "2026-08-14",
    siblings: ["ep-multi-c1", "ep-multi-c2"],
    why_probe_en: "Same ticker occupies G0 + C1 + C2 at once.",
    why_probe_zh: "同一代码同时占据G0、C1与C2。",
    why_armed_en: "Nightly grey-dot family on the confirmed bar.",
    why_armed_zh: "已确认K线上的夜间灰点家族。",
    why_candidate_en: "G0 lane only. Sister lanes are separate episodes on this ticker.",
    why_candidate_zh: "仅G0车道。同代码的姐妹车道是独立情节。",
    invalidation_en: "G0 slice drops the dot.", invalidation_zh: "G0切片不再带点。",
    expiry_en: "Next nightly slice.", expiry_zh: "下一次夜间切片。",
    cohort_en: "Multi-expert ticker · G0 lane", cohort_zh: "多专家代码 · G0车道",
    spark: [25, 25.4, 26.1, 25.8, 26.4, 26.9, 27.1, 27.4, 27.55],
  }),
  multi_c1: _ep({
    id: "ep-multi-c1",
    ticker: "FIX.MANY",
    name_en: "Fixture Multi-Lane",
    name_zh: "夹具多车道",
    price: 27.55, change: 0.22,
    expert: "C1", expert_id: "C1_1D_LIVE_WASHOUT@1",
    lifecycle: "candidate",
    bar_state: "provisional_1d_live",
    freshness: { kind: "live", age_s: 300, label_en: "5m ago · 1D LIVE · provisional", label_zh: "5分钟前 · 1D LIVE · 临时" },
    known_at: "2026-08-15T13:50:00Z", asof: "2026-08-15T13:50:00Z",
    siblings: ["ep-multi-g0", "ep-multi-c2"],
    why_probe_en: "Same ticker, C1 lane — not merged into the G0 card.",
    why_probe_zh: "同一代码的C1车道——不并入G0卡片。",
    why_armed_en: "Provisional K < 20.", why_armed_zh: "临时K低于20。",
    why_candidate_en: "Washout just printed on this ticker's live 1D path — a separate episode from Grey Dot and the turn lane.",
    why_candidate_zh: "此代码实时1D路径刚打印洗盘——与灰点和拐点车道是独立情节。",
    invalidation_en: "C1 rearm law.", invalidation_zh: "C1再武装法。",
    expiry_en: "C1 max sessions.", expiry_zh: "C1最长会话。",
    cohort_en: "Multi-expert ticker · C1 lane", cohort_zh: "多专家代码 · C1车道",
    spark: [25, 25.4, 26.1, 25.8, 26.4, 26.9, 27.1, 27.4, 27.55],
  }),
  multi_c2: _ep({
    id: "ep-multi-c2",
    ticker: "FIX.MANY",
    name_en: "Fixture Multi-Lane",
    name_zh: "夹具多车道",
    price: 27.55, change: 0.22,
    expert: "C2", expert_id: "C2_1D_TURN@1",
    c2_variant: "c2d_hist_trough",
    lifecycle: "pre_candidate",
    bar_state: "provisional_1d_live",
    freshness: { kind: "live", age_s: 300, label_en: "5m ago · 1D LIVE · provisional", label_zh: "5分钟前 · 1D LIVE · 临时" },
    known_at: "2026-08-15T13:50:00Z", asof: "2026-08-15T13:50:00Z",
    siblings: ["ep-multi-g0", "ep-multi-c1"],
    why_probe_en: "C2 variant c2d_hist_trough is pre-candidate on the same ticker.",
    why_probe_zh: "同一代码上C2变体c2d_hist_trough仍为预候选。",
    why_armed_en: "Parent C1 is open; this variant has not crossed its own fire yet.",
    why_armed_zh: "父C1仍开；该变体尚未越过自身开火条件。",
    why_candidate_en: "Not fired. Histogram trough is approaching, not printed.",
    why_candidate_zh: "未开火。柱状图见底在接近，尚未打印。",
    invalidation_en: "Parent C1 ends.", invalidation_zh: "父C1结束。",
    expiry_en: "Parent C1 window.", expiry_zh: "父C1窗口。",
    cohort_en: "Multi-expert ticker · C2 lane", cohort_zh: "多专家代码 · C2车道",
    spark: [25, 25.4, 26.1, 25.8, 26.4, 26.9, 27.1, 27.4, 27.55],
  }),

  expired: _ep({
    id: "ep-exp-old",
    ticker: "FIX.GONE",
    name_en: "Fixture Expired Episode",
    name_zh: "夹具过期情节",
    price: 44.02, change: 0.08,
    expert: "C1", expert_id: "C1_1D_LIVE_WASHOUT@1",
    lifecycle: "expired",
    bar_state: "confirmed",
    freshness: { kind: "expired", age_s: 3600 * 40, label_en: "expired · last usable 2 sessions ago", label_zh: "已过期 · 上次可用为2个会话前" },
    known_at: "2026-08-13T14:10:00Z", asof: "2026-08-13",
    why_probe_en: "Was in the Probe Set on the arm session.",
    why_probe_zh: "武装当日曾在探针集中。",
    why_armed_en: "C1 armed two sessions ago.",
    why_armed_zh: "C1于两个会话前武装。",
    why_candidate_en: "Was a candidate; the episode expired under max-session law. Still in the ledger.",
    why_candidate_zh: "曾是候选；情节按最长会话法过期。仍留在账本中。",
    invalidation_en: "Not invalidated — expired.",
    invalidation_zh: "不是失效——是过期。",
    expiry_en: "Max-session expiry fired. Ledger row retained.",
    expiry_zh: "最长会话过期已触发。账本行保留。",
    cohort_en: "Expired episode · retained",
    cohort_zh: "过期情节 · 已保留",
  }),

  invalidated: _ep({
    id: "ep-inv-fs",
    ticker: "FIX.FAKE",
    name_en: "Fixture False Start",
    name_zh: "夹具假启动",
    price: 31.70, change: -1.15,
    expert: "C2", expert_id: "C2_1D_TURN@1",
    c2_variant: "c2b_k_slope",
    lifecycle: "invalidated",
    bar_state: "confirmed",
    freshness: { kind: "invalidated", age_s: 3600 * 5, label_en: "invalidated · false start recorded", label_zh: "已失效 · 假启动已记录" },
    known_at: "2026-08-15T09:40:00Z", asof: "2026-08-15T09:40:00Z",
    why_probe_en: "Entered on a C1 arm at the open.",
    why_probe_zh: "开盘时因C1武装进入。",
    why_armed_en: "C2b K-slope printed, then the parent washout failed.",
    why_armed_zh: "C2b的K上行打印后，父洗盘失败。",
    why_candidate_en: "Fired, then invalidated. False start is kept forever — not deleted.",
    why_candidate_zh: "曾开火，随后失效。假启动永久保留——不删除。",
    invalidation_en: "Confirmed K reclaimed above the floor; structure broke the washout.",
    invalidation_zh: "已确认K收回下限之上；结构打破洗盘。",
    expiry_en: "Invalidated before expiry.",
    expiry_zh: "在过期前已失效。",
    cohort_en: "Invalidated false start",
    cohort_zh: "已失效的假启动",
    false_starts: [
      { episode_id: "ep-inv-fs", at: "2026-08-15T09:40:00Z", expert: "C2", variant: "c2b_k_slope",
        en: "This episode — K-slope fire, then washout failed.",
        zh: "本情节——K上行开火后洗盘失败。" },
    ],
  }),

  history: _ep({
    id: "ep-hist-now",
    ticker: "FIX.AGAIN",
    name_en: "Fixture Repeat Name",
    name_zh: "夹具再来一次",
    price: 14.88, change: 0.19,
    expert: "C1", expert_id: "C1_1D_LIVE_WASHOUT@1",
    lifecycle: "candidate",
    bar_state: "provisional_1d_live",
    freshness: { kind: "live", age_s: 120, label_en: "2m ago · 1D LIVE · provisional", label_zh: "2分钟前 · 1D LIVE · 临时" },
    known_at: "2026-08-15T13:53:00Z", asof: "2026-08-15T13:50:00Z",
    why_probe_en: "Re-entered the Probe Set after two recorded false starts.",
    why_probe_zh: "在两次已记录的假启动之后再次进入探针集。",
    why_armed_en: "New C1 arm on today's provisional path.",
    why_armed_zh: "今日临时路径上的新C1武装。",
    why_candidate_en: "Fresh C1 candidate. Prior false starts remain visible on the card.",
    why_candidate_zh: "新的C1候选。此前的假启动仍显示在卡片上。",
    invalidation_en: "Same C1 rearm law as any other C1 episode.",
    invalidation_zh: "与其他C1情节相同的再武装法。",
    expiry_en: "C1 max sessions.",
    expiry_zh: "C1最长会话。",
    cohort_en: "Has false-start history",
    cohort_zh: "有假启动历史",
    false_starts: [
      { episode_id: "ep-hist-fs1", at: "2026-08-08T15:10:00Z", expert: "C1",
        en: "Aug 8 — C1 armed, expired without a turn.",
        zh: "8月8日——C1武装，无拐点即过期。" },
      { episode_id: "ep-hist-fs2", at: "2026-08-12T14:05:00Z", expert: "C2", variant: "c2a_kd_cross",
        en: "Aug 12 — C2a fired, then invalidated the same session.",
        zh: "8月12日——C2a开火，同会话内失效。" },
    ],
    spark: [16.2, 15.7, 15.1, 14.6, 14.4, 14.55, 14.7, 14.8, 14.88],
  }),

  stale: _ep({
    id: "ep-stale",
    ticker: "FIX.OLD",
    name_en: "Fixture Stale Tape",
    name_zh: "夹具过期行情",
    price: 77.40, change: 0.00,
    expert: "C1", expert_id: "C1_1D_LIVE_WASHOUT@1",
    lifecycle: "candidate",
    bar_state: "stale",
    freshness: { kind: "stale", age_s: 840, label_en: "STALE · last usable reading 14m ago", label_zh: "过期 · 上次可用读数14分钟前" },
    known_at: "2026-08-15T13:41:00Z", asof: "2026-08-15T13:41:00Z",
    why_probe_en: "Was a live C1 candidate until the tape stopped advancing.",
    why_probe_zh: "在行情停止推进前曾是实时C1候选。",
    why_armed_en: "Last usable arm is 14 minutes old.",
    why_armed_zh: "上次可用武装已过14分钟。",
    why_candidate_en: "Still a ledger candidate, but the card is demoted. Not a live fire.",
    why_candidate_zh: "仍是账本候选，但卡片已降级。不是实时开火。",
    invalidation_en: "Stale is not invalidation — it is a freshness fact.",
    invalidation_zh: "过期不是失效——它是新鲜度事实。",
    expiry_en: "Unchanged. Stale demotion is independent of expiry.",
    expiry_zh: "不变。过期降级与过期时钟独立。",
    cohort_en: "Stale source · demoted",
    cohort_zh: "过期源 · 已降级",
    stale: true,
    spark: [74.2, 75.1, 76.0, 76.8, 77.1, 76.9, 77.2, 77.4, 77.40],
  }),

  unavailable: _ep({
    id: "ep-unav",
    ticker: "FIX.VOID",
    name_en: "Fixture Unavailable",
    name_zh: "夹具不可用",
    price: null, change: null,
    expert: "C2", expert_id: "C2_1D_TURN@1",
    c2_variant: "c2f_rebound_atr",
    lifecycle: "probing",
    bar_state: "unavailable",
    freshness: { kind: "unavailable", age_s: null, label_en: "UNAVAILABLE · condition is null, not a non-fire", label_zh: "不可用 · 条件为空，不是未开火" },
    known_at: null, asof: null,
    why_probe_en: "Ticker is in the Probe Set; the C2f reading cannot be formed.",
    why_probe_zh: "代码在探针集中；C2f读数无法形成。",
    why_armed_en: "Not armed. Unavailable is not False.",
    why_armed_zh: "未武装。不可用不是False。",
    why_candidate_en: "No candidate. A missing ATR makes c2f_rebound_atr unavailable, never a trivial pass.",
    why_candidate_zh: "无候选。缺失的ATR使c2f_rebound_atr不可用，绝不是平凡通过。",
    invalidation_en: "None — there was no fire to invalidate.",
    invalidation_zh: "无——没有可失效的开火。",
    expiry_en: "None.",
    expiry_zh: "无。",
    cohort_en: "Unavailable source",
    cohort_zh: "不可用源",
    unavailable: true,
  }),

  raw: _ep({
    id: "ep-raw",
    ticker: "FIX.RAW",
    name_en: "Fixture Raw-Basis Refusal",
    name_zh: "夹具原始基拒绝",
    price: null, change: null,
    expert: "C1", expert_id: "C1_1D_LIVE_WASHOUT@1",
    lifecycle: "probing",
    bar_state: "unavailable",
    freshness: { kind: "raw_basis", age_s: null, label_en: "UNAVAILABLE · raw/adjusted basis mismatch", label_zh: "不可用 · 原始/复权基不一致" },
    known_at: "2026-08-15T13:50:00Z", asof: "2026-08-15T13:50:00Z",
    why_probe_en: "In the Probe Set from the hot universe.",
    why_probe_zh: "因热门宇宙进入探针集。",
    why_armed_en: "Whole observation refused. Basis mismatch is an availability fact.",
    why_armed_zh: "整次观察被拒绝。基不一致是可用性事实。",
    why_candidate_en: "Not a non-fire. Concatenating raw tape onto adjusted daily would fabricate a cross.",
    why_candidate_zh: "不是未开火。把原始分时接到复权日线上会伪造穿越。",
    invalidation_en: "None.",
    invalidation_zh: "无。",
    expiry_en: "None.",
    expiry_zh: "无。",
    cohort_en: "Raw-basis refusal",
    cohort_zh: "原始基拒绝",
    unavailable: true,
    raw_basis: true,
  }),

  degraded: _ep({
    id: "ep-degr",
    ticker: "FIX.DIM",
    name_en: "Fixture Degraded Eval",
    name_zh: "夹具降级评估",
    price: 8.02, change: 0.04,
    expert: "C3", expert_id: "C3_1D_4H_RECOVERY@1",
    lifecycle: "pre_candidate",
    bar_state: "degraded",
    freshness: { kind: "degraded", age_s: 1200, label_en: "DEGRADED evaluator · do not treat as live", label_zh: "评估器降级 · 不得当作实时" },
    known_at: "2026-08-15T13:35:00Z", asof: "2026-08-15T13:35:00Z",
    why_probe_en: "Evaluator is degraded; this row is shown so the operator can see the last usable state.",
    why_probe_zh: "评估器已降级；展示此行是为了让操作者看到上次可用状态。",
    why_armed_en: "Last armed state is retained, visually demoted.",
    why_armed_zh: "上次武装状态保留，视觉降级。",
    why_candidate_en: "Not promoted while the evaluator is degraded.",
    why_candidate_zh: "评估器降级期间不晋级。",
    invalidation_en: "Degraded ≠ invalidated.",
    invalidation_zh: "降级不等于失效。",
    expiry_en: "Clock paused for display; engine law is W4.",
    expiry_zh: "展示时钟暂停；引擎法属于W4。",
    cohort_en: "Degraded evaluator",
    cohort_zh: "降级评估器",
    degraded: true,
  }),

  partial: _ep({
    id: "ep-part",
    ticker: "FIX.HALF",
    name_en: "Fixture Partial Data",
    name_zh: "夹具部分数据",
    price: 21.00, change: null,
    expert: "C5", expert_id: "C5_BOTTOM_WATCH@1",
    lifecycle: "probing",
    bar_state: "partial",
    freshness: { kind: "partial", age_s: 600, label_en: "partial · quote change unavailable", label_zh: "部分 · 涨跌不可用" },
    known_at: "2026-08-15T13:45:00Z", asof: "2026-08-15T13:45:00Z",
    event_id: "evt-fix-half-009",
    why_probe_en: "Lobe nomination present; live change and risk geometry are missing.",
    why_probe_zh: "脑叶提名在；实时涨跌与风险几何缺失。",
    why_armed_en: "Not armed — missing fields are printed as unavailable, not guessed.",
    why_armed_zh: "未武装——缺失字段打印为不可用，不猜测。",
    why_candidate_en: "No candidate. Partial data is not filled with a placeholder number.",
    why_candidate_zh: "无候选。部分数据不会用占位数字填满。",
    invalidation_en: "Unknown until the missing fields arrive.",
    invalidation_zh: "缺失字段到达前未知。",
    expiry_en: "Unknown.",
    expiry_zh: "未知。",
    cohort_en: "Partial data",
    cohort_zh: "部分数据",
    partial: true,
    spark: null,
  }),

  /* extra many-candidate rows so the default board is dense */
  extra_a: _ep({
    id: "ep-x-a", ticker: "REF.ALFA", name_en: "Reference Alfa", name_zh: "参考阿尔法",
    price: 5.44, change: 0.11, expert: "C1", expert_id: "C1_1D_LIVE_WASHOUT@1",
    lifecycle: "candidate", bar_state: "provisional_1d_live",
    freshness: { kind: "live", age_s: 200, label_en: "3m ago · 1D LIVE · provisional", label_zh: "3分钟前 · 1D LIVE · 临时" },
    known_at: "2026-08-15T13:52:00Z", asof: "2026-08-15T13:50:00Z",
    why_probe_en: "IPO-cohort fixture inside the Probe Set — not rejected for index non-membership.",
    why_probe_zh: "探针集内的IPO队列夹具——不因非指数成分被拒绝。",
    why_armed_en: "Provisional K < 20.", why_armed_zh: "临时K低于20。",
    why_candidate_en: "Washout just printed on the live 1D path.", why_candidate_zh: "实时1D路径刚打印洗盘。",
    invalidation_en: "C1 rearm.", invalidation_zh: "C1再武装。",
    expiry_en: "C1 max sessions.", expiry_zh: "C1最长会话。",
    cohort_en: "IPO cohort · fixture", cohort_zh: "IPO队列 · 夹具",
    spark: [6.1, 5.9, 5.6, 5.4, 5.22, 5.18, 5.30, 5.38, 5.44],
  }),
  extra_b: _ep({
    id: "ep-x-b", ticker: "REF.BRAVO", name_en: "Reference Bravo", name_zh: "参考布拉沃",
    price: 88.20, change: -0.55, expert: "C2", expert_id: "C2_1D_TURN@1",
    c2_variant: "c2e_hist_curvature",
    lifecycle: "candidate", bar_state: "provisional_1d_live",
    freshness: { kind: "live", age_s: 260, label_en: "4m ago · 1D LIVE · provisional", label_zh: "4分钟前 · 1D LIVE · 临时" },
    known_at: "2026-08-15T13:51:00Z", asof: "2026-08-15T13:50:00Z",
    why_probe_en: "Inside an open C1 episode.", why_probe_zh: "在未结束的C1情节内。",
    why_armed_en: "Parent C1 armed.", why_armed_zh: "父C1已武装。",
    why_candidate_en: "Histogram is bending up on the live 1D path — before a trough print.",
    why_candidate_zh: "实时1D路径上柱状图正在拐弯——见底打印之前。",
    invalidation_en: "Parent C1 ends.", invalidation_zh: "父C1结束。",
    expiry_en: "Parent window.", expiry_zh: "父窗口。",
    cohort_en: "C2e curvature", cohort_zh: "C2e拐弯",
    spark: [90, 89.2, 87.8, 86.9, 87.1, 87.6, 88.0, 88.4, 88.2],
  }),
  extra_c: _ep({
    id: "ep-x-c", ticker: "REF.COVE", name_en: "Reference Cove", name_zh: "参考湾",
    price: 33.01, change: 0.02, expert: "G0", expert_id: "G0_GREY_DOT@1",
    lifecycle: "pre_candidate", bar_state: "confirmed",
    freshness: { kind: "nightly_confirmed", age_s: 3600 * 16, label_en: "nightly · confirmed", label_zh: "夜间 · 已确认" },
    known_at: "2026-08-14T20:10:00Z", asof: "2026-08-14",
    why_probe_en: "Grey-dot slice, not yet a recorded candidate this cycle.",
    why_probe_zh: "灰点切片，本周期尚未记为候选。",
    why_armed_en: "Dot present, promotion pending the slice rule.",
    why_armed_zh: "点在，晋级仍待切片规则。",
    why_candidate_en: "Pre-candidate G0 — not blended into a generic entry signal.",
    why_candidate_zh: "G0预候选——不混成泛化入场信号。",
    invalidation_en: "Slice drops the dot.", invalidation_zh: "切片不再带点。",
    expiry_en: "Next nightly slice.", expiry_zh: "下一次夜间切片。",
    cohort_en: "Grey Dot · pre-candidate", cohort_zh: "灰点 · 预候选",
    spark: [32.2, 32.4, 32.6, 32.5, 32.7, 32.8, 32.9, 33.0, 33.01],
  }),
  extra_d: _ep({
    id: "ep-x-d", ticker: "REF.DELTA", name_en: "Reference Delta", name_zh: "参考德尔塔",
    price: 19.75, change: 0.48, expert: "C3", expert_id: "C3_1D_4H_RECOVERY@1",
    lifecycle: "candidate", bar_state: "confirmed_4h",
    freshness: { kind: "confirmed", age_s: 2400, label_en: "40m ago · confirmed 4H", label_zh: "40分钟前 · 已确认4小时" },
    known_at: "2026-08-15T13:20:00Z", asof: "2026-08-15T13:20:00Z",
    why_probe_en: "Confirmed 4H grid member.", why_probe_zh: "已确认4小时网格成员。",
    why_armed_en: "Confirmed daily arm.", why_armed_zh: "已确认日线武装。",
    why_candidate_en: "Completed 4H recovery bar.", why_candidate_zh: "完成的4小时修复K。",
    invalidation_en: "15-session expiry.", invalidation_zh: "15个会话过期。",
    expiry_en: "§10 15-session.", expiry_zh: "§10 的15个会话。",
    cohort_en: "Confirmed 4H", cohort_zh: "已确认4小时",
    spark: [18.2, 18.0, 17.7, 17.9, 18.4, 18.9, 19.2, 19.5, 19.75],
  }),
  extra_e: _ep({
    id: "ep-x-e", ticker: "REF.ECHO", name_en: "Reference Echo", name_zh: "参考回声",
    price: 4.10, change: -0.02, expert: "C5", expert_id: "C5_BOTTOM_WATCH@1",
    lifecycle: "probing", bar_state: "event_bound",
    freshness: { kind: "event", age_s: 7200, label_en: "event-bound · known 2h ago", label_zh: "事件绑定 · 2小时前已知" },
    known_at: "2026-08-15T11:55:00Z", asof: "2026-08-15T11:55:00Z",
    event_id: "evt-echo-2",
    why_probe_en: "Lobe-only probe — not yet armed.", why_probe_zh: "仅脑叶探针——尚未武装。",
    why_armed_en: "Watch event recorded, no arm.", why_armed_zh: "观察事件已记录，无武装。",
    why_candidate_en: "Probing only.", why_candidate_zh: "仅探测。",
    invalidation_en: "Bound event ends.", invalidation_zh: "被绑定事件结束。",
    expiry_en: "Event clock.", expiry_zh: "事件时钟。",
    cohort_en: "Lobe-only probe", cohort_zh: "仅脑叶探针",
  }),
};

/* Board compositions. quiet = empty. board = many. others = focused. */
window.RADAR_STATES = {
  board:        ["c1","c2","c3","g0","c5","multi_g0","multi_c1","multi_c2","history","extra_a","extra_b","extra_c","extra_d","extra_e","stale","partial"],
  quiet:        [],
  g0:           ["g0"],
  c1:           ["c1"],
  c2:           ["c2"],
  c3:           ["c3"],
  c5:           ["c5"],
  multi:        ["multi_g0","multi_c1","multi_c2"],
  expired:      ["expired"],
  invalidated:  ["invalidated"],
  history:      ["history"],
  stale:        ["stale"],
  unavailable:  ["unavailable"],
  raw:          ["raw"],
  degraded:     ["degraded"],
  partial:      ["partial"],
  anon:         ["c1","c2","c3"],
  ipo:          ["extra_a"],
  lobe:         ["extra_e"],
};

window.RADAR_COPY = {
  title: { en: "Live Entry Radar", zh: "实时入场雷达" },
  purpose: {
    en: "Where an observable entry is developing right now — through which expert, why, and how fresh.",
    zh: "此刻哪里正在形成可观察的入场——经由哪位专家、为什么、证据有多新。",
  },
  not_prophet: {
    en: "Prophet asks what we want to own. Radar asks where an entry is forming. Sister look, different job.",
    zh: "先知问我们想拥有什么。雷达问入场正在哪里形成。同一家族，不同工作。",
  },
  ref_banner: {
    en: "REFERENCE · SYNTHETIC FIXTURES · NOT PRODUCTION · NOT A LIVE TAPE",
    zh: "参考稿 · 合成夹具 · 非生产 · 非实时行情",
  },
  lanes: {
    all:  { en: "All", zh: "全部" },
    best: { en: "Best · unranked", zh: "首选 · 未排名" },
    g0:   { en: "Grey Dot", zh: "灰点" },
    c1:   { en: "1D Washout", zh: "1D洗盘" },
    c2:   { en: "1D Turn", zh: "1D拐点" },
    c3:   { en: "Deep Washout", zh: "深处洗盘" },
    c5:   { en: "Intelligence", zh: "情报" },
  },
  life: {
    probing:       { en: "Probing", zh: "探测中" },
    pre_candidate: { en: "Pre-candidate", zh: "预候选" },
    candidate:     { en: "Candidate", zh: "候选" },
    invalidated:   { en: "Invalidated", zh: "已失效" },
    expired:       { en: "Expired", zh: "已过期" },
  },
  life_axis: { en: "Lifecycle", zh: "生命周期" },
  expert_axis: { en: "Expert", zh: "专家" },
  pri_label: { en: "Priority", zh: "优先级" },
  pri_accruing: { en: "ACCRUING", zh: "累计中" },
  pri_tip: {
    en: "Research Priority is a future W6 object. No number is printed because none has been measured.",
    zh: "研究优先级是未来W6的对象。没有打印数字，因为尚未被测量。",
  },
  opp_label: { en: "Opportunity", zh: "机会" },
  opp_none: { en: "NOT YET MEASURED — future W7", zh: "尚未测量 — 未来W7" },
  c4_chip: { en: "C4 · context only", zh: "C4 · 仅语境" },
  empty: {
    en: "No candidates in this view. Quiet is a state, not a broken page. The Probe Set count above is the live probe universe — it is not required to be zero.",
    zh: "此视图没有候选。安静是一种状态，不是坏页。上方探针集计数是活的探针宇宙——不必为零。",
  },
  stale_banner: {
    en: "Stale or degraded readings are demoted. They never keep a live-candidate look.",
    zh: "过期或降级读数已被降级。它们绝不保留实时候选的外观。",
  },
  degraded_banner: {
    en: "Evaluator degraded — last usable state only. Do not treat these rows as live fires.",
    zh: "评估器已降级——仅为上次可用状态。不要把这些行当作实时开火。",
  },
  anon_title: { en: "Live Entry Radar is a research board", zh: "实时入场雷达是研究看板" },
  anon_body: {
    en: "The paid board shows expert identity, lifecycle, freshness, and why a name is here. It does not print entry, target, or void levels, and it does not print a win probability.",
    zh: "付费看板显示专家身份、生命周期、新鲜度，以及一只名字为何在此。它不打印入场、目标或失效价，也不打印获胜概率。",
  },
  drawer: {
    why_here: { en: "Why is it here", zh: "为何在此" },
    why_now: { en: "Why now", zh: "为何是现在" },
    why_armed: { en: "Why it armed", zh: "为何武装" },
    why_cand: { en: "Why candidate / fired", zh: "为何成为候选 / 开火" },
    variant: { en: "C2 variant", zh: "C2变体" },
    c4: { en: "C4 context (not a fire)", zh: "C4语境（不是开火）" },
    invalidation: { en: "Invalidation", zh: "失效条件" },
    expiry: { en: "Expiry", zh: "过期" },
    history: { en: "False-start history", zh: "假启动历史" },
    clocks: { en: "Clocks", zh: "时钟" },
    siblings: { en: "Other expert lanes on this ticker", zh: "此代码上的其他专家车道" },
  },
};
