#!/usr/bin/env python3
"""Build the R4 closure ledger MECHANICALLY from the frozen R3 review record.

The ledger is not hand-maintained prose. It is generated by joining:

  * the R3 verdict packet   (r3_source/verdict.yml)            — the binding record
  * both R3 critic receipts (r3_source/reviews/*.yml)          — every finding raised
  * the R4 disposition table (DISPOSITIONS, below)             — this cycle's answer

and it HARD-FAILS if the join is not total in both directions:

  * a finding present in the R3 record with no R4 disposition   -> exit 2
  * an R4 disposition naming a finding absent from the record   -> exit 2
  * a verdict condition whose findings are not all dispositioned-> exit 2

That is the mechanism behind the handoff's "no finding may disappear merely
because it is awkward or not mentioned below". A finding cannot be dropped by
forgetting it — dropping it breaks the build. To retire one you must write an
explicit disposition saying so, on the record, with a reason.

Usage:
  python3 tools/build_ledger.py            # write R4_CLOSURE_LEDGER.md
  python3 tools/build_ledger.py --check    # verify coverage + freshness, write nothing
"""
import hashlib
import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
SRC = ROOT / "r3_source"
OUT = ROOT / "R4_CLOSURE_LEDGER.md"

# sha256 of the vendored R3 record as committed. The ledger is an answer to a
# SPECIFIC frozen record; if the source moves, the ledger is stale by definition
# (RIG §3 — receipts go stale the moment the frozen sha moves).
R3_SOURCE_SHA256 = {
    "verdict.yml": "af6953df241c9df881aa5877f5f68280b565fa4aca21a17c3501172cf9b27b60",
    "reviews/product_regression.yml": "eb580945883ad943ef1c91c242f6130497e71a016febf0a4f1edb662ee611f6a",
    "reviews/visual_taste.yml": "47eb4fee34c6d3de8a14b2ebdab4c2648f6c71f2debdadb959b6606921d92f27",
}

R3_ARTIFACT_SHA = "6ad6b51bc351bb7e32a77960abe11f6ddb63475c"

# Ids the R3 conditions cite as HISTORY from an earlier cycle, not as open work.
# PRC-203 is the r2 one-universe count law that DA-001 says superseded the stale
# state=paid exemption; it was closed in R3 and verified closed by both critics.
# Listed explicitly so an unrecognised id in a condition still fails the build.
PRIOR_CYCLE_REFS = {"PRC-203"}

# ── The R4 disposition table — this cycle's adjudication ─────────────────────
# tier:    blocking | authority | carried_major | carried_minor | withdrawn
# action:  implement | amend_doc | disclose | accept_blocked_data | no_action
# proof:   verify.py check ids and/or crop names that FAIL if the work is undone.
#          A disposition with an empty proof list is allowed only for `withdrawn`
#          and `no_action` — enforced below.
DISPOSITIONS = [
    # ── blocking (verdict.blocking_findings) ────────────────────────────────
    dict(
        id="PRC-301", tier="blocking", action="implement", ws="W1",
        summary="Card routes to the name's detail surface. The whole card is a real link to "
                "stock.html#TICKER; the internal caution/episode/tip controls stay reachable "
                "and are not nested inside the anchor.",
        proof=["R1 card-link", "R1b card-link-a11y", "R1c card-link-no-nesting"],
    ),
    dict(
        id="PRC-302", tier="blocking", action="implement", ws="W1",
        summary="Anonymous gate copy states what the paid Board actually provides — full setups, "
                "stance, live quote/change, Priority, lifecycle, zone and cautions — and no longer "
                "promises entry/target/void levels the card tier bans.",
        proof=["R2 anon-gate-truth", "40-anon-locked-dark-en", "41-anon-locked-light-zh"],
    ),
    dict(
        id="PRC-305", tier="blocking", action="implement", ws="W1",
        summary="Behind-the-tape state restored with a capability id, reusing production's freshness "
                "producer. Fresh renders 'Settled close'; behind renders the ranking vintage, the "
                "sessions-behind count and a verify-live-price instruction, EN + ZH.",
        proof=["R3 freshness-fresh", "R3b freshness-behind", "R3c freshness-bilingual",
               "80-stale-dark-en", "81-stale-light-zh"],
    ),
    dict(
        id="PRC-306", tier="blocking", action="implement", ws="W1",
        summary="Full-book reachability restored. The 40-card viewport stays as the initial density "
                "budget but is no longer a ceiling: in-place 'Show more / Show all' expands the grid "
                "to every row of the active partition. Table is an alternate representation, not the "
                "only route to the tail.",
        proof=["R4 expand-more", "R4b expand-all", "R4c full-book-card-reachable",
               "90-expanded-dark-en"],
    ),
    dict(
        id="VTC-301", tier="blocking", action="implement", ws="W2",
        summary="Mixed-grid degradation fixed at desktop. The chartless placeholder is equalised to "
                "the 74px chart height (the pattern board.css already uses at 720px) and renders as "
                "an intentional, visibly null hero — not a stretched void.",
        proof=["R5 nochart-geometry", "R5b nochart-intentional-null", "01-desktop-dark-en"],
    ),
    dict(
        id="PRC-303", tier="blocking", action="implement", ws="W1",
        summary="No-read / zone / caution incoherence resolved. A no-read card keeps its independently "
                "sourced trigger event, but caution text that references a buy zone is suppressed or "
                "rewritten when the card carries no zone. No zone is fabricated.",
        proof=["R6 noread-caution-coherence", "R6b noread-keeps-trigger"],
    ),
    dict(
        id="VTC-302", tier="blocking", action="implement", ws="W2",
        summary="Stance salience inversion cured by adopting the critic's luminance-ordered ramp. "
                "BUY > WAIT > NO-READ in all four theme x language quadrants, with --pv-buy still "
                "derived from --up so the zh flip stays structural.",
        proof=["R7 stance-ramp-order", "R7b stance-ramp-quadrants"],
    ),
    dict(
        id="DA-001", tier="blocking", action="amend_doc", ws="W3",
        summary="DESIGN_NOTES §0b.1 and §7 amended: the state=paid exemption and the '60% no-read must "
                "not become flagship' mechanism are recorded as SUPERSEDED by PRC-203's one-universe "
                "count law, with G-D named as how full fidelity catches up.",
        proof=["R8 design-notes-no-contradiction"],
    ),
    dict(
        id="DA-002", tier="blocking", action="implement", ws="W2",
        summary="The r2 non-waivable stance-distinctness condition discharged on the CHIP as well as the "
                "chart: dark --ink-mix-up moves off 100%, so the solid BUY badge is no longer "
                "byte-identical to the live positive-direction token.",
        proof=["R9 stance-chip-not-direction-ink"],
    ),
    dict(
        id="DA-003", tier="blocking", action="implement", ws="W3",
        summary="Compare page repaired as evidence: FTI renders at its true payload stance, production-only "
                "styles are scoped into .cmp-prod so production shows production semantics (including the "
                "green Triggered hue), the revised column carries an explicit costs/tradeoffs list, and a "
                "second chartless/no-read specimen is added.",
        proof=["R10 compare-true-stance", "R10b compare-scoped-prod",
               "R10c compare-revised-costs", "R10d compare-nochart-specimen"],
    ),

    # ── carried majors (verdict conditions, "carried as revision work") ─────
    dict(
        id="PRC-307", tier="carried_major", action="implement", ws="W3",
        summary="Quantitative track record restored on the page from its real producer, replacing the "
                "RELOCATE-to-four-empty-links claim. The page ends on evidence carrying numbers.",
        proof=["R11 track-record-numbers"],
    ),
    dict(
        id="PRC-309", tier="carried_major", action="implement", ws="W2",
        summary="The chart null is PRINTED rather than hidden: the equalised no-chart hero states its own "
                "absence instead of rendering a decorative empty strip.",
        proof=["R5b nochart-intentional-null"],
    ),
    dict(
        id="PRC-310", tier="carried_major", action="implement", ws="W1",
        summary="'the six cells below add up to this number' is only asserted where the six cells are "
                "actually on screen; the claim is not repeated over a surface that contradicts it.",
        proof=["R12 headline-claim-scope"],
    ),
    dict(
        id="PRC-311", tier="carried_major", action="implement", ws="W1",
        summary="'What changed today' stays a board-level fact: rendered on the unfiltered Board, hidden "
                "when a lifecycle filter is active rather than sitting a full-book number inside a "
                "filtered frame.",
        proof=["R13 chgstrip-unfiltered-only"],
    ),
    dict(
        id="PRC-312", tier="carried_major", action="implement", ws="W1",
        summary="Entry stance and lifecycle made to coexist semantically. The five sourced entry verbs are "
                "preserved (no sixth stance, no fallback to recommended_action); the axis is labelled so "
                "WAIT reads as an entry verb, not a verdict on an already-entered position. The Ready "
                "gloss is amended so it states the lifecycle fact rather than contradicting a sourced "
                "Triggered event.",
        proof=["R14 stance-axis-explicit", "R14b ready-gloss-no-trigger-contradiction"],
    ),
    dict(
        id="PRC-313", tier="carried_major", action="implement", ws="W1",
        summary="Closed by the PRC-306 table redesign: the Board table carries the decision fields "
                "(ticker, stance, lifecycle, Priority, quote/change, Zone, episode/as-of) with honest "
                "dashes, and Entry/T1/Void are removed — exact execution geometry belongs to detail.",
        proof=["R15 table-decision-fields", "R15b table-no-execution-levels", "60-table-invalidated"],
    ),
    dict(
        id="PRC-314", tier="carried_major", action="implement", ws="W1",
        summary="Resolved wins precedence: a resolved card suppresses the active zone, live change and "
                "Priority treatments that imply an open plan, and takes the closed-record treatment first.",
        proof=["R16 resolved-precedence", "27-filter-resolved"],
    ),
    dict(
        id="VTC-303", tier="carried_major", action="implement", ws="W2",
        summary="Featured pinning completed: the .pv-featured::before rail takes var(--pv-buy) like the "
                "ring, glow and lift, so no grey stance rail sits inside a green/red Featured aura.",
        proof=["R17 featured-rail-cohort"],
    ),
    dict(
        id="VTC-304", tier="carried_major", action="implement", ws="W2",
        summary="Amber stops carrying three meanings. Triggered returns to the verb/stance hue as production "
                "ships it; the caution carrier keeps amber; WAIT no longer shares one semantic ink with "
                "both Triggered and caution.",
        proof=["R18 trigger-verb-hue", "R18b wait-not-caution-ink"],
    ),
    dict(
        id="VTC-306", tier="carried_major", action="implement", ws="W1",
        summary="The anonymous shop window no longer specimens a card that says 'No read yet' / 'No zone' "
                "while the gate advertises the product; the unlocked specimen is reconciled with the gate copy.",
        proof=["R2b anon-specimen-reconciled"],
    ),
    dict(
        id="VTC-307", tier="carried_major", action="implement", ws="W3",
        summary="The page stops decaying to furniture: the empty Market Context shell is removed unless bound "
                "to real content, and Evidence carries real numbers rather than four bare links.",
        proof=["R11 track-record-numbers", "R19 no-empty-section-shell"],
    ),
    dict(
        id="VTC-308", tier="carried_major", action="implement", ws="W2",
        summary="Sparse archive rows use the right form: Resolved and severely data-sparse episode rows render "
                "in the compact form the fallback treatment already proves, not 5-across full-card husks "
                "repeating PRIORITY —.",
        proof=["R20 sparse-compact-form", "32-multi-episode-resolved"],
    ),

    # ── carried minors (upheld at minor; hygiene the handoff names) ─────────
    dict(
        id="PRC-304", tier="carried_minor", action="disclose", ws="W1",
        summary="The per-ticker demo change overlay stays the only simulated number on the page and stays "
                "marked data-mock-live, but it is disclosed on the surface rather than only in DESIGN_NOTES, "
                "so a reader of a crop cannot mistake it for a live tape.",
        proof=["R21 mock-live-disclosed"],
    ),
    dict(
        id="PRC-308", tier="carried_minor", action="accept_blocked_data", ws="W3",
        summary="Company name and sector absent on 134/179 rows is ACCEPTED as the same G-D publication gap "
                "(#5541), not cured here. Recorded with its coverage number rather than silently absorbed.",
        proof=["R22 enrichment-gap-disclosed"],
    ),
    dict(
        id="PRC-316", tier="carried_minor", action="implement", ws="W1",
        summary="Every Groups recommendation slug is mapped in both languages; no raw payload slug (e.g. "
                "'enter') can leak into user-facing copy in either language.",
        proof=["R23 groups-slug-mapped"],
    ),
    dict(
        id="PRC-317", tier="carried_minor", action="implement", ws="W1",
        summary="Groups rank is hidden unless its denominator and provenance are known; an unranked population "
                "does not print an authoritative-looking ordinal.",
        proof=["R24 groups-rank-denominator"],
    ),
    dict(
        id="PRC-318", tier="carried_minor", action="implement", ws="W1",
        summary="A zero-width zone renders as a single price, not as a range whose endpoints are equal.",
        proof=["R25 zero-width-zone"],
    ),
    dict(
        id="PRC-319", tier="carried_minor", action="disclose", ws="W3",
        summary="Lifecycle cells the real payload cannot exhibit get an honest recorded screenshot gap in "
                "DESIGN_NOTES rather than an implied-but-missing capture.",
        proof=["R26 screenshot-gaps-recorded"],
    ),
    dict(
        id="PRC-320", tier="carried_minor", action="amend_doc", ws="W3",
        summary="Every stale numeric statement in DESIGN_NOTES is refreshed after the fixture rebake, "
                "including the §5 candidate arithmetic and the §7 '.actcol idiom' claim.",
        proof=["R27 design-notes-numbers-fresh"],
    ),
    dict(
        id="PRC-321", tier="carried_minor", action="implement", ws="W2",
        summary="Resolved stays physically outside the live partition at 390px — the mobile ladder keeps the "
                "separation that carries 'Resolved sits outside the count'.",
        proof=["R28 mobile-resolved-separation", "42-anon-locked-390-dark"],
    ),
    dict(
        id="VTC-305", tier="carried_minor", action="implement", ws="W2",
        summary="The lifecycle mark is made legible at shipped size and the two marks that rendered from one "
                "rule are given distinguishable forms.",
        proof=["R29 lifecycle-mark-distinct"],
    ),
    dict(
        id="VTC-309", tier="carried_minor", action="implement", ws="W1",
        summary="The Candidates sample stops needlessly duplicating already-visible Setup names where the real "
                "pool permits a distinct sample.",
        proof=["R30 candidates-sample-distinct"],
    ),
    dict(
        id="VTC-310", tier="carried_minor", action="implement", ws="W2",
        summary="The dead .actcol / actiongrid stylesheet block is removed now that it is not normative, and "
                "the DESIGN_NOTES claim that it is the live component is corrected with it.",
        proof=["R31 no-dead-actcol-css"],
    ),
    dict(
        id="VTC-311", tier="carried_minor", action="implement", ws="W2",
        summary="The light+zh stance ramp is authored explicitly rather than emerging from cascade source "
                "order, so the quadrant is a design rather than a side effect.",
        proof=["R7b stance-ramp-quadrants", "R32 light-zh-explicit"],
    ),
    dict(
        id="VTC-312", tier="carried_minor", action="implement", ws="W1",
        summary="The headline claim no longer invites an addition that does not visibly work: the asserted "
                "arithmetic is either demonstrable on the surface that states it, or the claim is scoped.",
        proof=["R12 headline-claim-scope"],
    ),

    # ── withdrawn at the R3 second pass ────────────────────────────────────
    dict(
        id="PRC-315", tier="withdrawn", action="no_action", ws="—",
        summary="WITHDRAWN by its own critic at the R3 second pass (the Regime/Breadth/Posture removal is "
                "correctly filed). Carried here only so the ledger's coverage of the record is total; no R4 "
                "work is owed.",
        proof=[],
    ),

    # ── mechanically-flagged rows the verdict requires be adjudicated ──────
    dict(
        id="task.open_name_detail", tier="authority", action="implement", ws="W1",
        summary="Capability acquires a disposition via PRC-301: the card routes to detail. No longer WORSE "
                "with no disposition.",
        proof=["R1 card-link"],
    ),
    dict(
        id="task.staleness_awareness", tier="authority", action="implement", ws="W1",
        summary="Capability acquires a disposition via PRC-305: the behind-the-tape state gets a slot, a "
                "capability id and a producer.",
        proof=["R3b freshness-behind"],
    ),
    dict(
        id="task.momentum_context", tier="authority", action="accept_blocked_data", ws="W3",
        summary="ACCEPTED as a data dependency (G-D / #5541), exactly as the R3 verdict resolved it — with the "
                "express exception of its layout consequence, which is VTC-301 and IS cured here.",
        proof=["R5 nochart-geometry", "R22 enrichment-gap-disclosed"],
    ),
    dict(
        id="auth.anon_gate_copy", tier="authority", action="implement", ws="W1",
        summary="Resolved by PRC-302: the gate copy is brought to what a subscriber actually lands on. The "
                "card-tier execution-level ban is NOT reopened.",
        proof=["R2 anon-gate-truth"],
    ),
    dict(
        id="auth.table_levels", tier="authority", action="implement", ws="W1",
        summary="Resolved by the PRC-306/PRC-313 table redesign: the table carries stance, Priority and zone "
                "and drops the execution levels. The card-tier ban stands unamended.",
        proof=["R15 table-decision-fields", "R15b table-no-execution-levels"],
    ),
]

# Findings the R3 record raises that are NOT owed R4 work must still appear.
# Anything else missing is a build failure.
TIER_ORDER = ["blocking", "authority", "carried_major", "carried_minor", "withdrawn"]
TIER_LABEL = {
    "blocking": "BLOCKING — verdict.blocking_findings",
    "authority": "AUTHORITY — task-matrix and authority-delta rows",
    "carried_major": "CARRIED MAJOR — revision work per verdict conditions",
    "carried_minor": "CARRIED MINOR — upheld hygiene",
    "withdrawn": "WITHDRAWN at the R3 second pass",
}


def load(rel):
    p = SRC / rel
    raw = p.read_bytes()
    got = hashlib.sha256(raw).hexdigest()
    want = R3_SOURCE_SHA256[rel]
    if got != want:
        die(f"R3 source {rel} changed (sha256 {got[:16]}… != pinned {want[:16]}…). "
            "The ledger answers a FROZEN record; re-pin deliberately or restore the file.")
    return yaml.safe_load(raw)


def die(msg):
    print(f"::error title=r4-ledger::{msg}", flush=True)
    print(f"\nLEDGER BUILD FAILED: {msg}", file=sys.stderr)
    sys.exit(2)


def collect_record():
    """Every finding id the R3 record raises, with its severity trail."""
    verdict = load("verdict.yml")
    rec = {}

    for rel, who in [("reviews/product_regression.yml", "product_regression"),
                     ("reviews/visual_taste.yml", "visual_taste")]:
        d = load(rel)
        amend = {(a.get("finding") or a.get("id")): a
                 for a in (d["second_pass"].get("amendments") or [])}
        for f in d["first_pass"]["findings"]:
            fid = f["id"]
            a = amend.get(fid, {})
            rec[fid] = dict(
                source=who,
                title=" ".join(str(f.get("title", "")).split()),
                p1=f.get("severity"),
                p2_action=a.get("action"),
                p2_severity=a.get("new_severity"),
            )

    # authority-originated findings live only in the verdict packet
    for bf in verdict.get("blocking_findings") or []:
        fid = bf["finding"]
        rec.setdefault(fid, dict(source="authority (verdict)", title="",
                                 p1="blocker", p2_action=None, p2_severity=None))
        rec[fid]["verdict_resolution"] = bf.get("resolution")
        rec[fid]["verdict_note"] = " ".join(str(bf.get("note", "")).split())

    for row in verdict.get("task_matrix_adjudication") or []:
        fid = row["task"]
        rec[fid] = dict(source="verdict task_matrix", title=f"verdict_stands: {row.get('verdict_stands')}",
                        p1=None, p2_action=None, p2_severity=None,
                        verdict_resolution=row.get("resolution"),
                        verdict_note=" ".join(str(row.get("note", "")).split()))

    for row in verdict.get("authority_delta_adjudication") or []:
        fid = row["row"]
        rec[fid] = dict(source="verdict authority_delta", title="",
                        p1=None, p2_action=None, p2_severity=None,
                        verdict_resolution=row.get("resolution"),
                        verdict_note=" ".join(str(row.get("note", "")).split()))

    return verdict, rec


def main():
    check_only = "--check" in sys.argv
    verdict, rec = collect_record()

    disp = {d["id"]: d for d in DISPOSITIONS}
    if len(disp) != len(DISPOSITIONS):
        die("duplicate id in DISPOSITIONS")

    # ── the total-join guarantee, both directions ──────────────────────────
    missing = sorted(set(rec) - set(disp))
    if missing:
        die("R3 findings with NO R4 disposition (a finding may not disappear): "
            + ", ".join(missing))

    invented = sorted(set(disp) - set(rec))
    if invented:
        die("R4 dispositions naming findings absent from the R3 record: " + ", ".join(invented))

    # ── every disposition owing work must name a proof ─────────────────────
    unproven = sorted(d["id"] for d in DISPOSITIONS
                      if d["action"] not in ("no_action",) and not d["proof"])
    if unproven:
        die("dispositions owing work with no proof handle: " + ", ".join(unproven))

    # ── every verdict condition must reference dispositioned findings ──────
    # Conditions also cite PRIOR-CYCLE findings as history ("PRC-203's count law
    # superseded it"). Those are references, not open work, and are allowlisted
    # BY ID — so a genuinely new uncovered id still fails the build.
    import re as _re
    cond_ids = set()
    for c in verdict.get("conditions") or []:
        cond_ids |= set(_re.findall(r"\b(?:PRC|VTC|DA)-\d{3}\b", c))
    stray = cond_ids - set(disp) - PRIOR_CYCLE_REFS
    if stray:
        die("verdict conditions cite findings with no disposition: " + ", ".join(sorted(stray)))
    orphan_refs = sorted(PRIOR_CYCLE_REFS & set(disp))
    if orphan_refs:
        die("ids allowlisted as prior-cycle history are also dispositioned as open R4 work "
            "(pick one): " + ", ".join(orphan_refs))

    if check_only:
        print(f"r4-ledger OK — {len(rec)} R3 record rows, {len(disp)} dispositions, "
              f"{len(cond_ids)} condition-cited ids, all joined.")
        return 0

    # ── render ─────────────────────────────────────────────────────────────
    L = []
    L.append("<!-- GENERATED by tools/build_ledger.py — do not hand-edit.")
    L.append("     Source of truth: the frozen R3 review record vendored in r3_source/.")
    L.append("     Regenerate: python3 tools/build_ledger.py -->")
    L.append("")
    L.append("# Prophet Board — R4 closure ledger")
    L.append("")
    L.append(f"Answers the **R3 verdict `{verdict['verdict']}`** (PR #5552) issued over artifact "
             f"`{R3_ARTIFACT_SHA[:12]}`.")
    L.append("")
    L.append("This file is **generated**, not written. `tools/build_ledger.py` joins every finding in "
             "the frozen R3 record against this cycle's disposition table and **hard-fails** if the "
             "join is not total in both directions. A finding cannot be dropped by forgetting it; "
             "dropping it breaks the build.")
    L.append("")
    L.append("| R3 record rows | R4 dispositions | Condition-cited ids |")
    L.append("|---|---|---|")
    L.append(f"| {len(rec)} | {len(disp)} | {len(cond_ids)} |")
    L.append("")
    L.append("**This is a closure pass, not a redesign.** The successful R3 architecture is preserved: "
             "chart-first card, live quote/change slot, Priority, plan-book Setups, lifecycle ladder, "
             "one universe/count law, sourced Groups, caution carrier, stance-branched zone, light-mode "
             "card plane, bilingual behaviour, Candidates separation, compact no-prose philosophy.")
    L.append("")
    L.append("## Frozen source")
    L.append("")
    L.append("| File | sha256 |")
    L.append("|---|---|")
    for k, v in R3_SOURCE_SHA256.items():
        L.append(f"| `r3_source/{k}` | `{v[:32]}…` |")
    L.append("")

    for tier in TIER_ORDER:
        rowset = [d for d in DISPOSITIONS if d["tier"] == tier]
        if not rowset:
            continue
        L.append(f"## {TIER_LABEL[tier]} ({len(rowset)})")
        L.append("")
        for d in rowset:
            r = rec[d["id"]]
            L.append(f"### `{d['id']}` — {d['action']} · {d['ws']}")
            L.append("")
            if r.get("title"):
                L.append(f"> **R3 finding:** {r['title']}")
                L.append("")
            trail = []
            if r.get("p1"):
                trail.append(f"pass-1 `{r['p1']}`")
            if r.get("p2_action"):
                sev = f" → `{r['p2_severity']}`" if r.get("p2_severity") else ""
                trail.append(f"pass-2 `{r['p2_action']}`{sev}")
            if r.get("verdict_resolution"):
                trail.append(f"verdict `{r['verdict_resolution']}`")
            L.append(f"*Source: {r['source']}*" + (f" · {' · '.join(trail)}" if trail else ""))
            L.append("")
            if r.get("verdict_note"):
                L.append(f"**Verdict note.** {r['verdict_note']}")
                L.append("")
            L.append(f"**R4 disposition.** {d['summary']}")
            L.append("")
            if d["proof"]:
                L.append("**Proof handles:** " + ", ".join(f"`{p}`" for p in d["proof"]))
                L.append("")

    L.append("## Preserved as separate production blockers — NOT waived here")
    L.append("")
    for b in verdict.get("production_migration_blockers_preserved") or []:
        L.append(f"- **`{b['id']}`** (PR #{b['pr']}, {b['status']}) — "
                 f"{' '.join(str(b.get('note','')).split())}")
    L.append("")
    L.append("Approving or revising a visual reference does not waive either, and neither is a reason "
             "to weaken the reference.")
    L.append("")
    L.append("## Resubmission")
    L.append("")
    L.append("Per the R3 verdict's final condition, resubmission is a **new frozen SHA with fresh critic "
             "receipts**. This cycle self-approves nothing: it produces the SHA and stops.")
    L.append("")

    OUT.write_text("\n".join(L))
    print(f"wrote {OUT.relative_to(ROOT)} — {len(rec)} record rows, {len(disp)} dispositions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
